### PR TITLE
*: handle both v1 and v1beta1 CRD versions

### LINKED ISSUE #3005: e2e test fails with additionalPrinterColumns in v1 CRDs
## Bug Report

**What did you do?**
Create v1 CRDs which include additionalPrinterColumns i.e. 

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dashboards.appconnect.ibm.com
spec:
  group: appconnect.ibm.com
  names:
    categories:
    - all
    - ace
    - cp4i
    kind: Dashboard
    listKind: DashboardList
    plural: dashboards
    singular: dashboard
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.versions.reconciled
      name: ResolvedVersion
      type: string
    - jsonPath: .status.replicas
      name: Replicas
      type: integer
    - jsonPath: .status.customImages
      name: CustomImages
      type: boolean
    - jsonPath: .status.conditions[0].type
      name: Status
      type: string
    - jsonPath: .status.conditions[0].lastTransitionTime
      name: LastUpdate
      type: date
.......
```
These were generated using `operator-sdk generate crds --crd-version v1`. These CRDs will deploy fine. When running e2e test, it fails. If I switch the CRDs to use the v1beta1 API then the e2e runs without issue. 

**What did you expect to see?**

The e2e test to run as normal

**What did you see instead? Under which circumstances?**

Running e2e results in an error being thrown
```
Robs-MBP-3:ibm-appconnect convery$ operator-sdk test local ./test/e2e --operator-namespace ace-rob --verbose --up-local
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/empty.yaml936751762", "-globalMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/global-manifest.yaml021941961", "-root", "/Users/convery/Documents/GitHub-IBM/ACEcc/ibm-appconnect-operator/stable/ibm-appconnect-bundle/operators/ibm-appconnect", "-parallel=1", "-localOperator", "-skipCleanupOnError=false"} 
time="2020-05-11T15:46:19+01:00" level=fatal msg="failed to create resource(s) in global resource manifest: CustomResourceDefinition.apiextensions.k8s.io \"dashboards.appconnect.ibm.com\" is invalid: [spec.additionalPrinterColumns[0].JSONPath: Required value, spec.additionalPrinterColumns[1].JSONPath: Required value, spec.additionalPrinterColumns[2].JSONPath: Required value, spec.additionalPrinterColumns[3].JSONPath: Required value, spec.additionalPrinterColumns[4].JSONPath: Required value]"
FAIL	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e	15.078s
?   	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e/testcontentserver	[no test files]
?   	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e/testcontentserver/contentserver	[no test files]
FAIL
FATA[0020] Failed to build test binary: failed to exec []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/empty.yaml936751762", "-globalMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/global-manifest.yaml021941961", "-root", "/Users/convery/Documents/GitHub-IBM/ACEcc/ibm-appconnect-operator/stable/ibm-appconnect-bundle/operators/ibm-appconnect", "-parallel=1", "-localOperator", "-skipCleanupOnError=false"}: exit status 1 
```

**Environment**
* operator-sdk version: 0.17.0
* go version: 0.13.5
* Kubernetes version information: v1.17.1
* Kubernetes cluster kind: OCP 4.4
* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** either use a v1 CRD directly or convert between v1beta1 and v1.

**Motivation for the change:** the SDK should support both v1 and v1beta1 CRDs anywhere relevant because `operator-sdk generate crds` generates both types. Instead of converting to v1 in all cases, which could be error prone ex. validation keys differ, these changes handle both explicitly.

Closes #3005

### CODE REVIEW

File: cmd/operator-sdk/generate/internal/genutil.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ func PluginKeyToOperatorType(pluginKey string) projutil.OperatorType {
 }
 
 // WriteCRDs writes each CustomResourceDefinition in crds to w.
-func WriteCRDs(w io.Writer, crds ...v1beta1.CustomResourceDefinition) error {
+func WriteCRDs(w io.Writer, crds ...apiextv1.CustomResourceDefinition) error {
```
Comment (estroz) [inline cmd/operator-sdk/generate/internal/genutil.go:70]: I am a little worried that writing a v1 CRD when the one being copied could be v1beta1 will break things. Need to make sure conversion always generates a valid manifest.

Comment (estroz) [reply cmd/operator-sdk/generate/internal/genutil.go]: By handling both v1 and v1beta1 CRDs explicitly we avoid this issue, although with more verbose code.

File: cmd/operator-sdk/generate/internal/genutil.go [hunk 2]
```diff
@@ -66,65 +67,82 @@ func PluginKeyToOperatorType(pluginKey string) projutil.OperatorType {
...
+		if err := writeObjectToFile(dir, obj, fileName); err != nil {
 			return err
 		}
 	}
 	return nil
 }
 
-func makeCRDFileNameLegacy(crd v1beta1.CustomResourceDefinition) string {
-	return fmt.Sprintf("%s_%s_crd.yaml", crd.Spec.Group, crd.Spec.Names.Plural)
+func makeCRDFileNameLegacy(group, resource string) string {
```
Comment (fabianvf) [inline cmd/operator-sdk/generate/internal/genutil.go:129]: I assume group/resource is enough to differentiate, and there's no reason to have a v1beta1 AND v1 CRD for the same resource (that probably doesn't even work). Even if that's not valid, if a user does provide them which one wins the write?

Comment (estroz) [reply cmd/operator-sdk/generate/internal/genutil.go:129]: Added a check for duplicate v1 and v1beta1 file names just to be sure.

File: cmd/operator-sdk/generate/internal/genutil.go [hunk 3]
```diff
@@ -66,65 +67,82 @@ func PluginKeyToOperatorType(pluginKey string) projutil.OperatorType {
...
 	}
-	for _, crd := range crds {
-		if err := writeCRDFile(dir, crd, makeCRDFileName(crd)); err != nil {
+	for _, obj := range objs {
+		var fileName string
+		switch t := obj.(type) {
+		case apiextv1.CustomResourceDefinition:
+			fileName = makeCRDFileName(t.Spec.Group, t.Spec.Names.Plural)
+		case apiextv1beta1.CustomResourceDefinition:
+			fileName = makeCRDFileName(t.Spec.Group, t.Spec.Names.Plural)
```
[the remark this answers is not in the document]
Comment (estroz) [reply cmd/operator-sdk/generate/internal/genutil.go:91]: Yeah I'm not happy about this code duplication, it's just easier until we fully remove v1beta1 CRD support in a few k8s releases.
