### PR TITLE
pkg/helm: install resources in same namespace as CR

### LINKED ISSUE #2416: Helm resources are created in the operator namespace instead of the CR namespace
## Bug Report

**What did you do?**
I posted about this issue in slack. I've upgraded from 0.10.0 to 0.14.0. The operator is releasing into the same namespace that it is deployed in instead of where the CR's are created. This was confirmed by @joelanford on slack.

**What did you expect to see?**
The resources created by the operator are created in the CR's namespace.

**What did you see instead? Under which circumstances?**
The resources created by the operator are created in the operator's namespace.

**Environment**
* operator-sdk version:
0.14.0

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
Helm

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
This PR fixes a bug that causes all release resources
to be created in the namespace that the helm-operator is deployed
in, not the namespace that the CR is deployed in.

**Motivation for the change:**
Closes #2416

### CODE REVIEW

File: pkg/helm/client/client.go [hunk 1]
```diff
@@ -62,10 +54,32 @@ func (c *restClientGetter) ToRESTMapper() (meta.RESTMapper, error) {
...
+type namespaceClientConfig struct {
+	namespace string
+}
+
+func (c namespaceClientConfig) RawConfig() (clientcmdapi.Config, error) {
+	return clientcmdapi.Config{}, nil
+}
+
+func (c namespaceClientConfig) ClientConfig() (*rest.Config, error) {
+	return nil, nil
```
Comment (camilamacedo86) [inline pkg/helm/client/client.go]: Why it is required since always return nil and nil?

File: pkg/helm/client/client.go [hunk 2]
```diff
@@ -62,10 +54,32 @@ func (c *restClientGetter) ToRESTMapper() (meta.RESTMapper, error) {
...
+}
+
+func (c namespaceClientConfig) Namespace() (string, bool, error) {
+	return c.namespace, false, nil
+}
+
+func (c namespaceClientConfig) ConfigAccess() clientcmd.ConfigAccess {
 	return nil
```
Comment (camilamacedo86) [inline pkg/helm/client/client.go]: same here

File: pkg/helm/client/client.go (hunk 1 above)
Comment (joelanford) [reply pkg/helm/client/client.go]: These functions are required because `ToRawKubeConfigLoader()` needs to return a `clientcmd.ClientConfig` which is an interface that requires that all of these functions be implemented.

As far as I can tell, Helm only uses `ToRawKubeConfigLoader().Namespace()` and not the other functions (I'll double check this), so it should be okay for those to be no-ops. We _could_ have those unused functions return `fmt.Errorf("not implemented")` if that makes sense.

**Comment by joelanford** [comment]
Before we merge this, I also want to update the e2e helm test to deploy the CR in a separate namespace to prevent this regression in the future.

File: pkg/helm/client/client.go (hunk 1 above)
Comment (joelanford) [reply pkg/helm/client/client.go]: Just following up on the question of how `ToRawKubeConfigLoader()` is used. Here's the grep output from the Helm project:

```console
$ grep -r ToRaw *
pkg/kube/factory.go:	// ToRawKubeConfigLoader return kubeconfig loader as-is
pkg/kube/factory.go:	ToRawKubeConfigLoader() clientcmd.ClientConfig
pkg/kube/client.go:	if ns, _, err := c.Factory.ToRawKubeConfigLoader().Namespace(); err == nil {
pkg/cli/environment.go:	if ns, _, err := s.RESTClientGetter().ToRawKubeConfigLoader().Namespace(); err == nil {
```

So yeah, only `Namespace()` actually needs to be implemented.

**Comment by joelanford** [comment]
@camilamacedo86 PTAL

File: hack/tests/e2e-helm.sh [hunk 3]
```diff
@@ -10,20 +10,24 @@ ROOTDIR="$(pwd)"
...
+test_namespace="test-e2e-helm"
+
 deploy_operator() {
-    kubectl create -f "$OPERATORDIR/deploy/service_account.yaml"
-    kubectl create -f "$OPERATORDIR/deploy/role.yaml"
-    kubectl create -f "$OPERATORDIR/deploy/role_binding.yaml"
     kubectl create -f "$OPERATORDIR/deploy/crds/helm.example.com_nginxes_crd.yaml"
-    kubectl create -f "$OPERATORDIR/deploy/operator.yaml"
+    kubectl create -f "$OPERATORDIR/deploy/service_account.yaml"
+    kubectl create -f "$OPERATORDIR/deploy/cluster_role.yaml"
```
Comment (estroz) [inline hack/tests/e2e-helm.sh]: The addition of `--namespace` below makes sense, but why is the test operator now cluster-scoped? Shouldn't its manifests just have a different namespace?

Comment (joelanford) [reply hack/tests/e2e-helm.sh]: The change to the `operator.yaml` is to make it watch all namespaces so that it can see CRs outside of its own namespace. Not sure if that answers your question...

**Comment by joelanford** [comment]
Closes #2416

File: pkg/helm/client/client.go [hunk 4]
```diff
@@ -28,25 +28,17 @@ import (
...
-// NewFromManager returns a Kubernetes client that can be used with
-// a Tiller server.
-func NewFromManager(mgr manager.Manager) (*kube.Client, error) {
-	c, err := NewRESTClientGetter(mgr)
-	if err != nil {
-		return nil, err
-	}
-	return kube.New(c), nil
-}
-
```
Comment (camilamacedo86) [inline pkg/helm/client/client.go]: It as unused before.
