### PR TITLE
internal/pkg/scaffold/olm-catalog/config.go: omit owned CRD's from CSV if no default CRD's dir

### LINKED ISSUE #1334: unable to generate olm-csv if no CRD are defined
## Bug Report

**What did you do?**
I wanted to generate the OCL CSV. I have an operator that does not define any new CRD. I got the following output:
```
operator-sdk olm-catalog gen-csv --csv-version 0.1.0
INFO[0000] Generating CSV manifest version 0.1.0        
Error: catalog scaffold failed: (lstat deploy/crds: no such file or directory)
Usage:
  operator-sdk olm-catalog gen-csv [flags]

Flags:
      --csv-config string     Path to CSV config file. Defaults to deploy/olm-catalog/csv-config.yaml
      --csv-version string    Semantic version of the CSV
      --from-version string   Semantic version of an existing CSV to use as a base
  -h, --help                  help for gen-csv
      --update-crds           Update CRD manifests in deploy/{operator-name}/{csv-version} the using latest API's
``` 

**What did you expect to see?**
Not sure, this was the first time I was running this command, not an error though.

**What did you see instead? Under which circumstances?**
see the output above.

The general question is: can OLM be used with an operator that does not define any new CRD? If yes the `operato-sdk olm-catalog gen-cvs` command should work.

**Environment**
* operator-sdk version:
```
operator-sdk --version
operator-sdk version v0.6.0+git
```
* go version:

```
go version
go version go1.11.6 linux/amd64
```

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** Omit owned CRD's from CSV if no default CRD's dir, and notify user with info messages.

**Motivation for the change:** See #1334.

Closes #1334

### CODE REVIEW

File: internal/pkg/scaffold/olm-catalog/config.go [hunk 1]
```diff
@@ -78,9 +79,17 @@ func (c *CSVConfig) setFields() error {
...
 			return err
 		}
+		if os.IsNotExist(err) {
+			log.Infof(`Default CRDs dir "%s" does not exist. Omitting field spec.customresourcedefinitions.owned from CSV.`, scaffold.CRDsDir)
+			return nil
+		}
+		if len(paths) == 0 {
+			log.Infof(`Default CRDs dir "%s" is empty. Omitting field spec.customresourcedefinitions.owned from CSV.`, scaffold.CRDsDir)
+			return nil
+		}
```
Comment (joelanford) [inline internal/pkg/scaffold/olm-catalog/config.go]: If we add more logic near the bottom of this function in the future, there will be an edge case where that logic is skipped.

Since these are valid-ish cases, should we fall through to the `return nil` in line 123 instead of returning immediately here?

```go
if os.IsNotExist(err) {
	log.Infof(...)
} else if len(paths) == 0 {
	log.Infof(...)
} else {
	c.CRDCRPaths = paths
}
```
