### PR TITLE
internal/pkg/scaffold/crd.go: overwrite CRD manifests for Go operators

### LINKED ISSUE #1212: operator-sdk generate openapi ignores +kubebuilder:printcolumn
## Bug Report

**What did you do?**
added the following annotation:

```go
// +kubebuilder:printcolumn:name="Replicas",type="integer",JSONPath=".spec.Replicas",description="The number of MyCoolCRD instances"
type MyCoolCRD struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MyCoolCRDSpec   `json:"spec,omitempty"`
	Status MyCoolCRDStatus `json:"status,omitempty"`
}
```

**What did you expect to see?**
Expected to see it in the generated CRD.

**What did you see instead? Under which circumstances?**
```
$ GOFLAGS="-v" operator-sdk generate openapi
INFO[0001] Running OpenAPI code-generation for Custom Resource group versions: [k8s:[v1alpha1], ] 
2019/03/15 14:36:53 Code for OpenAPI definitions generated

[debug] name="Replicas"
[debug] type="integer"
[debug] JSONPath=".spec.Replicas"
[debug] description="The number of MyCoolCRD instances"INFO[0004] Created deploy/crds/k8s_v1alpha1_woot_crd.yaml 
INFO[0004] Code-generation complete. 
```

**Environment**
* operator-sdk version:
operator-sdk version v0.5.0+git

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**

**Additional context**
If it is an upstream issue please advise the repo to report and probably to fix it. Kubebuilder looks great as a tool but it looks a bit immature at the same time. I've run in a number of issues possibly related to kubebuilder in a couple of days and don't want to flood here ) And I see that there are other people complaining about it.

### LINKED ISSUE #1323: generate openapi removes shortNames from CRD
## Bug Report

**What did you do?**
1. operator-sdk add api ...
2. Edit `deploy/crds/my_crd.yaml` to add `shortNames: ["blah"]`.
3. operator-sdk generate openapi

**What did you expect to see?**
The validation section should be filled in without removing my shortNames.

**What did you see instead? Under which circumstances?**
The generator removed my shortNames.

**Environment**
* operator-sdk version: v0.7.0

* go version: 1.12.2

**Additional context**

I also tried the `+kubebuilder` annotation for setting shortNames, but it was ignored:

```
// +kubebuilder:resource:path=services,shortName=to;ty
```

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** overwrite on-disk CRD manifests for Go operators.

**Motivation for the change:** `controller-tools` [CRD generator](https://godoc.org/sigs.k8s.io/controller-tools/pkg/crd/generator#Generator) is used for Go operators. This generator supports _most_ OpenAPIv3 validation [properties](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#properties), and other nice-to-have automation, through Go [code annotations](https://book.kubebuilder.io/beyond_basics/generating_crd.html). Annotations for all validation properties is a WIP. Generating CRD manifests using these annotations is more reproducible and robust than preserving data in on-disk CRD manifests, so they should be overwritten every time a command that scaffolds a CRD manifest is invoked.

Closes #1212, closes #1323

### CODE REVIEW

File: internal/pkg/scaffold/crd.go [hunk 1]
```diff
@@ -132,8 +131,10 @@ func (s *CRD) CustomRender() ([]byte, error) {
 				if err = yaml.Unmarshal(cb, dstCRD); err != nil {
 					return nil, err
 				}
-				dstCRD.Spec.Validation = val
+				mergeCRDs(dstCRD, srcCRD)
```
Comment (estroz) [inline internal/pkg/scaffold/crd.go]: To prevent bugs like this happening in the future, I suggest we directly use the generated CRD's instead of trying to use old CRD data. Thoughts?

Comment (LiliC) [reply internal/pkg/scaffold/crd.go]: Would there be anything in the old CRD data we would miss by using the generated CRDs? If not, that sounds good to me.

Comment (estroz) [reply internal/pkg/scaffold/crd.go]: Custom validation is the main issue. I submitted a [ticket upstream](https://github.com/kubernetes-sigs/controller-tools/issues/156) to merge existing and new validations, and have #1155 to do that in the SDK. Part of the issue is there's no good way to determine what a user has manually added and what is old in all fields; parsing `+kubebuilder` tagged types only partially solves the problem.

Other than validation, there's not much a user can add that isn't already autogenerated.

Comment (hasbro17) [reply internal/pkg/scaffold/crd.go]: > I suggest we directly use the generated CRD's instead of trying to use old CRD data

@estroz Do you mean just overwrite the entire CRD and not just the validation+printerColumns fields?
What if the user needs modifies other fields like the scope of the CRD.
Or adds in custom short names for the CRD.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#customresourcedefinitionnames-v1beta1-apiextensions-k8s-io

I think we can't autogenerate that.

Comment (estroz) [reply internal/pkg/scaffold/crd.go]: @hasbro17 I believe most, if not all, CRD fields can be set using code annotations:
* scope: https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/internal/codegen/parse/crd.go#L76-L80
* short names (comma separated list): https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/internal/codegen/parse/index.go#L132-L133

That being said, there's no documentation on CRD generation in the SDK to actually tell users this is possible. I'm working on that.

Comment (hasbro17) [reply internal/pkg/scaffold/crd.go]: @estroz I'm fine with just overwriting the entire CRD if we have the documentation to point out all the kubebuilder comment annotations for the CRD.
Your call on if you want to add the documentation to this PR or if you want to open an issue and do a follow up.

Comment (estroz) [reply internal/pkg/scaffold/crd.go]: I'll do the former here so we can fix all issues going forward in one PR.

**Comment by hasbro17** [comment]
Also related #1323

File: internal/pkg/scaffold/crd.go [hunk 2]
```diff
@@ -41,6 +39,20 @@ type CRD struct {
 
 	// IsOperatorGo is true when the operator is written in Go.
 	IsOperatorGo bool
+
+	once sync.Once
+	fs   afero.Fs // For testing, ex. afero.NewMemMapFs()
```
Comment (estroz) [inline internal/pkg/scaffold/crd.go]: I'm repeating this pattern from [CSV generation](https://github.com/estroz/operator-sdk/blob/2e6b2e30fe53a323a6e19419059999b734d93f2d/pkg/scaffold/olm-catalog/csv.go#L55-L56) for easier testing. In the future this should be refactored into `Input` so all scaffolds can access a test `afero.Fs`.

**Comment by hasbro17** [comment]
Worth mentioning this in the CHANGELOG to warn users expecting to preserve manual edits to the CRD manifest.
