### PR TITLE
pkg/ansible/proxy; Do not inject owner references on subresource requests

### LINKED ISSUE #911: kubectl exec task inside Ansible Operator not handled properly within proxy
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
Put a `kubectl exec` task inside of the Ansible logic that AO runs.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
I expected for the `kubectl exec` command to upgrade its connection to be able to run commands inside of a pod in the cluster.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
Task fails with error:
```
F0112 21:34:31.338682    9872 helpers.go:116] error: unable to upgrade connection: Could not deserialize request body
```
**Environment**
* operator-sdk version:
`v0.3.0+git`

  Insert operator-sdk release or Git SHA here. If you have paste the Gopkg.lock operator-sdk information here. 

* Kubernetes version information:
v1.11.0
  Insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
Ansible
**Possible Solution**

AO proxy (specifically the cache) needs to pass along GET requests on a sub resource to the apiserver.
**Additional context**

Additionally, we need to be setting the `Content-Type` header on the response since right now it is set to `text/plain`.

### PR DESCRIPTION
**Pull request by dymurray**
**Description of the change:**
* Adds a `Content-Type` header to our cache.
* Checks if a subresource is present on the request before injecting owner reference

**Motivation for the change:**
Kubectl exec now works from within Ansible Operator tasks

Closes #911

### CODE REVIEW

File: pkg/ansible/proxy/proxy.go [hunk 1]
```diff
@@ -66,6 +66,8 @@ func CacheResponseHandler(h http.Handler, informerCache cache.Cache, restMapper
 				log.Error(err, "Failed to convert request")
 				break
 			}
+			// Set Content-Type header
+			w.Header().Set("Content-Type", "application/json")
```
Comment (shawn-hurley) [inline pkg/ansible/proxy/proxy.go]: Let's do this closer to the other cache header we set. I don't think this would be an issue but don't want to set this, if the api-server is not going to send json back.

**Comment by dymurray** [comment]
Just want to note that as I test this, I sometimes get a log message:
```
ERROR: logging before flag.Parse: E0116 11:45:29.890427   23845 upgradeaware.go:338] Error proxying data from client to backend: read tcp 127.0.0.1:8888->127.0.0.1:58380: read: connection reset by peer
```

It is not 100% consistent and it appears that the `kubectl exec` task succeeds without a problem. I have found a [link](https://github.com/kubernetes/kubernetes/issues/30489#issuecomment-245394081) which might explain what is occurring. I'm not finding any errors in the apiserver logs though.

**Comment by dymurray** [comment]
I have confirmed the above comment is due to a bug in `kubectl proxy` which minikube is running under the hood to expose the apiserver to the end user outside of the VM. This is not a problem when running the operator in production as a pod on the cluster. This PR is good to be merged.
