### PR TITLE
fix scripts to run in mac os x and or linux

### LINKED ISSUE #2257: Commands using sed the shell scripts do not work for Mac OS
## Bug Report

**What did you do?**
For example, try to run make test-sanity in a mac os x. 

**What did you expect to see?**
The test be executed with success

**What did you see instead? Under which circumstances?**
An error because of the sed

**Possible Solution**
Check if is mac or Linux and then exec accordingly the command. Or change the implementation in order to not require sed usage.

**Additional context**
See the places: https://github.com/operator-framework/operator-sdk/search?l=Shell&q=sed

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
fix scripts to run in mac os x and/or Linux

**Motivation for the change:**
Closes #2257

### CODE REVIEW

File: hack/generate/gen-test-framework.sh [hunk 1]
```diff
@@ -13,7 +13,13 @@ cd test/test-framework
...
 # Ensure test-framework is up-to-date with current Go project dependencies.
 echo "$(../../build/operator-sdk print-deps)" > go.mod
-sed -i 's|github.com/operator-framework/operator-sdk\s\+master||g' go.mod
+
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  sed -i " " 's|github.com/operator-framework/operator-sdk\s\+master||g' go.mod
+else
+  sed -i 's|github.com/operator-framework/operator-sdk\s\+master||g' go.mod
+fi
+
```
Comment (joelanford) [inline hack/generate/gen-test-framework.sh]: This should work on both Mac and Linux:
```
sed -i".bak" -E -e "s|github.com/operator-framework/operator-sdk[[:blank:]]+master||g" go.mod; rm -f go.mod.bak
```

Important things to note:
* There is no space between `-i` and the quoted extension
* Use -E to specify POSIX extended regular expressions.
* Use `-e` to specify the sed script.

Ditto for all other usages.

File: hack/tests/e2e-helm.sh [hunk 2]
```diff
@@ -125,12 +125,15 @@ if echo $log | grep -q "failed to generate RBAC rules"; then
...
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
+
 operator-sdk build "$DEST_IMAGE"
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-sed -i "s|REPLACE_IMAGE|$DEST_IMAGE|g" deploy/operator.yaml
-sed -i 's|Always|Never|g' deploy/operator.yaml
+
+sed -i".bak" -E -e "s|REPLACE_IMAGE|$DEST_IMAGE|g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-helm.sh]:
```suggestion
sed -i".bak" -E -e "s|Always|Never|g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```

File: hack/tests/e2e-helm.sh [hunk 3]
```diff
@@ -125,12 +125,15 @@ if echo $log | grep -q "failed to generate RBAC rules"; then
 fi
 
 pushd nginx-operator
-sed -i 's|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-helm.sh]:
```suggestion
sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
```

File: ci/tests/e2e-ansible.sh [hunk 4]
```diff
@@ -158,9 +158,8 @@ operator-sdk new memcached-operator --api-version=ansible.example.com/v1alpha1 -
 pushd memcached-operator
 # Add a second Kind to test watching multiple GVKs
 operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
-sed -i 's|{{ pull_policy.default..Always.. }}|Always|g' deploy/operator.yaml
-cp deploy/operator.yaml deploy/operator-copy.yaml
-sed -i "s|{{ REPLACE_IMAGE }}|$IMAGE|g" deploy/operator.yaml
+
+sed -i".bak" -E -e "s|{{ pull_policy.default..Always.. }}|Always|g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```
Comment (camilamacedo86) [inline ci/tests/e2e-ansible.sh]:
```suggestion
sed -i".bak" -E -e "s|{{ pull_policy.default..Always.. }}|Always|g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
cp deploy/operator.yaml deploy/operator-copy.yaml
sed -i".bak" -E -e "s|{{ REPLACE_IMAGE }}|$IMAGE|g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```

File: ci/tests/subcommand-scorecard.sh [hunk 5]
```diff
@@ -17,11 +17,13 @@ eval IMAGE=$IMAGE_FORMAT
...
 trap_add 'cp $ROOTDIR/backup.yaml $DEFAULT_CONFIG_PATH && rm $ROOTDIR/backup.yaml' EXIT
-sed 's|REPLACE_IMAGE|'$IMAGE'|g' -i $DEFAULT_CONFIG_PATH
+
+sed -i".bak" -E -e "s|REPLACE_IMAGE|$IMAGE2|g" $DEFAULT_CONFIG_PATH; rm -f $DEFAULT_CONFIG_PATH.bak
 
 cp $CONFIG_PATH $ROOTDIR/backup2.yaml
 trap_add 'cp $ROOTDIR/backup2.yaml $CONFIG_PATH && rm $ROOTDIR/backup2.yaml' EXIT
-sed 's|REPLACE_IMAGE|'$IMAGE'|g' -i $CONFIG_PATH
+
+sed -i".bak" -E -e "s|REPLACE_IMAGE|$IMAGE2|g" $CONFIG_PATH; rm -f $CONFIG_PATH.bak
```
Comment (camilamacedo86) [inline ci/tests/subcommand-scorecard.sh]:
```suggestion
sed -i".bak" -E -e 's|REPLACE_IMAGE|'$IMAGE'|g' -i $CONFIG_PATH'; rm -f $CONFIG_PATH.bak
```

File: ci/tests/subcommand-scorecard.sh [hunk 6]
```diff
@@ -17,11 +17,13 @@ eval IMAGE=$IMAGE_FORMAT
 cp $DEFAULT_CONFIG_PATH $ROOTDIR/backup.yaml
 cp $DEFAULT_CONFIG_PATH_CI $DEFAULT_CONFIG_PATH
 trap_add 'cp $ROOTDIR/backup.yaml $DEFAULT_CONFIG_PATH && rm $ROOTDIR/backup.yaml' EXIT
-sed 's|REPLACE_IMAGE|'$IMAGE'|g' -i $DEFAULT_CONFIG_PATH
+
+sed -i".bak" -E -e "s|REPLACE_IMAGE|$IMAGE2|g" $DEFAULT_CONFIG_PATH; rm -f $DEFAULT_CONFIG_PATH.bak
```
Comment (camilamacedo86) [inline ci/tests/subcommand-scorecard.sh]:
```suggestion
sed -i".bak" -E -e 's|REPLACE_IMAGE|'$IMAGE'|g' -i $DEFAULT_CONFIG_PATH; rm -f $DEFAULT_CONFIG_PATH.bak
```

File: hack/tests/e2e-ansible-molecule.sh [hunk 7]
```diff
@@ -46,11 +46,9 @@ cat "$ROOTDIR/test/ansible-memcached/watches-v1-kind.yaml" >> memcached-operator
 
 # Test local
 pushd memcached-operator
-# Use the following sed command to check it on macOsX.
-# More info: https://www.mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/
-# sed -i "" 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
-# The following code is the default used (Not valid for MacOSX)
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible-molecule.sh]:
```suggestion
sed -i".bak" -E -e 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile build/Dockerfile; rm -f build/Dockerfile.bak
```

File: hack/tests/e2e-ansible-molecule.sh [hunk 8]
```diff
@@ -60,11 +58,9 @@ popd
 popd
 
 pushd "${ROOTDIR}/test/ansible-inventory"
-# Use the following sed command to check it on macOsX.
-# More info: https://www.mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/
-# sed -i "" 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
-# The following code is the default used (Not valid for MacOSX)
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible-molecule.sh]:
```suggestion
sed -i".bak" -E -e 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile; rm -f build/Dockerfile.bak
```

File: hack/tests/e2e-ansible.sh [hunk 9]
```diff
@@ -145,12 +145,16 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
 pushd memcached-operator
 # Add a second Kind to test watching multiple GVKs
 operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]:
```suggestion
sed -i".bak" -E -e 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile; rm -f build/Dockerfile.bak
```

File: hack/tests/e2e-ansible.sh [hunk 10]
```diff
@@ -145,12 +145,16 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
...
+
 operator-sdk build "$DEST_IMAGE"
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
+
+pushd "${ROOTDIR}/test/ansible-inventory"
+sed -i".bak" -E -e "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" build/Dockerfile; rm -f build/Dockerfile.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]:
```suggestion
```

File: hack/tests/e2e-ansible.sh [hunk 11]
```diff
@@ -145,12 +145,16 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
...
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+
+sed -i".bak" -E -e "s|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g" build/Dockerfile; rm -f build/Dockerfile.bak
+
 operator-sdk build "$DEST_IMAGE"
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
+
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]:
```suggestion
sed -i".bak" -E -e "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml; rm -f deploy/operator.yam.bak
sed -i".bak" -E -e 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml; rm -f deploy/operator.yam.bak
```

File: ci/tests/e2e-ansible.sh [hunk 12]
```diff
@@ -158,9 +158,10 @@ operator-sdk new memcached-operator --api-version=ansible.example.com/v1alpha1 -
 pushd memcached-operator
 # Add a second Kind to test watching multiple GVKs
 operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
-sed -i 's|{{ pull_policy.default..Always.. }}|Always|g' deploy/operator.yaml
+
```
Comment (joelanford) [inline ci/tests/e2e-ansible.sh]: Nit: is there a reason for all of the introduced newline spacing between the `sed` commands? The new lines make it more difficult to review the changes since the removals and additions are now on separate lines.

File: hack/tests/e2e-ansible.sh [hunk 13]
```diff
@@ -145,12 +145,16 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
...
+sed -i".bak" -E -e 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile; rm -f build/Dockerfile.bak
+
 operator-sdk build "$DEST_IMAGE"
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
+sed -i".bak" -E -e "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml; rm -f deploy/operator.yam.bak
+sed -i".bak" -E -e 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml; rm -f deploy/operator.yam.bak
+pushd "${ROOTDIR}/test/ansible-inventory"
```
Comment (joelanford) [inline hack/tests/e2e-ansible.sh]: Do we need to change directory into `"${ROOTDIR}/test/ansible-inventory"`? Regardless, this change seems out of scope for this PR.

File: hack/tests/e2e-ansible-molecule.sh [hunk 14]
```diff
@@ -46,11 +46,11 @@ cat "$ROOTDIR/test/ansible-memcached/watches-v1-kind.yaml" >> memcached-operator
...
-# Use the following sed command to check it on macOsX.
-# More info: https://www.mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/
-# sed -i "" 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
-# The following code is the default used (Not valid for MacOSX)
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  sed -i " " 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+else
+  sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+fi
```
Comment (joelanford) [inline hack/tests/e2e-ansible-molecule.sh]: Can this be combined into one command, similar to the others?

File: hack/tests/e2e-ansible-molecule.sh [hunk 15]
```diff
@@ -60,11 +60,11 @@ popd
...
```
Comment (joelanford) [inline hack/tests/e2e-ansible-molecule.sh]: Can this be combined into one command, similar to the others?

File: hack/tests/e2e-ansible.sh [hunk 16]
```diff
@@ -145,12 +145,16 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
 pushd memcached-operator
 # Add a second Kind to test watching multiple GVKs
 operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  sed -i " " 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+else
+  sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+fi
```
Comment (joelanford) [inline hack/tests/e2e-ansible.sh]: Can this be combined into one command, similar to the others?

File: hack/tests/e2e-helm.sh [hunk 17]
```diff
@@ -125,12 +125,16 @@ if echo $log | grep -q "failed to generate RBAC rules"; then
 fi
 
 pushd nginx-operator
-sed -i 's|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  sed -i " " 's|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+else
+  sed -i 's|\(FROM quay.io/operator-framework/helm-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+fi
```
Comment (joelanford) [inline hack/tests/e2e-helm.sh]: Can this be combined into one command, similar to the others?

Comment (camilamacedo86) [reply hack/tests/e2e-helm.sh]: Note that it is in WIP and I am doing it step by step because I am trying to make the regex work with your suggestion so far. See that the current changes are not passing:

> +sed -i.bak -E -e 's|{{ REPLACE_IMAGE }}|quay.io/example/memcached-operator:v0.0.2|g' deploy/operator.yaml
> sed: -e expression #1, char 65: Invalid preceding regular expression
> +rm -rf /tmp/tmp.fNuNyKjuVW

The error is with: https://github.com/operator-framework/operator-sdk/pull/2260/files#diff-a8c10525e5714b373fd8c481bd9feb85R156

File: hack/tests/e2e-ansible.sh [hunk 18]
```diff
@@ -149,13 +149,9 @@ sed -i".bak" -E -e 's/(FROM quay.io\/operator-framework\/ansible-operator)(:.*)?
...
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-if [[ "$OSTYPE" == "darwin"* ]]; then
-  sed -i  " " "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-  sed -i  " " 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
-else
-  sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-  sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
-fi
+sed -i".bak" -E -e "s/{{ REPLACE_IMAGE }}/$DEST_IMAGE/g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]:
```suggestion
sed -i".bak" -e "s/{{ REPLACE_IMAGE }}/$DEST_IMAGE/g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```

File: hack/tests/e2e-ansible.sh [hunk 19]
```diff
@@ -145,12 +145,17 @@ cat "$ROOTDIR/test/ansible-memcached/watches-foo-kind.yaml" >> memcached-operato
...
 operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
-sed -i 's|\(FROM quay.io/operator-framework/ansible-operator\)\(:.*\)\?|\1:dev|g' build/Dockerfile
+sed -i".bak" -E -e 's/(FROM quay.io\/operator-framework\/ansible-operator)(:.*)?/\1:dev/g' build/Dockerfile; rm -f build/Dockerfile.bak
 operator-sdk build "$DEST_IMAGE"
 # If using a kind cluster, load the image into all nodes.
 load_image_if_kind "$DEST_IMAGE"
-sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
-sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  sed -i  " " "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
```
Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]: @joelanford just this one was required to keep with the if.

Comment (camilamacedo86) [inline hack/tests/e2e-ansible.sh]: @joelanford just here that I could not find a solution because of "{{" which should be a string and is not.

Comment (joelanford) [reply hack/tests/e2e-ansible.sh]:
```sh
DEST_IMAGE_ESCAPED="$(printf '%s' "$DEST_IMAGE" | sed 's/[.[\/*^$]/\\&/g')"
sed -i".bak" -E -e "s/\{\{ REPLACE_IMAGE \}\}/$DEST_IMAGE_ESCAPED/g" deploy/operator.yaml; rm -f deploy/operator.yaml.bak
sed -i".bak" -E -e 's/\{\{ pull_policy.default..Always.. \}\}/Never/g' deploy/operator.yaml; rm -f deploy/operator.yaml.bak
```

Comment (joelanford) [reply hack/tests/e2e-ansible.sh]: I think I was wrong originally when I said that `|` characters don't work with BSD sed. It seems that they do, in fact, work with both GNU sed and BSD sed. So I think we should use `|` everywhere we were using it before so that we don't have to escape the forward slashes in the regex patterns and replacements.
