### PR TITLE
cmd/operator-sdk/new/cmd.go: fallback to default helm RBAC role without kubeconfig

### LINKED ISSUE #1625: Why is kubeconfig needed during operator-sdk new
## Type of question

operator-sdk general context

## Question

**What did you do?**
Running `operator-sdk new` fails because a kubeconfig cannot be found.

**What did you expect to see?**
Generation of Helm Operator files (Dockerfile, yamls, etc.)

**What did you see instead? Under which circumstances?**
```
INFO[0000] Creating new Helm operator 'instance-operator'. 
INFO[0000] Created helm-charts/instance  
Error: failed to get kubernetes config: could not locate a kubeconfig
Usage:
  operator-sdk new <project-name> [flags]

Flags:
      --api-version string          Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1) - used with "ansible" or "helm" types
      --dep-manager string          Dependency manager the new project will use (choices: "dep", "modules") (default "modules")
      --generate-playbook           Generate a playbook skeleton. (Only used for --type ansible)
      --header-file string          Path to file containing headers for generated Go files. Copied to hack/boilerplate.go.txt
      --helm-chart string           Initialize helm operator with existing helm chart (<URL>, <repo>/<name>, or local path)
      --helm-chart-repo string      Chart repository URL for the requested helm chart
      --helm-chart-version string   Specific version of the helm chart (default is latest version)
  -h, --help                        help for new
      --kind string                 Kubernetes CustomResourceDefintion kind. (e.g AppService) - used with "ansible" or "helm" types
      --skip-git-init               Do not init the directory as a git repository
      --type string                 Type of operator to initialize (choices: "go", "ansible" or "helm") (default "go")

Global Flags:
      --verbose   Enable verbose logging
```

**Environment**
* operator-sdk version:

  0.8.1

* Kubernetes version information:
  1.15.0

* Kubernetes cluster kind: 

**Additional context**
I understand needing a kubeconfig for testing with `up` but this shouldn't be needed for creating a new Operator. My use case is that I have Docker systems where I can build/publish images but is separate from my kubernetes cluster. While I may be able to find a work around with a fake K8s config, I think there should be an official solution.

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Updates `operator-sdk new --type=helm` to fallback to default RBAC rules if there is an error getting the kubeconfig or creating a discovery client.

**Motivation for the change:**
Closes #1625

### CODE REVIEW

File: cmd/operator-sdk/new/cmd.go [hunk 1]
```diff
@@ -325,19 +325,13 @@ func doHelmScaffold() error {
...
-		return fmt.Errorf("failed to get kubernetes discovery client: %s", err)
-	}
-
-	roleScaffold, err := helm.CreateRoleScaffold(dc, chart)
-	if err != nil {
-		return fmt.Errorf("failed to generate role scaffold: %s", err)
+	roleScaffold := helm.DefaultRoleScaffold
+	if k8sCfg, err := config.GetConfig(); err != nil {
+		log.Warnf("Using default RBAC rules: failed to get Kubernetes config: %s", err)
+	} else if dc, err := discovery.NewDiscoveryClientForConfig(k8sCfg); err != nil {
```
Comment (LiliC) [inline cmd/operator-sdk/new/cmd.go]: What happens here if `k8sCfg` is `nil` and we pass it to `NewDiscoveryClientForConfig `?

File: CHANGELOG.md [hunk 2]
```diff
@@ -22,6 +22,7 @@
 -  `CreateMetricsService()` function from the metrics package accepts an array of ServicePort objects ([]v1.ServicePort) as input to create Service metrics. `CRPortName` constant is added to describe the string of custom resource port name. ([#1560](https://github.com/operator-framework/operator-sdk/pull/1560))
 - Changed the flag `--skip-git-init` to [`--git-init`](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#new). This changes the default behavior of `operator-sdk new` to not initialize the new project directory as a git repository with `git init`. This behavior is now opt-in with `--git-init`. ([#1588](https://github.com/operator-framework/operator-sdk/pull/1588))
 - `operator-sdk new` will no longer create the initial commit for a new project, even with `--git-init=true`. ([#1588](https://github.com/operator-framework/operator-sdk/pull/1588))
+- Updated `operator-sdk new --type=helm` to fallback to a default RBAC role (instead of failing) when errors occur setting up the Kubernetes client necessary for role generation. ([#1627](https://github.com/operator-framework/operator-sdk/pull/1627))
```
Comment (LiliC) [inline CHANGELOG.md]: Nit: Can we break up this sentence so it reads easier, or just reverse it.

Comment (joelanford) [reply CHANGELOG.md]: 👍  reversing it sounds better.

File: cmd/operator-sdk/new/cmd.go (hunk 1 above)
Comment (joelanford) [reply cmd/operator-sdk/new/cmd.go]: In that case, `config.GetConfig()` would have to return `nil, nil`, which is probably not something that it would ever do. But better safe than sorry  🙂 . I'll check if the follow-on functions handle `nil` for both `k8sCfg` and `dc`.

Comment (LiliC) [reply cmd/operator-sdk/new/cmd.go]: Missed the else part of the if, nvm.
