### PR TITLE
pkg/restmapper,scaffold/cmd.go: override default restmapper

### LINKED ISSUE #1328: Default RESTMapper returns stale resources
## Bug Report

**What did you do?**
When applying multiple interdependent resources, e.g. CRD's + CR's, a race condition can result in an infinite loop where cached resources become stale.

**What did you expect to see?**
I expect to eventually receive the resource I created.

**What did you see instead? Under which circumstances?**
I kept getting the stale one

**Environment**
* operator-sdk version:
v0.7.0

* go version:
1.11.4

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
minikube

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**
Upstream bug: https://github.com/kubernetes-sigs/controller-runtime/issues/321

**Additional context**
Potential fix: https://github.com/openshift/cluster-network-operator/pull/95

### PR DESCRIPTION
**Pull request by jcrossley3**
This addresses a controller-runtime bug which can affect operators
that create CRD's and then CR's that refer to them, as the default
mapper never "sees" the new CRD's.

Fixes #1328 (originally from @danwinship)

### CODE REVIEW

**Comment by AlexNPavel** [comment]
Looks good. To fix the tests, you need to update `internal/pkg/scaffold/cmd_test.go` to match the expected scaffold output, and you need to commit the `Gopkg.lock` file after running `make dep`. Otherwise, this looks good to me.

/cc @shawn-hurley @joelanford @hasbro17

File: internal/pkg/scaffold/cmd.go [hunk 1]
```diff
@@ -122,6 +123,7 @@ func main() {
 	// Create a new Cmd to provide shared dependencies and start components
 	mgr, err := manager.New(cfg, manager.Options{
 		Namespace:          namespace,
+		MapperProvider:     restmapper.NewDynamicRESTMapper,
```
Comment (shawn-hurley) [inline internal/pkg/scaffold/cmd.go]: I am wondering if we should make this an opt-in feature because missing there is no mechanism's in place to back off expensive reloads on every miss. 

Thoughts?

Comment (jcrossley3) [reply internal/pkg/scaffold/cmd.go]: I reasoned that it's better to be slow than wrong, by default, but I could go either way.

Comment (danwinship) [reply internal/pkg/scaffold/cmd.go]: Solly wanted a backoff upstream (controller-runtime); that's why I haven't just submitted this there already.

I guess the case where it would matter would be if you're waiting for another operator to create a bunch of objects of some CRD type. So then every now and then you do 50 GETs, to see if the 50 objects have been created. Which, with this code, could result in 50 restmapper reloads if the CRD hadn't been created yet.

**Comment by shawn-hurley** [comment]
We probably want to update the changelog with this change as well

**Comment by jcrossley3** [comment]
changelog updated. i think i got the rebase right. lemme know if you need anything else.

File: internal/pkg/scaffold/cmd.go (hunk 1 above)
Comment (hasbro17) [reply internal/pkg/scaffold/cmd.go]: I'm probably missing something but do we only incur the miss when the client/cache is used to CRUD an instance/CR of a newly created CRD whose mapping is not present in the DynamicRestMapper?

If so then I assume most likely this call(e.g GET) would be made inside the reconcile loop. If the DynamicRestMapper reloads and misses(because the CRD is not yet created), and we get an error from `client.Get()`, then we can just rely on backoff of the controller's workqueue right?
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L210-L215

If this call is not in the reconcile loop, then I imagine most likely the operator exits and restarts in the absence of a retry.

**Comment by jmazzitelli** [comment]
This PR didn't fix my problem in #1330, which I was thinking it should have fixed it:

Make sure I'm running 0.8.0:

```
{"level":"info","ts":1558465126.8952413,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1558465126.8952928,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1558465126.895298,"logger":"cmd","msg":"Version of operator-sdk: v0.8.0"}
{"level":"info","ts":1558465126.895325,"logger":"cmd","msg":"Watching namespace.","Namespace":"kiali-operator"}
```

But I still see the error:

```
{"level":"error","ts":1558465170.3098834,"logger":"proxy","msg":"Could not get rest mapping for: monitoring.kiali.io/v1alpha1, Kind=MonitoringDashboard","error":"no matches for kind \"MonitoringDashboard\" in version \"monitoring.kiali.io/v1alpha1\"","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.shouldAddOwnerRef\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:151\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*injectOwnerReferenceHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:89\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:127\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878"}
{"level":"error","ts":1558465170.309941,"logger":"proxy","msg":"Could not determine if we should add owner ref","error":"no matches for kind \"MonitoringDashboard\" in version \"monitoring.kiali.io/v1alpha1\"","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*injectOwnerReferenceHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:92\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:127\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878"}
```
