### PR TITLE
internal/generate: align CRD generator with controller-gen

### LINKED ISSUE #2042: CRD generation via `generate openapi` does not surface errors for invalid tags
## Bug Report

**What did you do?**
Run `operator-sdk generate openapi` for the following `pkg/apis/..._types.go` file that has the invalid marker comment `// +kubebuilder:resource:foo=bar`.

```Go
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Memcached is the Schema for the memcacheds API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=memcacheds,scope=Namespaced
// +kubebuilder:resource:shortName=mc
// +kubebuilder:resource:foo=bar
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MemcachedSpec   `json:"spec,omitempty"`
	Status MemcachedStatus `json:"status,omitempty"`
}

````

**What did you expect to see?**
An error message on which marker is invalid.

**What did you see instead? Under which circumstances?**
No error from the actual controller-gen CRD generator is being surfaced.
```console
$ operator-sdk generate openapi --verbose
DEBU[0000] Debug logging is set
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [cache:[v1alpha1], ]
Error: error generating CRD for Group cache Version v1alpha1 Kind Memcached
Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

**Environment**
* operator-sdk version: "v0.10.0-84-g8132d358", commit: "8132d3588c988b12907e541e5069e9ff7a9fcc55", go version: "go1.12.7 darwin/amd64"

* go version: 1.12.7

**Additional context**
The wrapped error message `Error: error generating CRD ...` suggests that this might just be a lack of context being surfaced from the CRD generator.
https://github.com/operator-framework/operator-sdk/blob/8132d3588c988b12907e541e5069e9ff7a9fcc55/internal/pkg/scaffold/crd.go#L167-L170

https://github.com/kubernetes-sigs/controller-tools/blob/83f6193614de0a51c4bd5af02650c577034c6a4c/pkg/crd/gen.go#L54

Going to test this directly with [controller-gen](https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go) to see if the issue is upstream.

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** 
* cmd/operator-sdk: replace CRD scaffold with CRD generator
* internal/scaffold: remove CRD scaffold and tests
* internal/generate/crd: CRD generator
* test/test-framework: update operator with new CRD generator
* internal/util/fileutil: DotPath prepends "./" or ".\" to a path depending on OS
* doc: discuss storage version setting in CRDs
* test/test-framework: use storage version annotation in APIs

**Motivation for the change:** This PR aligns the CRD generator with controller-gen's. By using the same option strings one would pass to [`controller-gen`](https://github.com/kubernetes-sigs/controller-tools/blob/6eef398/cmd/controller-gen/main.go) to configure the CRD generator, we can easily transition this command to a Makefile, as well as more easily debug CRD generation errors.

Note that a resource is no longer required to run the generator for Go projects. It will update each CRD that corresponds to an API. For non-go projects a resource is still required.

Closes #2042

### CODE REVIEW

File: internal/generate/crd/crd.go [hunk 1]
```diff
@@ -0,0 +1,351 @@
...
+	}
+	b, err := k8sutil.GetObjectBytes(crd, yaml.Marshal)
+	if err != nil {
+		return nil, err
+	}
+	fileMap[fileName] = b
+	return fileMap, nil
+}
+
+// newCRDForResource constructs a barebones CRD using data in resource.
```
Comment (estroz) [inline internal/generate/crd/crd.go]: Everything in this file below this line was copied verbatim from the [CRD scaffold](https://github.com/operator-framework/operator-sdk/blob/460022f/internal/scaffold/crd.go#L189).

**Comment by estroz** [comment]
/hold

blocked by #2202

File: internal/generate/crd/crd.go [hunk 2]
```diff
@@ -0,0 +1,348 @@
...
+type crdGenerator struct {
+	// Dir containing relevant input files.
+	inputDir string
+	// Dir in which to generate output files.
+	outputDir string
+	// isOperatorGo is true when the operator is written in Go.
+	isOperatorGo bool
+	// resource contains API information used to configure single-CRD generation.
+	// This is only required when isOperatorGo is false.
+	resource scaffold.Resource
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]:
```suggestion
	resource *scaffold.Resource
```

File: internal/generate/crd/crd.go [hunk 3]
```diff
@@ -0,0 +1,348 @@
...
+		g.outputDir = scaffold.CRDsDir
+	}
+	g.inputDir = fileutil.DotPath(g.inputDir)
+	g.outputDir = fileutil.DotPath(g.outputDir)
+	return g
+}
+
+// NewGo returns a CRD generator configured to generate a
+// CustomResourceDefintion manifest from scratch using data in resource.
+func NewNonGo(inputDir, outputDir string, resource scaffold.Resource) genutil.Generator {
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: WDYT about it is a NewGenerator and the info if is or not a go project be an attribute of the Generator object?

File: internal/generate/crd/crd.go [hunk 4]
```diff
@@ -0,0 +1,348 @@
...
+	if g.outputDir == "" {
+		g.outputDir = scaffold.CRDsDir
+	}
+	g.inputDir = fileutil.DotPath(g.inputDir)
+	g.outputDir = fileutil.DotPath(g.outputDir)
+	return g
+}
+
+func (g crdGenerator) validate() error {
+	if g.inputDir == "" {
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: These validations shows be the Resource ones. Why is required to duplicate the Resources validations here?

File: internal/generate/crd/crd.go [hunk 5]
```diff
@@ -0,0 +1,348 @@
...
+	if err = g.validate(); err != nil {
+		return errors.Wrap(err, "validation error")
+	}
+	var fileMap map[string][]byte
+	if g.isOperatorGo {
+		fileMap, err = g.generateGo()
+	} else {
+		fileMap, err = g.generateNonGo()
+	}
+	if err != nil {
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]:
```suggestion
	generator := newGenerator()
```

Comment (camilamacedo86) [inline internal/generate/crd/crd.go]:
```suggestion
	generator := newGenerator()
```

File: internal/generate/crd/crd.go [hunk 6]
```diff
@@ -0,0 +1,348 @@
...
+func (g crdGenerator) Generate() (err error) {
+	if err = g.validate(); err != nil {
+		return errors.Wrap(err, "validation error")
+	}
+	var fileMap map[string][]byte
+	if g.isOperatorGo {
+		fileMap, err = g.generateGo()
+	} else {
+		fileMap, err = g.generateNonGo()
+	}
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]:
```suggestion
	generator := newGenerator()
```

File: internal/generate/crd/crd.go [hunk 7]
```diff
@@ -0,0 +1,348 @@
...
+	if err != nil {
+		return errors.Wrap(err, "error generating CRD manifests")
+	}
+	if len(fileMap) == 0 {
+		return errors.New("error generating CRD manifests: no generated files found")
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: wdyt about it be inside of genCRD?

File: internal/generate/crd/crd.go [hunk 8]
```diff
@@ -0,0 +1,348 @@
...
+	}
+	if err = os.MkdirAll(g.outputDir, fileutil.DefaultDirFileMode); err != nil {
+		return errors.Wrapf(err, "error mkdir %s", g.outputDir)
+	}
+	for fileName, b := range fileMap {
+		path := filepath.Join(g.outputDir, fileName)
+		if err := ioutil.WriteFile(path, b, fileutil.DefaultFileMode); err != nil {
+			return errors.Wrap(err, "error writing CRD manifests")
+		}
+	}
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: wdyt it be writeCRD()?

File: test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml [hunk 9]
```diff
@@ -19,12 +19,12 @@ spec:
         apiVersion:
           description: 'APIVersion defines the versioned schema of this representation
             of an object. Servers should convert recognized schemas to the latest
-            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
```
Comment (estroz) [inline test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml]: The updated links are invalid because our kubernetes tag for `k8s.io/apimachinery` contains old comments. I may have to add a regexp for these until we bump to v1.16.

File: cmd/operator-sdk/new/cmd.go [hunk 10]
```diff
@@ -341,6 +349,14 @@ func doHelmScaffold() error {
...
 	}
 
+	crdsDir := filepath.Join(projectName, scaffold.CRDsDir)
+	gcfg := genutil.Config{InputDir: crdsDir, OutputDir: crdsDir}
+	crd := gencrd.NewNonGo(gcfg, *resource)
+	if err := crd.Generate(); err != nil {
+		return errors.Wrapf(err, "error generating CRD for %s", resource)
+	}
+	log.Info("Generated CustomResourceDefinition manifests.")
+
```
Comment (camilamacedo86) [inline cmd/operator-sdk/new/cmd.go]: The above code shows  duplicated see: 264 to 271. So, if is duplicated,  wdyt about centralized in a func?

File: internal/generate/crd/crd.go [hunk 11]
```diff
@@ -0,0 +1,342 @@
...
+		if !hasVersion {
+			// Let either the user or below logic determine whether this new
+			// version is stored or not.
+			crd.Spec.Versions = append(crd.Spec.Versions, apiextv1beta1.CustomResourceDefinitionVersion{
+				Name:    g.resource.Version,
+				Storage: false,
+				Served:  true,
+			})
+		}
+	} else if os.IsNotExist(err) {
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: I think would be easier to read/understand as:
if err ;= call() ;err!= nil{
   //todo
}
if err ;= call() ;err!= nil{
   //todo
}
if err ;= call() ;err!= nil{
   //todo
}

then use the else

File: internal/generate/crd/crd.go [hunk 12]
```diff
@@ -0,0 +1,342 @@
...
+	}
+	if crd.Spec.Names.ListKind == "" {
+		crd.Spec.Names.ListKind = r.Kind + "List"
+	}
+	if crd.Spec.Names.Plural == "" {
+		crd.Spec.Names.Plural = r.Resource
+	}
+	if crd.Spec.Names.Singular == "" {
+		crd.Spec.Names.Singular = r.LowerKind
+	}
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: CCould it not be in the newCRD()?

File: internal/generate/crd/crd.go [hunk 13]
```diff
@@ -0,0 +1,342 @@
...
+// checkCRDVersions ensures version(s) generated for a CRD are in valid format.
+// From the Kubernetes CRD docs:
+//
+// The version field is deprecated and optional, but if it is not empty,
+// it must match the first item in the versions field.
+func checkCRDVersions(crd *apiextv1beta1.CustomResourceDefinition) error {
+	singleVer := crd.Spec.Version != ""
+	multiVers := len(crd.Spec.Versions) > 0
+	if singleVer {
+		if !multiVers {
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]: It is strange .. if is single and !muti shows return error?

File: internal/generate/crd/crd.go [hunk 14]
```diff
@@ -0,0 +1,342 @@
...
+	var hasStorageVer bool
+	for _, ver := range crd.Spec.Versions {
+		// There must be exactly one version flagged as a storage version.
+		if ver.Storage {
+			if hasStorageVer {
+				return errors.Errorf("spec.versions cannot have more than one storage version for CRD %s", crd.Spec.Names.Kind)
+			}
+			hasStorageVer = true
+		}
+	}
```
Comment (camilamacedo86) [inline internal/generate/crd/crd.go]:
```suggestion
    if ver.Storage && hasStorageVer {
	return errors.Errorf("spec.versions cannot have more than one storage version for CRD %s", crd.Spec.Names.Kind)
    }
    hasStorageVer = true
}
```

Comment (camilamacedo86) [reply internal/generate/crd/crd.go]: Maybe ^. But is hard to understand this func logic.

File: internal/generate/crd/crd.go (hunk 2 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: I'd rather not persist heap-allocated objects when we don't have to.

File: internal/generate/crd/crd.go (hunk 3 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: For a Go project, generating a CRD for a resource and generating all CRD's follows the same process, except the former extracts a CRD for only one GVK. For a non-Go project, CRD generation follows a different process and always requires a Resource. While I agree naming could be better and configuration improved, I don't think your suggestion is the correct approach.

File: internal/generate/crd/crd.go (hunk 4 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: How do you mean? We need to make sure Resource is populated is all.

File: internal/generate/crd/crd.go (hunk 8 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: IMO there's not enough code in `Generate()` to warrant refactoring the writing bit into its own function.

File: internal/generate/crd/crd.go (hunk 11 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: You mean like
```go
_, err := os.Stat(path)
if err != nil && !os.IsNotExist(err) {
	...
}
if err != nil && os.IsNotExist(err) {
	...
}
// else
...
```

File: internal/generate/crd/crd.go (hunk 4 above)
Comment (camilamacedo86) [reply internal/generate/crd/crd.go]: So, could you not to do resource.Validate() instead of ?

File: internal/generate/crd/crd.go (hunk 13 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: Not necessarily because `spec.version` is still usable but deprecated. This code will be replaced with validation library code soon anyway.

File: internal/generate/crd/crd.go (hunk 14 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: I'm trying not to change much of this logic since this is copied from existing, working code. Also if `ver.Storage` was false in your suggestion `hasStorageVer` would be set to true.

**Comment by estroz** [comment]
/hold

blocked by #2249

File: cmd/operator-sdk/add/api.go [hunk 15]
```diff
@@ -125,25 +127,32 @@ func apiRun(cmd *cobra.Command, args []string) error {
...
 	}
 
+	gcfg := genutil.Config{InputDir: scaffold.ApisDir, OutputDir: scaffold.CRDsDir}
+	crd := gencrd.NewCRDGo(gcfg)
+	if err := crd.Generate(); err != nil {
+		return errors.Wrapf(err, "error generating CRDs from APIs in %s", scaffold.ApisDir)
+	}
+
+	log.Info("Generated CustomResourceDefinition manifests.")
+
```
Comment (joelanford) [inline cmd/operator-sdk/add/api.go]: Do we need this code since we're running it in `k8sgenutil.OpenAPIGen()`?

File: internal/generate/crd/crd.go [hunk 16]
```diff
@@ -0,0 +1,332 @@
...
+// generateNonGo generates CRDs for Go projects using Go API files.
+func (g crdGenerator) generateGo() (map[string][]byte, error) {
+	fileMap := map[string][]byte{}
+	// Generate files in the generator's cache so we can modify the file name
+	// and annotations.
+	defName := "output:crd:cache"
+	cacheOutputDir := string(filepath.Separator) + filepath.Clean(g.OutputDir)
+	rawOpts := []string{
+		"crd",
+		fmt.Sprintf("paths=%s/...", fileutil.DotPath(g.InputDir)),
```
Comment (joelanford) [inline internal/generate/crd/crd.go]: Do we need to use `filepath.Separator` in `%s/...` instead of the forward slash? Or does Go always expect the forward slash for this style of path expression?

File: internal/generate/crd/crd.go [hunk 17]
```diff
@@ -0,0 +1,332 @@
...
+		fmt.Sprintf("%s:dir=%s", defName, cacheOutputDir),
+	}
+	cachedGen := genutil.NewCachedGenerator()
+	cachedGen.AddOutputRule(defName, genutil.OutputToCachedDirectory{})
+	if err := cachedGen.Run(rawOpts); err != nil {
+		return nil, err
+	}
+	cache := genutil.GetCache()
+	infos, err := afero.ReadDir(cache, cacheOutputDir)
```
Comment (joelanford) [inline internal/generate/crd/crd.go]: Is it possible that `controller-gen` will create a hierarchy directory structure in the future? If so, should we do the afero equivalent of `filepath.Walk()`?

File: internal/generate/crd/crd.go [hunk 18]
```diff
@@ -0,0 +1,332 @@
...
+		modifiedCRD := []byte{}
+		for scanner.Scan() {
+			sb := scanner.Bytes()
+			typeMeta, err := k8sutil.GetTypeMetaFromBytes(sb)
+			if err != nil {
+				return nil, err
+			}
+			if typeMeta.Kind != "CustomResourceDefinition" {
+				continue
+			}
```
Comment (joelanford) [inline internal/generate/crd/crd.go]: Does `controller-gen crd` generate other kinds? Or do we check the kind so we can unmarshal into the CRD type and remove the annotation?

Wondering if it's safer for future-proofing if we don't assume the kind and generically remove the annotation using `unstructured.Unstructured`?

File: internal/generate/crd/crd.go (hunk 1 above)
Comment (joelanford) [reply internal/generate/crd/crd.go]: This function needs to be updated based on #2275

File: internal/generate/crd/crd_test.go [hunk 19]
```diff
@@ -12,58 +12,77 @@
...
+		t.Fatalf("Failed to execute CRD generator: %v", err)
+	}
+	if b, ok := fileMap[getFileNameForResource(*r)]; !ok {
+		t.Errorf("Failed to generate CRD for %s", r)
+	} else {
+		assert.Equal(t, crdExp, string(b))
+	}
+}
+
+func TestCRDNonGo(t *testing.T) {
```
Comment (joelanford) [inline internal/generate/crd/crd_test.go]: Need to add similar test for the default non-go CRD that was added in #2275

File: internal/generate/crd/crd.go (hunk 16 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: `/` is always used for package paths.

File: internal/generate/crd/crd.go (hunk 17 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: I don't think so since we control the custom output rule `OutputToCachedDirectory`, to which you must explicitly provide the dir to output files.

File: internal/generate/crd/crd.go (hunk 18 above)
Comment (estroz) [reply internal/generate/crd/crd.go]: The latter. I agree using `unstructured.Unstructured` is a better general solution.

File: cmd/operator-sdk/add/api.go (hunk 15 above)
Comment (estroz) [reply cmd/operator-sdk/add/api.go]: We do not, especially with #2276.

File: internal/generate/crd/crd.go (hunk 17 above)
Comment (joelanford) [reply internal/generate/crd/crd.go]: Right, but say `cacheOutputDir` is `/tmp/myOutputDir`. Is it guaranteed that files will always be  written in _that_ directory, or is it possible that at some point in the future, controller-gen could create files in subdirectories (e.g. `/tmp/myOutputDir/<group>/<resource>.yaml`)

It's probably not anything we really need to worry about now since a change like that would be caught in our unit test. But something I thought about nonetheless.

Comment (estroz) [reply internal/generate/crd/crd.go]: It is guaranteed unless we change our code. Any change in path would come from modifying an [`OutputRule`](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/genall/output.go#L77-L78) and the only `OutputRule` our generator is configured with is one we've written, which creates a file at the top level of the supplied dir.

File: doc/user-guide.md [hunk 20]
```diff
@@ -107,7 +107,23 @@ After modifying the `*_types.go` file always run the following command to update
...
+
+```console
+$ operator-sdk generate openapi
+```
+
+**Notes:**
+- - Your CRD *must* specify exactly one [storage version][crd-storage-version]. Use the `+kubebuilder:storageversion` [marker][crd-markers] to indicate the GVK that should be used to store data by the API server. This marker should be in a comment above your `Memcached` type.
+- You may see errors like "API rule violation" when running the above command. For information on these errors, read the below section and see the [API rules][api-rules] documentation.
+
+[crd-storage-version]:https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#writing-reading-and-updating-versioned-customresourcedefinition-objects
```
Comment (camilamacedo86) [inline doc/user-guide.md]: Should not the links be in the bottom of the file?

File: cmd/operator-sdk/add/crd.go [hunk 21]
```diff
@@ -98,6 +96,14 @@ func crdFunc(cmd *cobra.Command, args []string) error {
 		return fmt.Errorf("crd scaffold failed: (%v)", err)
 	}
 
+	// This command does not consider an APIs dir. Instead it adds a plain CRD
+	// for the provided resource. We can use NewCRDNonGo to get this behavior.
+	gcfg := genutil.Config{InputDir: scaffold.ApisDir, OutputDir: scaffold.CRDsDir}
```
Comment (joelanford) [inline cmd/operator-sdk/add/crd.go]: For non-go, should `InputDir` be `scaffold.CRDsDir`? Also, since `NewCRDNonGo()` defaults the config's input and output dirs, can we pass an empty `genutil.Config{}`?

Ditto for other places that we're passing the config that use the defaults.

File: cmd/operator-sdk/internal/genutil/crds.go [hunk 22]
```diff
@@ -31,49 +28,12 @@ import (
...
-		err = s.Execute(cfg,
-			&scaffold.CRD{Resource: r, IsOperatorGo: projutil.IsOperatorGo()},
-		)
-		if err != nil {
-			return err
-		}
+	cfg := genutil.Config{InputDir: scaffold.ApisDir, OutputDir: scaffold.CRDsDir}
+	crd := gencrd.NewCRDGo(cfg)
+	if err := crd.Generate(); err != nil {
+		return errors.Wrapf(err, "error generating CRDs from APIs in %s", scaffold.ApisDir)
```
Comment (joelanford) [inline cmd/operator-sdk/internal/genutil/crds.go]: Can we start switching over to Go 1.13 errors?
```suggestion
		return fmt.Errorf("error generating CRDs from APIs in %s: %w", scaffold.ApisDir, err)
```

File: doc/user-guide.md (hunk 20 above)
Comment (joelanford) [reply doc/user-guide.md]: I actually kind of like these links being at the end of each section since it puts the link closer to its reference. We should only do this when the link is used only in that section though.

File: test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go [hunk 23]
```diff
@@ -77,13 +77,13 @@ type Hog struct {
 	// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
 	Inlined InlinedComponent `json:",inline"`
 	// Fields should be inlined
-	InlinedComponent
+	InlinedComponent `json:",inline"`
```
Comment (joelanford) [inline test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go]: Are the `json` tag changes in this file related to this PR?

File: cmd/operator-sdk/internal/genutil/crds.go (hunk 22 above)
Comment (estroz) [reply cmd/operator-sdk/internal/genutil/crds.go]: `errors.Wrap` returns an error implementing Go 1.13’s `Unwrap` function. However I am fine with using `fmt.Errorf` everywhere for consistency.

File: test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go (hunk 23 above)
Comment (estroz) [reply test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go]: Yes, the CRD generator seems to complain if no JSON tags are present on a field.

File: cmd/operator-sdk/internal/genutil/crds.go (hunk 22 above)
Comment (joelanford) [reply cmd/operator-sdk/internal/genutil/crds.go]: Oh that's cool, didn't know that. Regardless, if we can move to `fmt.Errorf` that's one less dependency to pull in. We can standardize in a follow-on.

File: cmd/operator-sdk/add/crd.go (hunk 21 above)
Comment (estroz) [reply cmd/operator-sdk/add/crd.go]: Yes we can pass an empty config here, changing.

File: doc/user-guide.md [hunk 24]
```diff
@@ -107,7 +107,22 @@ After modifying the `*_types.go` file always run the following command to update
...
+### Updating CRD manifests
+
+Now that `MemcachedSpec` and `MemcachedStatus` have fields and possibly annotations, the CRD corresponding to the API's group and kind must be updated. To do so, run the following command:
+
+```console
+$ operator-sdk generate crds
+```
+
+**Notes:**
+- - Your CRD *must* specify exactly one [storage version][crd-storage-version]. Use the `+kubebuilder:storageversion` [marker][crd-markers] to indicate the GVK that should be used to store data by the API server. This marker should be in a comment above your `Memcached` type.
```
Comment (joelanford) [inline doc/user-guide.md]: I noticed that without manually adding `+kubebuilder:storageversion` in advance, `operator-sdk add api` errors out when another version is added to an existing CRD with the same group & kind.

This problem may be out-of-scope for this PR, but something we may want to think about whether there's a more graceful way to handle from a user experience perspective.

Here's the error I get:
```
$ operator-sdk generate crds
INFO[0000] Running CRD generator.
example.com/go-operator/pkg/apis/example/v1:-: CRD for GoOperator.example.com has no storage version
Error: error generating CRDs from APIs in pkg/apis: error generating CRD manifests: error running CRD generator: not all generators ran successfully
Usage:
  operator-sdk generate crds [flags]

Flags:
  -h, --help   help for crds

Global Flags:
      --verbose   Enable verbose logging
```

It's a good hint, but could be improved by telling the user how to fix the problem. Can we put this note into the error message, nearly verbatim and skip outputting the usage?

Comment (joelanford) [reply doc/user-guide.md]: Also, I just noticed that it's possible to define `+kubebuilder:storageversion` in both versions of a CRD's types.go files and controller-gen happily creates a CRD where `storage: true` exists in both versions. That should also be an error right?

**Comment by joelanford** [comment]
Oh also, is the code coverage decrease related to this PR? If so, is it possible to bump that back up?

File: doc/user-guide.md (hunk 24 above)
Comment (estroz) [reply doc/user-guide.md]: :+1: on not printing usage. By note do you mean:
```
example.com/go-operator/pkg/apis/example/v1:-: CRD for GoOperator.example.com has no storage version
```

Two CRD versions with `storage: true` is an error, but controller-tools does not consider this an error during generation. I will submit an issue if one does not exist already upstream.

Comment (joelanford) [reply doc/user-guide.md]: Oh I meant based on the note that you have in the user guide:

Something like:
> Your CRD must specify exactly one storage version. Use the `+kubebuilder:storageversion` marker to indicate the GVK that should be used to store data by the API server. This marker should be in a comment above your CRDs root storage type in `_types.go`.
>
> See https://book.kubebuilder.io/multiversion-tutorial/api-changes.html#storage-versions

Comment (estroz) [reply doc/user-guide.md]: Generator errors are not returned by [`Runtime.Run()`](https://github.com/kubernetes-sigs/controller-tools/blob/b62a514/pkg/genall/genall.go#L172) so we can't check if the error returned pertains to no `+kubebuilder:storageversion` annotation. How about linking https://book.kubebuilder.io/reference/generating-crd.html in an error message for `Runtime.Run()` errors? This should cover this and other errors, but isn't as specific.
