### PR TITLE
up local command: add flag operator-flags

### LINKED ISSUE #255: operator-sdk up local does not allow pass through command flags
As an operator author I would like the ability to use flags/command line args to my operator and use the `operator-sdk up local` command

Results: 
```
operator-sdk up local --kubeconfig ~/.kube/config --namespace test

Error: unknown flag: --namespace
Usage:
  operator-sdk up local [flags]

Flags:
  -h, --help                help for local
      --kubeconfig string   The file path to kubernetes configuration file; defaults to $HOME/.kube/config

unknown flag: --namespace
```

Expected Results: 

some method to pass arguments through

### PR DESCRIPTION
**Pull request by shawn-hurley**
operator-flags gives the ability to pass flags to the local operator.

Fixes #255

### CODE REVIEW

File: commands/operator-sdk/cmd/up/local.go [hunk 1]
```diff
@@ -18,20 +19,22 @@ func NewLocalCmd() *cobra.Command {
...
-by building the operator binary with the ability to access a 
+		Long: `The operator-sdk up local command launches the operator on the local machine
+by building the operator binary with the ability to access a
 kubernetes cluster using a kubeconfig file.
 `,
 		Run: upLocalFunc,
 	}
 
 	upLocalCmd.Flags().StringVar(&kubeConfig, "kubeconfig", "", "The file path to kubernetes configuration file; defaults to $HOME/.kube/config")
+	upLocalCmd.Flags().StringVar(&passThroughFlags, "extra-flags", "", "The extra flags that your operator will need. Example: \"--namespace test\"")
```
Comment (fanminshi) [inline commands/operator-sdk/cmd/up/local.go]: I think we might want to make `"extra-flags"` more explicit such as `"operator-flags"`

I think change the description to:
`"The flags that the operator needs. Example: \"--flag1=value1 --flag2=value2 ...\""`
sounds a bit more formal to avoid `your` and `will`.

File: commands/operator-sdk/cmd/up/local.go [hunk 2]
```diff
@@ -18,20 +19,22 @@ func NewLocalCmd() *cobra.Command {
...
 
 	return upLocalCmd
 }
 
 var (
-	kubeConfig string
+	kubeConfig       string
+	passThroughFlags string
```
Comment (fanminshi) [inline commands/operator-sdk/cmd/up/local.go]: suggest to use `operatorFlags` instead of `passThroughFlags`.

**Comment by fanminshi** [comment]
lgtm

**Comment by fanminshi** [comment]
One last nit, could you update the commit title to use operator-flags instead of extra-flags?
