### PR TITLE
fix(Helm.controller.watch): Process watch for List kind

### LINKED ISSUE #4636: Helm Operator doesn't work with Kube Prometheus Stack with additionalPrometheusRulesMap yaml list
## Bug Report

Hi!
Helm Operator doesn't seem to work with Kube Prometheus Stack when there is a list used inside the `additionalPrometheusRulesMap` configuration.
The same config works just fine when used with `helm v3.2.4` without the operator.

Without the `additionalPrometheusRulesMap` key the helm operator works as expected.

#### What did you do?

1. Created the Helm Operator for the Kube Prometheus Stack
```bash
$ operator-sdk_linux_amd64 init --plugins helm --helm-chart prometheus-community/kube-prometheus-stack --domain example.com --group helm-chart --version v1 --kind Promhelm
```

2. Prepared the following CR
```
apiVersion: helm-chart.example.com/v1
kind: Promhelm
metadata:
  name: promhelm-sample
spec:
  additionalPrometheusRulesMap:
    some-rules:
      groups:
        - name: foo
          rules:
            - expr: bar
              record: baz
  alertmanager:
    enabled: false
  grafana:
    enabled: false
    defaultDashboardsEnabled: false
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tls:
      enabled: false
```

3. Deployed the CR
```
kubectl apply -f /prometheus-helm-operator/config/samples/promhelm.yaml -n promhelm --validate=false
```

#### What did you expect to see?

I should see the Helm chart deployed.
I should see applied k8s objects in the operator logs.
I should be able to edit / delete the CR.

#### What did you see instead? Under which circumstances?

The Helm chart has been deployed and Prometheus seems to be working fine. I can uninstall it without the operator using the external helm command.

In the operator logs I don't see the applied k8s objects.

Also in the operator logs I can see the following error line:
```
E0311 12:05:49.494839       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch /v1, Kind=List: failed to list /v1, Kind=List: the server could not find the requested resource
```

I cannot change nor delete the previously applied CR.

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

microk8s

`$ operator-sdk version`

```
operator-sdk version: "v1.3.2", commit: "5dd883dc90085da6a6e75bb05443b4d491a39143", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

`$ helm search repo prometheus-community/kube-prometheus-stack`
```
NAME                                      	CHART VERSION	APP VERSION	DESCRIPTION
prometheus-community/kube-prometheus-stack	14.0.1       	0.46.0     	kube-prometheus-stack collects Kubernetes manif...
```

### PR DESCRIPTION
**Pull request by hickeyma**
**Description of the change:**

The Kubernetes `kind: List` is not actually a resource and therefore cannot have a watch set on it. This PR iterates on the `List` items instead and sets the watch on those Kubernetes kinds. 

**Motivation for the change:**

Helm operator controller errors out when a Helm chart has a `kind: List` declared.

Closes #4636 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: internal/helm/controller/controller.go [hunk 1]
```diff
@@ -25,7 +25,9 @@ import (
 	"helm.sh/helm/v3/pkg/releaseutil"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/runtime/schema"
+
```
Comment (estroz) [inline internal/helm/controller/controller.go:30]: Nit: import order
```suggestion
```

File: internal/helm/controller/controller.go [hunk 2]
```diff
@@ -113,37 +115,65 @@ func watchDependentResources(mgr manager.Manager, r *HelmOperatorReconciler, c c
...
+				m.Unlock()
+				log.Info("Watching dependent resource", "ownerApiVersion", r.GVK.GroupVersion(),
+					"ownerKind", r.GVK.Kind, "apiVersion", gvkDependent.GroupVersion(), "kind", gvkDependent.Kind)
+				return nil
+			}
+
+			// List is not actually a resource and therefore cannot have a
+			// watch on it. The watch will be on the kinds listed in the list
+			// and will therefore need to be handled individually.
+			if gvk.Kind == "List" {
```
Comment (estroz) [inline internal/helm/controller/controller.go:163]: Someone can define their own `List` type (however unlikely) but the group will not be empty.
```suggestion
			if gvk == schema.GroupVersionKind{Version: "v1", Kind: "List"} {
```

File: internal/helm/controller/controller.go [hunk 3]
```diff
@@ -113,37 +115,65 @@ func watchDependentResources(mgr manager.Manager, r *HelmOperatorReconciler, c c
...
+				u.EachListItem(func(obj runtime.Object) error {
+					err := setWatchOnResource(obj)
+					if err != nil {
+						return err
+					}
+					return nil
```
Comment (estroz) [inline internal/helm/controller/controller.go:169]: Style nit
```suggestion
					return setWatchOnResource(obj)
```

**Review by estroz — CHANGES_REQUESTED** [review]
Just some nits and a suggested fix. Otherwise LGTM. Thanks @hickeyma!

File: internal/helm/controller/controller.go [hunk 4]
```diff
@@ -113,37 +115,65 @@ func watchDependentResources(mgr manager.Manager, r *HelmOperatorReconciler, c c
...
+				log.Info("Watching dependent resource", "ownerApiVersion", r.GVK.GroupVersion(),
+					"ownerKind", r.GVK.Kind, "apiVersion", gvkDependent.GroupVersion(), "kind", gvkDependent.Kind)
+				return nil
+			}
+
+			// List is not actually a resource and therefore cannot have a
+			// watch on it. The watch will be on the kinds listed in the list
+			// and will therefore need to be handled individually.
+			if gvk.Kind == "List" {
+				u.EachListItem(func(obj runtime.Object) error {
```
Comment (estroz) [inline internal/helm/controller/controller.go:164]: Also this error should be checked
```suggestion
				err := u.EachListItem(func(obj runtime.Object) error {
```

**Comment by estroz** [comment]
Additionally can you add a [changelog](https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml) entry for this bugfix?

/kind bug

File: internal/helm/controller/controller.go (hunk 1 above)
Comment (hickeyma) [reply internal/helm/controller/controller.go]: Done

File: internal/helm/controller/controller.go (hunk 2 above)
Comment (hickeyma) [reply internal/helm/controller/controller.go]: Done

File: internal/helm/controller/controller.go (hunk 3 above)
Comment (hickeyma) [reply internal/helm/controller/controller.go]: Done

File: internal/helm/controller/controller.go (hunk 4 above)
Comment (hickeyma) [reply internal/helm/controller/controller.go]: Done

**Comment by hickeyma** [comment]
Thanks fo the review @estroz. I have updated with your feedback and it is ready to review again.

BTW, does this need a changelog?

**Comment by estroz** [comment]
>BTW, does this need a changelog?

Yep!

**Comment by hickeyma** [comment]
@estroz Changelog added.

**Review by estroz — APPROVED** [review]
Thanks again @hickeyma 

/lgtm

**Comment by hickeyma** [comment]
Thanks for reviews and merge @estroz
