### PR TITLE
Fix Allow IfNotPresent policy when `operator-sdk run bundle` #6795

### LINKED ISSUE #6795: Allow IfNotPresent policy when `operator-sdk run bundle`
#### Describe the problem you need a feature to resolve.
We may use ttl.sh as registry to push bundle to from time to time and want ability to restart pod in the future when image no longer exists in registry. If policy is Always, pod will fail to restart.

### PR DESCRIPTION
**Pull request by kaovilai**
**Description of the change:**
```diff
❯ go run cmd/operator-sdk/main.go run bundle 
Error: accepts 1 arg(s), received 0
Usage:
  operator-sdk run bundle <bundle-image> [flags]

Flags:
      --ca-secret-name string                     Name of a generic secret containing a PEM root certificate file required to pull bundle images. This secret *must* be in the namespace that this command is configured to run in, and the file *must* be encoded under the key "cert.pem"
      --decompression-image string                image used in an init container in the registry pod to decompress the compressed catalog contents. cat and gzip binaries are expected to exist in the PATH (default "registry.access.redhat.com/ubi8:8.9")
  -h, --help                                      help for bundle
+     --image-pull-policy string                  image pull policy for the registry pod (default "Always")
      --index-image string                        index image in which to inject bundle (default "quay.io/operator-framework/opm:latest")
      --install-mode InstallModeValue             install mode
      --kubeconfig string                         Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string                          If present, namespace scope for this CLI request
      --pull-secret-name string                   Name of image pull secret ("type: kubernetes.io/dockerconfigjson") required to pull bundle images. This secret *must* be both in the namespace and an imagePullSecret of the service account that this command is configured to run in
      --security-context-config SecurityContext   specifies the security context to use for the catalog pod. allowed: 'restricted', 'legacy'. (default legacy)
      --service-account string                    Service account name to bind registry objects to. If unset, the default service account is used. This value does not override the operator's service account
      --skip-tls                                  skip authentication of image registry TLS certificate when pulling a bundle image in-cluster
      --skip-tls-verify                           skip TLS certificate verification for container image registries while pulling bundles
      --timeout duration                          Duration to wait for the command to complete before failing (default 2m0s)
      --use-http                                  use plain HTTP for container image registries while pulling bundles

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0000] accepts 1 arg(s), received 0                 
exit status 1
```

**Motivation for the change:**
When pushing bundle to temp registry like ttl.sh, images ought to become unavailable eventually. We want pod restarts if any to not result in pull errors. The images will be tagged with a short sha hash so it should be "globally unique" to the user working on a branch.

Fixes #6795 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: internal/olm/operator/registry/index_image.go [hunk 1]
```diff
@@ -138,6 +139,13 @@ func (c *IndexImageCatalogCreator) BindFlags(fs *pflag.FlagSet) {
 		"while pulling bundles")
 	fs.BoolVar(&c.UseHTTP, "use-http", false, "use plain HTTP for container image registries "+
 		"while pulling bundles")
+	fs.StringVar(&c.ImagePullPolicy, "image-pull-policy", string(corev1.PullAlways), "image pull policy for the registry pod")
```
Comment (mateusoliveira43) [inline internal/olm/operator/registry/index_image.go:142]: only this flag would not solve the problem?

Comment (kaovilai) [reply internal/olm/operator/registry/index_image.go:142]: It would but I would rather not type out the string every time or lookup possible values. Just personal preference.

Comment (acornett21) [reply internal/olm/operator/registry/index_image.go:142]: @mateusoliveira43 is correct, IMO this PR is encapsulating the functionally of the flag and not letting a user choose the value(s) they want. I think it's better to just go with one flag to expose a given pods `ImagePullPolicy`.

Comment (kaovilai) [reply internal/olm/operator/registry/index_image.go:142]: Ok will update in a bit

**Review by mateusoliveira43 — APPROVED** [review]

**Review by acornett21 — APPROVED** [review]
