### PR TITLE
internal/olm: refactor package `internal/operator` and `run packagemanifests` logic

### LINKED ISSUE #2938: operator-sdk run --olm reports installation failure after successful installation
## Bug Report

**What did you do?**

```
operator-sdk run --olm \
  --olm-namespace=openshift-operator-lifecycle-manager \
  --manifests=deploy/olm-catalog/my-operator \
  --operator-version=0.9.0 \
  --operator-namespace=my-operator-ns
```

**What did you expect to see?**

Successful installation.

**What did you see instead? Under which circumstances?**

The log output from `operator-sdk run --olm` shows a fatal error stating the operator did not install successully, the the log(s) right before this error show `phase: Succeeded`:

```
INFO[0000] Waiting for ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" to reach 'Succeeded' phase
INFO[0000]   Waiting for ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" to appear
INFO[0003]   Found ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" phase: Pending
INFO[0004]   Found ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" phase: InstallReady
INFO[0005]   Found ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" phase: Installing
INFO[0022]   Found ClusterServiceVersion "my-operator-ns/my-operator.v0.9.0" phase: Succeeded
FATA[0022] Failed to run operator using OLM: operator my-operator did not install successfully
```

In addition to this, I can verify in the OCP dashboard as well as via `oc` that my operator deployment is created and `Ready` in the cluster:

```
$ oc get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
my-operator          1/1     1            1           102s
```

Looking through my operator pod logs, everything looks fine. I see no errors. This seems to be an `operator-sdk` error being thrown, as even in the OCP dashboard I cannot find any source of error for the operator installation.

**Environment**
* operator-sdk version:

```
$ operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* go version:

```
$ go version
go version go1.13.8 linux/amd64
```

* Kubernetes version information:

```
$ oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```

* Kubernetes cluster kind: OCP 4.3

* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
* internal/olm: refactor package `internal/operator` into a coherent set of types under `internal/olm/operator`, and move the OLM installer into its own package

**Motivation for the change:** both `run bundle` and `run packagemanifests` share a lot of code, so should live under the same package such that types/functions can be shared as much as possible.

Closes #2938 

/cc @rashmigottipati @jmrodri  

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: internal/olm/operator/registry/configmap.go [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+	cfg *operator.Configuration
+}
+
+func NewConfigMapCatalogCreator(cfg *operator.Configuration) *ConfigMapCatalogCreator {
+	return &ConfigMapCatalogCreator{
+		cfg: cfg,
+	}
+}
+
+func (c ConfigMapCatalogCreator) CreateCatalog(ctx context.Context, name string) (*v1alpha1.CatalogSource, error) {
```
Comment (estroz) [inline internal/olm/operator/registry/configmap.go:46]: This was refactored from `internal/olm/operator/packagemanifests_manager.go`.

File: internal/olm/operator/registry/operator_installer.go [hunk 2]
```diff
@@ -0,0 +1,228 @@
...
+		return fmt.Errorf("catalog source connection is not ready: %v", err)
+	}
+
+	return nil
+}
+
+// createOperatorGroup creates an OperatorGroup using package name if an OperatorGroup does not exist.
+// If one exists in the desired namespace and it's target namespaces do not match the desired set,
+// createOperatorGroup will return an error.
+func (o OperatorInstaller) createOperatorGroup(ctx context.Context) error {
```
Comment (estroz) [inline internal/olm/operator/registry/operator_installer.go:132]: This was moved here from `internal/olm/operator/tenancy.go`.
