### PR TITLE
test/e2e/memcached_test.go: poll for leader lock configmap

### LINKED ISSUE #1152: Leader election e2e test flake
## Bug Report

**What did you do?**
Ran the e2e tests against the `master` branch

**What did you expect to see?**
All tests pass

**What did you see instead? Under which circumstances?**
The `TestMemcached/memcached-group/Cluster` test failed, seemingly related to leader election: https://travis-ci.org/operator-framework/operator-sdk/jobs/499875835#L904

**Environment**
* operator-sdk version: 82aff45a9c9011b147cfe260dcdb208a364ee6d1

* Kubernetes version information:

Openshift v3.11.0-0cbc58b (from CI setup)

* Kubernetes cluster kind: 

N/A

**Possible Solution**
Research and fix flake or revert [leader election test fixes](https://github.com/operator-framework/operator-sdk/commit/f6d83791dd8880f0e33d549343642aabadc9d3a0).

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Add wait polling for getting leader lock configmap in e2e test.

**Motivation for the change:**
The e2e test sometimes flakes trying to fetch the leader lock config map before it is present.

Closes #1152

### CODE REVIEW

File: test/e2e/memcached_test.go [hunk 1]
```diff
@@ -316,11 +317,23 @@ func memcachedLeaderTest(t *testing.T, f *framework.Framework, ctx *framework.Te
 
 func verifyLeader(t *testing.T, namespace string, f *framework.Framework) (*v1.Pod, error) {
 	// get configmap, which is the lock
+	lockName := "memcached-operator-lock"
 	lock := v1.ConfigMap{}
-	err := f.Client.Get(context.TODO(), types.NamespacedName{Name: "memcached-operator-lock", Namespace: namespace}, &lock)
+	err := wait.Poll(time.Second*5, time.Second*60, func() (done bool, err error) {
```
Comment (LiliC) [inline test/e2e/memcached_test.go]: The wait times are they based on anything or just approximate times?

Comment (joelanford) [reply test/e2e/memcached_test.go]: They're arbitrary. Seems like a reasonable balance between spamming the API server and delaying our test too much if the leader lock isn't present on the first try.

Comment (estroz) [inline test/e2e/memcached_test.go]:
```suggestion
	err := wait.Poll(retryInterval, timeout, func() (done bool, err error) {
```
