### PR TITLE
k8sutil: ExposeMetricsPort works for ClusterScoped

### LINKED ISSUE #835: ExposeMetricsPort does not work with operator generated with --cluster-scoped
## Bug Report

**What did you do?**
I generated an operator with --cluster-scoped
Then in my code I called the function
```
metrics.ExposeMetricsPort()
```
This does not work. Service creation fails:
```
{"level":"error","ts":1544610953.1499157,"logger":"metrics","caller":"metrics/metrics.go:54","msg":"failed to create service for operator metrics","error":"an empty namespace may not be set during creation","stacktrace":"github.com/amadeusitgroup/---/go-logr/zapr.(*zapLogger).Error\n\t/home/dbenque/---/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/amadeusitgroup/---/vendor/github.com/operator-framework/operator-sdk/pkg/metrics.ExposeMetricsPort\n\t/home/dbenque/---/vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go:54\nmain.main\n\t/home/dbenque/---/cmd/manager/main.go:74\nruntime.main\n\t/home/dbenque/code/goroot/src/runtime/proc.go:201"}
```

**What did you expect to see?**
Service creation to expose metrics inside the namespace where the operator is running.

**What did you see instead? Under which circumstances?**
Error in logs (See above) + No service creation

**Environment**
* operator-sdk version:
operator-sdk version v0.1.1+git
```
[[projects]]
  branch = "master"
  digest = "1:dddee56f7208e9df866e44e8a14749e1048395af27d72b498a35f543ac8b3465"
  name = "github.com/operator-framework/operator-sdk"
  packages = [
    "pkg/k8sutil",
    "pkg/metrics",
    "version",
  ]
  pruneopts = "NT"
  revision = "9ae4ed9972e0296799a60ab9341c6a9138a77509"
```
* Kubernetes version information:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Minikube

* Are you writing your operator in ansible or go?
Go

**Possible Solution**
In case of cluster scope operator, the service should be created inside the namespace of the operator and not inside the WATCHNAMESPACE that is empty in that case.
I will try to propose a PR for that.

**Additional context**
None

### PR DESCRIPTION
**Pull request by dbenque-1a**
**Description of the change:**
When creating the Service to expose metrics, use the NAMESPACE env variable instead of the WATCH_NAMESPACE that is empty for an operator generated with --cluster-scoped

**Motivation for the change:**
ExposeMetricsPort was failing to generate the kubernetes service to scrape metrics if the operator was generated with --cluster-scoped flag

Closes #835

### CODE REVIEW

File: pkg/k8sutil/k8sutil.go [hunk 1]
```diff
@@ -54,6 +63,9 @@ func InitOperatorService() (*v1.Service, error) {
 	if err != nil {
 		return nil, err
 	}
+	if namespace == "" { // This will happen for clusterScoped operators
+		namespace, _ = GetNamespace()
```
Comment (estroz) [inline pkg/k8sutil/k8sutil.go]: Check this error.

Comment (dbenque-1a) [reply pkg/k8sutil/k8sutil.go]: Done. +some unit tests
Should I squash both commits?

File: pkg/k8sutil/k8sutil.go [hunk 2]
```diff
@@ -32,6 +32,15 @@ func GetWatchNamespace() (string, error) {
 	return ns, nil
 }
 
+// GetNamespace returns the namespace the operator should be running in.
+func GetNamespace() (string, error) {
```
Comment (LiliC) [inline pkg/k8sutil/k8sutil.go]: GetNamespace is a very generic name, could we name it something like `GetClusterNamespace`. Also not sure we need to export this?

File: pkg/k8sutil/constants.go [hunk 3]
```diff
@@ -20,9 +20,15 @@ const (
...
 	// WatchNamespaceEnvVar is the constant for env variable WATCH_NAMESPACE
-	// which is the namespace that the pod is currently running in.
+	// which is the namespace where the watch activity happens and where the pod is currently running in.
+	// this value is empty if the operator is running with clusterScope.
 	WatchNamespaceEnvVar = "WATCH_NAMESPACE"
 
+	// NamespaceEnvVar is the constant for env variable NAMESPACE
+	// which is the namespace that the pod is currently running in.
+	// this value is set only if the operator is running with clusterScope
+	NamespaceEnvVar = "NAMESPACE"
```
Comment (LiliC) [inline pkg/k8sutil/constants.go]: Could this be renamed to `ClusterNamespaceEnvVar` as like you explain it's only set if the operator is running with cluster scope?

Comment (LiliC) [reply pkg/k8sutil/constants.go]: Also maybe `OPERATOR_NAMESPACE` would be a better env var name as `NAMESPACE` seems very generic and might have conflicts.

File: pkg/scaffold/operator_test.go [hunk 4]
```diff
@@ -126,6 +126,10 @@ spec:
             periodSeconds: 10
             failureThreshold: 1
           env:
+            - name: NAMESPACE
```
Comment (LiliC) [inline pkg/scaffold/operator_test.go]: This would need to be done in ansible scaffold as well.

**Comment by LiliC** [comment]
@hasbro17 had a good suggestion in https://github.com/operator-framework/operator-sdk/pull/786#discussion_r238933021 so pinging him on this.

File: pkg/k8sutil/constants.go (hunk 3 above)
Comment (dbenque-1a) [reply pkg/k8sutil/constants.go]: renaming done:
GetNamespace -> getOperatorNamespace
NamespaceEnvVar -> OperatorNamespace

**Comment by joelanford** [comment]
I think https://github.com/operator-framework/operator-sdk/pull/786#discussion_r238933021 makes a lot of sense.

I'd suggest we move [this](https://github.com/operator-framework/operator-sdk/blob/48be90640e69ed2506e16b59602d8c98a6683559/pkg/leader/leader.go#L148-L160) function to `k8sutil.GetOperatorNamespace()`, and then change [this line](https://github.com/operator-framework/operator-sdk/blob/4c3d8ca3ad6036835ce3b573b072d299cc17952c/pkg/k8sutil/k8sutil.go#L53) to use it.

**Comment by dbenque-1a** [comment]
@joelanford i will do that. Thanks.

File: pkg/k8sutil/k8sutil.go [hunk 5]
```diff
@@ -32,6 +34,19 @@ func GetWatchNamespace() (string, error) {
 	return ns, nil
 }
 
+// getOperatorNamespace returns the namespace the operator should be running in.
+func getOperatorNamespace() (string, error) {
```
Comment (joelanford) [inline pkg/k8sutil/k8sutil.go]: We should probably export `getOperatorNamespace`, since it would be generally useful.

Also, would you mind removing `func myNS()` from `pkg/leader/leader.go` and replacing any calls to it with `GetOperatorNamespace()`?

File: pkg/k8sutil/constants.go [hunk 6]
```diff
@@ -20,7 +20,8 @@ const (
 	KubeConfigEnvVar = "KUBECONFIG"
 
 	// WatchNamespaceEnvVar is the constant for env variable WATCH_NAMESPACE
-	// which is the namespace that the pod is currently running in.
+	// which is the namespace where the watch activity happens and where the pod is currently running in.
```
Comment (joelanford) [inline pkg/k8sutil/constants.go]: I think we can strike "and where the pod is currently running in." now that we have a distinction between the watched namespace and the operator namespace.

File: pkg/k8sutil/k8sutil.go (hunk 5 above)
Comment (dbenque-1a) [reply pkg/k8sutil/k8sutil.go]: done

File: pkg/leader/leader.go [hunk 7]
```diff
@@ -54,7 +55,7 @@ const PodNameEnv = "POD_NAME"
 func Become(ctx context.Context, lockName string) error {
 	log.Info("Trying to become the leader.")
 
-	ns, err := myNS()
+	ns, err := k8sutil.GetOperatorNamespace()
```
Comment (LiliC) [inline pkg/leader/leader.go]: We can also remove the function myNs() as it is not being used anymore.

Comment (dbenque-1a) [reply pkg/leader/leader.go]: Done, my bad, I should have done it with previous commit. Sorry for that "one more" iteration.

**Comment by LiliC** [comment]
pinging @estroz @joelanford to re-review. LGTM from my side.

**Comment by estroz** [comment]
@dbenque-1a needs a rebase. LGTM on green tests.

**Comment by dbenque-1a** [comment]
@estroz, rebase done.
@estroz @LiliC @joelanford , thanks for your reviews. At Amadeus ( https://amadeus.com/en  |  https://github.com/AmadeusITGroup/kubervisor ) we have already built couple of operators, the public ones are:
https://github.com/AmadeusITGroup/kubervisor
https://github.com/AmadeusITGroup/Redis-Operator
https://github.com/AmadeusITGroup/workflow-controller


 I must say that this SDK should really improve our efficiency in that exercise. At some point we wanted to build such a SDK.. and you do it, thanks! So now we are going to be regular users and probably contributors.

Regards,
David Benque

**Comment by LiliC** [comment]
> I must say that this SDK should really improve our efficiency in that exercise. At some point we wanted to build such a SDK.. and you do it, thanks! So now we are going to be regular users and probably contributors.

Thanks for that! We are happy to welcome any contributions! And of course, feedback is always welcome.

I reran the tests they are 🍏 , this should be good to merge once @estroz dismisses his review. Thanks again!

**Comment by LiliC** [comment]
@dbenque-1a Thanks again!
