### PR TITLE
pkg/ansible/controller/reconcile.go: fix invalid logger.Info usage

### LINKED ISSUE #2025: Ansible operator markDone function causing DPANIC in reconcile.go
## Bug Report

When deleting a CR , markDone function is causing DPANIC

```
2019-09-30T21:50:00.152Z DPANIC markDone odd number of arguments passed as key-value pairs for logging {"ignored key": "sabreprojects.ngp.sabre.com \"ram08291-free-tier\" not found"}
github.com/go-logr/zapr.handleFields
/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106
github.com/go-logr/zapr.(*infoLogger).Info
/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:70
github.com/operator-framework/operator-sdk/pkg/ansible/controller.(*AnsibleOperatorReconciler).markDone
/home/rammohan/ansible-operator-v0.10.0+max_worker_fix/operator-sdk/pkg/ansible/controller/reconcile.go:313
github.com/operator-framework/operator-sdk/pkg/ansible/controller.(*AnsibleOperatorReconciler).Reconcile
/home/rammohan/ansible-operator-v0.10.0+max_worker_fix/operator-sdk/pkg/ansible/controller/reconcile.go:222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
/root/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntil
/root/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134
k8s.io/apimachinery/pkg/util/wait.Until
/root/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88
```

**What did you do?**
Deleting CR is causing above issue

**What did you expect to see?**
markDone call should not cause DPANIC when it cannot find the Kubernetes object

**What did you see instead? Under which circumstances?**
During CR deletion, markDone function call is causing DPANIC

**Environment**

* operator-sdk version: v0.10.x, 
* go version: go1.12.4
* Kubernetes version information: v1.11.0+d4cacc0
* Kubernetes cluster kind: Openshift v3.11.141

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Don not pass the 'err' object to the logger call below
logger.Info("Resource not found, assuming it was deleted", err)

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
This PR fixes invalid usages of `logger.Info` in `pkg/ansible/controller/reconcile.go` that cause a panic due to an invalid number of arguments passed to the function.

`logger.Info` requires an odd number of arguments, consisting of a mandatory message and an optional list of `key1, value1, key2, value2, ..., keyN, valueN` pairs.

**Motivation for the change:**
See https://github.com/operator-framework/operator-sdk/issues/2025

Closes #2025

### CODE REVIEW

File: pkg/ansible/controller/reconcile.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ func (r *AnsibleOperatorReconciler) markError(u *unstructured.Unstructured, name
 	// Get the latest resource to prevent updating a stale status
 	err := r.Client.Get(context.TODO(), namespacedName, u)
 	if apierrors.IsNotFound(err) {
-		logger.Info("Resource not found, assuming it was deleted", err)
+		logger.Info("Resource not found, assuming it was deleted")
 		return nil
 	}
 	if err != nil {
```
Comment (camilamacedo86) [inline pkg/ansible/controller/reconcile.go]:
```suggestion
	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// Return and don't requeue
			reqLogger.Info("Resource not found, assuming it was deleted")
			return reconcile.Result{}, nil
		}
		// Error reading the object - requeue the request.
		reqLogger.Error(err, "Failed to get Resource.")
		return reconcile.Result{}, err
	}
```

Comment (camilamacedo86) [inline pkg/ansible/controller/reconcile.go]:
```suggestion
	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// should don't requeue
			logger.Info("Resource not found, assuming it was deleted")
			return nil
		}
		// Error reading the object should requeue the request.
		logger.Error(err, "Failed to get Resource.")
		return err
	}
```

File: pkg/ansible/controller/reconcile.go [hunk 2]
```diff
@@ -310,7 +310,7 @@ func (r *AnsibleOperatorReconciler) markDone(u *unstructured.Unstructured, names
 	// Get the latest resource to prevent updating a stale status
 	err := r.Client.Get(context.TODO(), namespacedName, u)
 	if apierrors.IsNotFound(err) {
-		logger.Info("Resource not found, assuming it was deleted", err)
+		logger.Info("Resource not found, assuming it was deleted")
```
Comment (camilamacedo86) [inline pkg/ansible/controller/reconcile.go]: Hi @joelanford, 

It shows not be the root cause of this issue because the Info should not require a par, just the error one. The info expected only a string. 

Also, note that when the CR is deleted we should stop the reconcile which shows that is not what is happening in these scenarios. The markDone and markError will return nil then the reconcile will not have the info to required to be stoped. 

IMHO: In these places, if an error is faced then it should be returned. Where it is called should use the `IsNotFound(err)` in order to check if is the scenario where the CR was deleted to stop the reconcile. 

Also, I would add some comments as follows to make it clear. 

	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// Return and don't requeue
			logger.Info("Resource not found, assuming it was deleted")
			return reconcile.Result{}, nil
		}
		// Error reading the object - requeue the request.
		logger.Error(err, "Failed to get resource.")
		return reconcile.Result{}, err
	}

Comment (joelanford) [reply pkg/ansible/controller/reconcile.go]: @camilamacedo86 I made this PR to solve just the DPANIC issue from #2025, and I specifically didn't want to include any other ancillary changes.

Based on my quick look at #2032, it looks like just a slight refactoring with some extra logging, which isn't related to the issue reported in #2025 as far as I can tell.

Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: The  #2032 would allow the reconcile to stop when the CR is removed which by looking the code in the markDone and markError is not.
