### PR TITLE
Fix Migration Guide link

### LINKED ISSUE #3862: documentation: Link to project migration guide is 404
#### What did you do?

[kni@provisionhost-0-0 kata-operator]$ operator-sdk version
[Deprecation Notice] Operator SDK has a new CLI and project layout that is aligned with Kubebuilder.
See `operator-sdk init -h` and the following doc on how to scaffold a new project:
https://v0-19-x.sdk.operatorframework.io/docs/golang/quickstart/
To migrate existing projects to the new layout see:
https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/

operator-sdk version: "v0.19.3", commit: "d529ba46aa04b85dfe2dba9074a6f7943ce7886d", kubernetes version: "v1.18.2", go version: "go1.13 linux/amd64"

#### What did you expect to see?

To click on the link project migration guide and see it

#### What did you see instead? Under which circumstances?

A 404 error page

`$ operator-sdk version`

v0.19.3

#### Possible Solution

Fix the URL. Maybe this is the right one? -> https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

### PR DESCRIPTION
**Pull request by pradeepnnv**
Fixes #3862

**This Change fixes the Link to project migration guide**

**Project Migration Guide link is broken.:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: cmd/operator-sdk/main.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func main() {
 				"See `operator-sdk init -h` and the following doc on how to scaffold a new project:\n" +
 				"https://v0-19-x.sdk.operatorframework.io/docs/golang/quickstart/\n" +
 				"To migrate existing projects to the new layout see:\n" +
-				"https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/\n"
+				"https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/\n"
 			projutil.PrintDeprecationWarning(depMsg)
 		}
 		if err := cli.RunLegacy(); err != nil {
```
Comment (camilamacedo86) [inline cmd/operator-sdk/main.go:54]: It shows great and it is just missing the fragment. 
See the changelog directory. we add the fragment and teh CHANGELOG it is gen over it.

Comment (pradeepnnv) [reply cmd/operator-sdk/main.go:54]: Thanks @camilamacedo86 . I added the changelog fragment. Please review.

File: cmd/operator-sdk/main.go [hunk 2]
```diff
@@ -48,7 +48,7 @@ func main() {
 				"See `operator-sdk init -h` and the following doc on how to scaffold a new project:\n" +
 				"https://v0-19-x.sdk.operatorframework.io/docs/golang/quickstart/\n" +
 				"To migrate existing projects to the new layout see:\n" +
-				"https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/\n"
+				"https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/\n"
```
Comment (estroz) [inline cmd/operator-sdk/main.go:51]: If we want users to upgrade to the latest operator-sdk with the most up-to-date docs, shouldn't this point to the latest guide?
```suggestion
				"https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/\n"
```

**Review by estroz — CHANGES_REQUESTED** [review]

File: cmd/operator-sdk/main.go (hunk 2 above)
Comment (pradeepnnv) [reply cmd/operator-sdk/main.go:51]: Sure @estroz . I was going by the update from @camilamacedo86 in the issue https://github.com/operator-framework/operator-sdk/issues/3862. Please confirm if this is the expected update so that I'll make this change.

Comment (camilamacedo86) [reply cmd/operator-sdk/main.go:51]: Hi @estroz, 

it is the SDK 0.19.x branch. So, here we should make the tool and all point of to the docs of its version and not master branch. See that the master branch can change.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

great work 🥇

**Comment by pradeepnnv** [comment]
Thanks @camilamacedo86 . Guessing I can merge now.

**Comment by camilamacedo86** [comment]
Hi @pradeepnnv,

> Thanks @camilamacedo86 . Guessing I can merge now.

The process defines that we need 2 LGTM before merging the changes. Open source is based on feedbacks and health discussions for we achieve the best result :-)  Let's see if the reason for we do not point out to master branch is clear for @estroz as well and he agrees as well with it and/or if at least we can get here +1 OK.

**Comment by pradeepnnv** [comment]
Thanks @camilamacedo86 . I'll wait for @estroz to approve before merging.

File: cmd/operator-sdk/main.go (hunk 2 above)
Comment (joelanford) [reply cmd/operator-sdk/main.go:51]: I think @estroz's suggestion makes sense from a content standpoint. Future 1.x updates should all be backward compatible, so the migration from 0.19 should never change again until we get to 2.x.

The one problem that @camilamacedo86 raises is the actual location of the link might change. Perhaps in a follow-up we can look into whether it would be possible to check that link somewhere along the line in our CI process.

**Comment by camilamacedo86** [comment]
I @pradeepnnv, 

Shows that @estroz and @joelanford for this specific scenario prefer to point out for the latest version. I just commit the @estroz suggestion. let's see if we are able to get it merged in time to ship with the next 0.19.4 release.

**Comment by joelanford** [comment]
@pradeepnnv Just FYI, I rebased your branch to the latest v0.19.x, which had some other necessary fixes. Hopefully the currently running CI will pass and we can get this into v0.19.4.

**Review by joelanford — APPROVED** [review]
/lgtm
