### PR TITLE
Scorecard finalizer fix

### LINKED ISSUE #2094: Scorecard does not wait for finalisers to complete before removing operator
## Bug Report

**What did you do?**
Created a simple Ansible Operator with SDK v0.11.0 to reproduce an issue we are seeing on our Ansible operators where finalisers do not complete within a few seconds. 

Using the following tasks:
```yaml
---
- name: "Set state of {{ meta.name }}-test-cfg"
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: "v1"
      kind: ConfigMap
      metadata:
        name: "{{ meta.name }}-test-cfg"
        namespace: "{{ meta.namespace }}"
      data:
        key: value

- name: test wait
  shell: sleep 10
```

Set a finaliser set in watches:
```yaml
- version: v1
  group: example.com
  kind: TestCr
  playbook: /opt/ansible/playbook.yml
  finalizer:
    name: example.com
    vars:
      state: absent
```

Used the following scorecard configuration:
```yaml
scorecard:
  plugins:
    - basic:
        olm-deployed: false
        cr-manifest:
          - "deploy/crds/icm.ibm.com_v1_testcr_cr.yaml"
        init-timeout: 300
```

**What did you expect to see?**
With the sleep task disabled I see the following as expected: 
```
operator-sdk scorecard --verbose   
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
Basic Tests:
        Writing into CRs has an effect: 1/1
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
```

**What did you see instead? Under which circumstances?**
Instead I get an error that cleanup does not complete:
```
operator-sdk scorecard --verbose       
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
WARN[0044] time="2019-10-23T15:19:35+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=error msg="Failed to cleanup resources: (a cleanup function failed; see stdout for more details)" 
Basic Tests:
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
        Writing into CRs has an effect: 1/1
```

Watching the operator deployment I can see that it gets removed before the finaliser completes.

**Environment**
* operator-sdk version:

operator-sdk version: "v0.11.0"
commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d"

* go version:
go version: "go1.13.1 darwin/amd64"

* Kubernetes version information:
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Docker desktop 2.1.4.0 on macOs 10.15

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Scorecard should wait before removing the operator deployment if finalisers are set.

### PR DESCRIPTION
**Pull request by jmccormick2001**
**Description of the change:**
make the scorecard cleanup use the init-timeout configuration setting when doing its cleanup, this will allow operators that specify a finalizer to have time to perform their cleanup based on a configurable value instead of the previous hard-coded value.

**Motivation for the change:**

Closes #2094

### CODE REVIEW

File: internal/scorecard/plugins/resource_handler.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ func createKubeconfigSecret(namespace string) error {
 		return err
 	}
 	addResourceCleanup(kubeconfigSecret, types.NamespacedName{Namespace: kubeconfigSecret.GetNamespace(),
-		Name: kubeconfigSecret.GetName()})
+		Name: kubeconfigSecret.GetName()}, 60)
```
Comment (camilamacedo86) [inline internal/scorecard/plugins/resource_handler.go]: should not here be the initTimeout as well?

Comment (jmccormick2001) [reply internal/scorecard/plugins/resource_handler.go]: good catch, fixed, also updated the CHANGELOG and docs with this latest commit.
