### PR TITLE
scorecard - lookup namespace from kubeconfig

### LINKED ISSUE #3422: Scorecard should use namespace from user's kubeconfig context
## Bug Report

**What did you do?**
1. Created a namespace called `scorecard-test`
2. Updated my `~/.kube/config` file to make `scorecard-test` my current context namespace
3. Ran `operator-sdk alpha scorecard ./internal/scorecard/alpha/testdata/bundle --skip-cleanup`
4. Ran `kubectl get pods`

**What did you expect to see?**
I expected to see the scorecard pods in the `scorecard-test` namespace.

**What did you see instead? Under which circumstances?**
I found the scorecard pods in the `default` namespace.

**Environment**
* operator-sdk version:

operator-sdk version: "v0.19.0-17-g2594430b", commit: "2594430b796836fb2e1b1b79b5970beae5346a37", kubernetes version: "v1.18.2", go version: "go1.14.4 linux/amd64"

* go version:

go version go1.13.10 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: minikube

* Are you writing your operator in ansible, helm, or go? N/A

**Possible Solution**
When loading the config, get the current context's namespace and use that as the default when `--namespace` is not defined.

**Additional context**

### PR DESCRIPTION
**Pull request by jmccormick2001**
**Description of the change:**

add logic in scorecard command to lookup the namespace, if not set on the command line, from the 
kubeconfig

**Motivation for the change:**

Closes #3422 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: internal/scorecard/kubeclient_test.go [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+package scorecard
+
+import (
+	"io/ioutil"
+	"log"
+	"os"
+	"testing"
+)
+
+func TestGetKubeNamespace(t *testing.T) {
```
Comment (joelanford) [inline internal/scorecard/kubeclient_test.go:24]: Nit: we should be writing all new tests with ginkgo/gomega. But let's get this merged and add a TODO.

File: internal/scorecard/kubeclient.go [hunk 2]
```diff
@@ -47,3 +48,35 @@ func GetKubeClient(kubeconfig string) (client kubernetes.Interface, err error) {
...
+
+	if kubeconfigPath != "" {
+		rules.ExplicitPath = kubeconfigPath
+	}
+
+	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(rules, &clientcmd.ConfigOverrides{})
+
+	ns, _, err := kubeConfig.Namespace()
+	if err != nil {
+		return "default"
```
Comment (estroz) [inline internal/scorecard/kubeclient.go:78]: The `"default"` namespace might not exist, and we probably shouldn't mask this error so I would return it to the CLI.

File: internal/scorecard/kubeclient.go [hunk 3]
```diff
@@ -47,3 +48,35 @@ func GetKubeClient(kubeconfig string) (client kubernetes.Interface, err error) {
...
+
+	if namespace != "" {
+		return namespace
+	}
+
+	rules := clientcmd.NewDefaultClientConfigLoadingRules()
+
+	if kubeconfigPath != "" {
+		rules.ExplicitPath = kubeconfigPath
+	}
```
Comment (estroz) [inline internal/scorecard/kubeclient.go:72]: Nit:
```suggestion
	rules.ExplicitPath = kubeconfigPath
```

File: internal/scorecard/kubeclient.go (hunk 2 above)
Comment (estroz) [reply internal/scorecard/kubeclient.go:78]: Address in a follow-up
