### PR TITLE
*: use fmt.Errorf with %w/%v for Go 1.13 error wrapping

### LINKED ISSUE #2308: Use Go 1.13 error wrapping
Now that we've upgraded to Go 1.13, we should find instances in our code base of:
1. `errors.Wrap()`, `errors.Wrapf()`, and replace them with `fmt.Errorf()` with `%w`.
2. `fmt.Errorf()` calls that wrap an error, but use `%s` or `%v`, and replace them with `fmt.Errorf()` with `%w`
3. Any other uses of the `github.com/pkg/errors` package should be transitioned over to Go's standard library `errors` package, if possible.

All `fmt.Errorf()` calls that wrap an error should look like the following:
```go
fmt.Errorf("some context about my error: %w", err)
```

* `%w` should be preceded by `: ` (colon space)
* `%w` should not be in parentheses

### PR DESCRIPTION
**Pull request by nrchakradhar**
Use fmt.Errorf as per 1.13. Changed errors.Wrap and errors.Wrapf to use fmt.Errorf.

Fixes #2308
Closes #2308

**Description of the change:**
As the code is upgraded to go 1.13, error handling has been changed. The PR addresses the same.

1. errors.Wrap(), errors.Wrapf(), are replaced with fmt.Errorf() with %w.
2. fmt.Errorf() calls that wrap an error, but use %s or %v, are replaced with fmt.Errorf() with %w
3. Uses of the github.com/pkg/errors package is transitioned over to Go's standard library errors package.

All fmt.Errorf() calls that wrap an error are changed as below:

`fmt.Errorf("some context about my error: %w", err)`

**Motivation for the change:**
Upgrade to go 1.13 version

### CODE REVIEW

**Comment by nrchakradhar** [comment]
@joelanford @jmrodri @jmccormick2001 
Can you please take a look. I had made multiple commits but have now squashed them and CI has passed.
Let me know if there are any changes to be done.

File: cmd/operator-sdk/new/cmd.go [hunk 1]
```diff
@@ -354,14 +353,14 @@ func doHelmScaffold() error {
 	}
 
 	if err := scaffold.UpdateRoleForResource(resource, cfg.AbsProjectPath); err != nil {
-		return fmt.Errorf("failed to update the RBAC manifest for resource (%v, %v): %w", resource.APIVersion, resource.Kind, err)
+		return fmt.Errorf("failed to update the RBAC manifest for resource (%v, %w): %w", resource.APIVersion, resource.Kind, err)
```
Comment (estroz) [inline cmd/operator-sdk/new/cmd.go]:
```suggestion
		return fmt.Errorf("failed to update the RBAC manifest for resource (%v, %v): %w", resource.APIVersion, resource.Kind, err)
```

File: cmd/operator-sdk/add/api.go [hunk 2]
```diff
@@ -25,7 +25,6 @@ import (
 	"github.com/operator-framework/operator-sdk/internal/scaffold/input"
```
Comment (estroz) [inline cmd/operator-sdk/add/api.go]: Any `fmt.Errorf` in `cmd/operator-sdk` can be left as `%v` for now since the consumer of those errors is cobra, which doesn't unwrap errors. You can remove the parentheses around `(%v)` though.

File: internal/scorecard/scorecard.go [hunk 3]
```diff
@@ -181,6 +180,7 @@ func initConfig() error {
 		}
 		log.Info("Using config file: ", viper.ConfigFileUsed())
 	} else {
+		//TODO: What to change here
```
Comment (estroz) [inline internal/scorecard/scorecard.go]: No need to change anything here in this PR.

File: internal/util/operator-registry/package_manifest.go [hunk 4]
```diff
@@ -18,19 +18,18 @@ import (
 	"fmt"
 
 	"github.com/operator-framework/operator-registry/pkg/registry"
-	"github.com/pkg/errors"
 )
 
 func ValidatePackageManifest(pkg *registry.PackageManifest) error {
 	if pkg.PackageName == "" {
-		return errors.New("package name cannot be empty")
+		return fmt.Errorf("package name cannot be empty")
```
Comment (estroz) [inline internal/util/operator-registry/package_manifest.go]: No need to change these from `errors.New` to `fmt.Errorf`. Instead, use the std `errors` package over `github.com/pkg/errors`.

File: pkg/ansible/watches/watches.go [hunk 5]
```diff
@@ -120,7 +120,7 @@ func (w *Watch) UnmarshalYAML(unmarshal func(interface{}) error) error {
 	}
 	err = verifyGVK(gvk)
 	if err != nil {
-		return fmt.Errorf("invalid GVK: %v - %s", gvk.String(), err)
+		return fmt.Errorf("invalid GVK: %v: %w", gvk.String(), err)
```
Comment (estroz) [inline pkg/ansible/watches/watches.go]:
```suggestion
		return fmt.Errorf("invalid GVK %s: %w", gvk, err)
```

File: pkg/helm/release/manager.go [hunk 6]
```diff
@@ -174,10 +174,11 @@ func (m manager) InstallRelease(ctx context.Context) (*rpb.Release, error) {
 			// Only log a message about a rollback failure if the failure was caused
 			// by something other than the release not being found.
 			if uninstallErr != nil && !notFoundErr(uninstallErr) {
+				//TODO: What to change this to?
 				return nil, fmt.Errorf("failed installation (%s) and failed rollback (%s)", err, uninstallErr)
```
Comment (estroz) [inline pkg/helm/release/manager.go]:
```suggestion
				return nil, fmt.Errorf("failed installation (%w) and failed rollback (%w)", err, uninstallErr)
```


`%w` works anywhere in the formatting string.

File: pkg/helm/release/manager.go [hunk 7]
```diff
@@ -201,10 +202,11 @@ func (m manager) UpdateRelease(ctx context.Context) (*rpb.Release, *rpb.Release,
 			// log both the update and rollback errors.
 			rollbackErr := rollback.Run(m.releaseName)
 			if rollbackErr != nil {
+				//TODO: What to change this to
 				return nil, nil, fmt.Errorf("failed update (%s) and failed rollback (%s)", err, rollbackErr)
```
Comment (estroz) [inline pkg/helm/release/manager.go]:
```suggestion
				return nil, nil, fmt.Errorf("failed update (%w) and failed rollback (%w)", err, rollbackErr)
```

File: internal/generate/gen/rules.go [hunk 8]
```diff
@@ -45,12 +45,12 @@ func (o OutputToCachedDirectory) Open(_ *loader.Package, path string) (io.WriteC
 		return nil, fmt.Errorf("error opening %s in output rule: cache must be set", path)
```
Comment (estroz) [inline internal/generate/gen/rules.go]: Anything in `internal` is an internal implementation detail, and errors in here are not necessarily relevant to users. According to the working with errors [blog post](https://blog.golang.org/go1.13-errors), implementation detail errors should not necessarily be exposed for unwrapping. Unless explicitly required by an error consumer within SDK code, `internal` errors should not be wrapped for now. You can still change `errors.Wrap` to `fmt.Errorf("...: %s", ..., err)`, which will hide the error if it implements `Unwrap`.

File: CHANGELOG.md [hunk 9]
```diff
@@ -9,7 +9,7 @@
 - Improve Ansible logs in the Operator container for Ansible-based Operators. ([#2321](https://github.com/operator-framework/operator-sdk/pull/2321))
 
 ### Changed
-
+- Changed to go 1.13 way of handling errors. ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```
Comment (estroz) [inline CHANGELOG.md]:
```suggestion
- Wrapped relevant errors per Go 1.13 error handling. ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```

File: pkg/helm/release/manager.go (hunk 6 above)
Comment (nrchakradhar) [reply pkg/helm/release/manager.go]: Per [Errorf reference](https://golang.org/pkg/fmt/#Errorf), and re-iterated in this [issue](https://github.com/golang/go/issues/34060), 
**It is invalid to include more than one %w verb**, so what should the change be?

File: pkg/helm/release/manager.go (hunk 7 above)
Comment (nrchakradhar) [reply pkg/helm/release/manager.go]: Per [Errorf reference](https://golang.org/pkg/fmt/#Errorf), and re-iterated in this [issue](https://github.com/golang/go/issues/34060), 
**It is invalid to include more than one %w verb**, so what should the change be?

File: cmd/operator-sdk/new/cmd.go (hunk 1 above)
Comment (nrchakradhar) [reply cmd/operator-sdk/new/cmd.go]: Sorry. My bad. Changed.

File: internal/scorecard/scorecard.go (hunk 3 above)
Comment (nrchakradhar) [reply internal/scorecard/scorecard.go]: Removed the TODO comment.

File: internal/util/operator-registry/package_manifest.go (hunk 4 above)
Comment (nrchakradhar) [reply internal/util/operator-registry/package_manifest.go]: One of the items mentioned in #2308 was about using native go lang errors. Hence I changed this. Please confirm if dependency on `github.com/pkg/errors` is fine to have.
I thought its better to remove this dependency.

File: pkg/ansible/watches/watches.go (hunk 5 above)
Comment (nrchakradhar) [reply pkg/ansible/watches/watches.go]: Done.

File: CHANGELOG.md (hunk 9 above)
Comment (nrchakradhar) [reply CHANGELOG.md]: Done

Comment (nrchakradhar) [reply CHANGELOG.md]: Done

File: cmd/operator-sdk/new/cmd.go (hunk 1 above)
Comment (nrchakradhar) [reply cmd/operator-sdk/new/cmd.go]: This file is also under `cmd/operator-sdk`. So shall I remove %w here as per [this comment](https://github.com/operator-framework/operator-sdk/pull/2355/files#r362048008), OR there are certain files under `cmd/operator-sdk` that needs to be specifically looked into.

File: cmd/operator-sdk/add/api.go (hunk 2 above)
Comment (nrchakradhar) [reply cmd/operator-sdk/add/api.go]: I can do a find-replace all for %w with %v for all files under `cmd/operator-sdk`, but was confused with another [comment below](https://github.com/operator-framework/operator-sdk/pull/2355/files#r362047287)

File: cmd/operator-sdk/new/cmd.go (hunk 1 above)
Comment (estroz) [reply cmd/operator-sdk/new/cmd.go]: Ignore this comment and remove `%w` changes as specified [here](https://github.com/operator-framework/operator-sdk/pull/2355#discussion_r362048008).

File: internal/util/operator-registry/package_manifest.go (hunk 4 above)
Comment (estroz) [reply internal/util/operator-registry/package_manifest.go]: You can use the `”errors"` package, which is in the standard library.

File: pkg/helm/release/manager.go (hunk 6 above)
Comment (estroz) [reply pkg/helm/release/manager.go]: Use `%v` for `err` and `%w` for `uninstallErr` since we’re returning after checking the latter.

File: pkg/helm/release/manager.go (hunk 7 above)
Comment (estroz) [reply pkg/helm/release/manager.go]: See https://github.com/operator-framework/operator-sdk/pull/2355#discussion_r362285536.

File: pkg/helm/release/manager.go (hunk 6 above)
Comment (nrchakradhar) [reply pkg/helm/release/manager.go]: Done.

File: pkg/helm/release/manager.go (hunk 7 above)
Comment (nrchakradhar) [reply pkg/helm/release/manager.go]: Done

File: cmd/operator-sdk/add/api.go (hunk 2 above)
Comment (nrchakradhar) [reply cmd/operator-sdk/add/api.go]: Done

File: internal/util/operator-registry/package_manifest.go (hunk 4 above)
Comment (nrchakradhar) [reply internal/util/operator-registry/package_manifest.go]: Done.

File: internal/generate/gen/rules.go (hunk 8 above)
Comment (nrchakradhar) [reply internal/generate/gen/rules.go]: Done

**Comment by nrchakradhar** [comment]
@estroz can you please check the changes and let me know if additional changes are needed. Thanks

File: cmd/operator-sdk/new/cmd.go (hunk 1 above)
Comment (nrchakradhar) [reply cmd/operator-sdk/new/cmd.go]: Done.

File: CHANGELOG.md [hunk 10]
```diff
@@ -9,7 +9,7 @@
 - Improve Ansible logs in the Operator container for Ansible-based Operators. ([#2321](https://github.com/operator-framework/operator-sdk/pull/2321))
 
 ### Changed
-
+- Wrapped relevant errors per Go 1.13 error handling. ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```
Comment (camilamacedo86) [inline CHANGELOG.md]: WDYT about something as: 

```suggestion
- Changes in errors format to handle them according to the Go version 1.13+. ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```

Comment (nrchakradhar) [reply CHANGELOG.md]: Done

**Comment by nrchakradhar** [comment]
@camilamacedo86 I have rebased and pre-submit checks have passed. PTAL.
Let me know if any additional changes are needed. Thanks for accepting the contribution.

File: test/e2e/_incluster-test-code/memcached_test.go [hunk 11]
```diff
@@ -126,7 +126,7 @@ func verifyLeader(t *testing.T, namespace string, f *framework.Framework, labels
 		return true, nil
 	})
 	if err != nil {
-		return nil, fmt.Errorf("error getting leader lock configmap: %v", err)
```
Comment (estroz) [inline test/e2e/_incluster-test-code/memcached_test.go]: @nrchakradhar also nothing in `test/` should be wrapped. Otherwise LGTM.

File: CHANGELOG.md [hunk 12]
```diff
@@ -10,7 +10,7 @@
 - Added support for override values with environment variable expansion in the `watches.yaml` file for Helm-based operators. ([#2325](https://github.com/operator-framework/operator-sdk/pull/2325))
 
 ### Changed
-
+- Changes in `errors` wrapped to handle them according to the Go version 1.13+. More info: https://blog.golang.org/go1.13-errors. ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```
Comment (estroz) [inline CHANGELOG.md]:
```suggestion

- Changed error wrapping according to Go version 1.13+ [error handling](https://blog.golang.org/go1.13-errors). ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```

File: test/e2e/_incluster-test-code/memcached_test.go (hunk 11 above)
Comment (nrchakradhar) [reply test/e2e/_incluster-test-code/memcached_test.go]: Changes done.

**Comment by nrchakradhar** [comment]
I hope I have addressed all the changes. @estroz @camilamacedo86 PTAL. Thanks.

File: CHANGELOG.md [hunk 13]
```diff
@@ -22,7 +22,7 @@
 - Added support for override values with environment variable expansion in the `watches.yaml` file for Helm-based operators. ([#2325](https://github.com/operator-framework/operator-sdk/pull/2325))
 
 ### Changed
-
+- Changed error wrapping according to Go version 1.13+ [error handling](https://blog.golang.org/go1.13-errors). ([#2355](https://github.com/operator-framework/operator-sdk/pull/2355))
```
Comment (camilamacedo86) [inline CHANGELOG.md]: Hi @nrchakradhar,

We had a new release so it needs to be updated with the master and the CHANGELOG properly updated. Could you please do that for we are able to merge?

**Comment by nrchakradhar** [comment]
@estroz @camilamacedo86 Travis error shows that there is a mismatch in go module versions.
I am not sure why the build is failing and how to fix it. Can you please help?

**Comment by estroz** [comment]
@nrchakradhar merge your branch with master, that should resolve the issue.

**Comment by nrchakradhar** [comment]
The new failure seems to be different than the changes.
https://travis-ci.org/operator-framework/operator-sdk/jobs/637862112?utm_medium=notification

Found broken url       (#1571 -> https://github.com/operator-framework/operator-sdk/pull/1571) at ./CHANGELOG.md:221 : 502 Bad Gateway
Found broken url       (#2298 -> https://github.com/operator-framework/operator-sdk/pull/2298) at ./CHANGELOG.md:81 : 502 Bad Gateway
