### PR TITLE
internal/pkg/scaffold: add group.go scaffold to prevent deepcopy parse errors

### LINKED ISSUE #1502: cannot find module providing package
**What did you do?**
I following the guide to add example-inc API, but got cannot find module providing package:
```
$ operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService
INFO[0000] Generating api version app.example.com/v1alpha1 for kind AppService. 
INFO[0000] Created pkg/apis/app/v1alpha1/appservice_types.go 
INFO[0000] Created pkg/apis/addtoscheme_app_v1alpha1.go 
INFO[0000] Created pkg/apis/app/v1alpha1/register.go    
INFO[0000] Created pkg/apis/app/v1alpha1/doc.go         
INFO[0000] Created deploy/crds/app_v1alpha1_appservice_cr.yaml 
W0530 09:51:53.863324   20942 parse.go:239] Ignoring child directory github.com/example-inc/app-operator/pkg/apis/app: unable to import "github.com/example-inc/app-operator/pkg/apis/app": go/build: importGo github.com/example-inc/app-operator/pkg/apis/app: exit status 1
can't load package: package github.com/example-inc/app-operator/pkg/apis/app: unknown import path "github.com/example-inc/app-operator/pkg/apis/app": cannot find module providing package github.com/example-inc/app-operator/pkg/apis/app

INFO[0013] Created deploy/crds/app_v1alpha1_appservice_crd.yaml 
Error: exit status 1
Usage:
  operator-sdk add api [flags]

Flags:
      --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
  -h, --help                 help for api
      --kind string          Kubernetes resource Kind name. (e.g AppService)

Global Flags:
      --verbose   Enable verbose loggin
```

**What did you expect to see?**
I pass without error

**What did you see instead? Under which circumstances?**
I use the operator-sdk v0.8.1 release and make install to build and install.

**Environment**
* operator-sdk version: `operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342`

* Kubernetes version information: `Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: `minikube`

* go version: `go version go1.12 linux/amd64`

* go variables:
```
GO111MODULE=on
GOPATH=/home/user/go
GOROOT=/usr/lib/go-1.12/bin/
```

* current directory: `/home/user/go/src/github.com/example-inc/app-operator`

### LINKED ISSUE #1546: Warning during `add api` about missing package
## Bug Report

When adding a new api via

```
operator-sdk add api --api-version=hello.k8spatterns.io/v1alpha1 --kind=Hello
```

on a freshly created project, I get the following output:

```
INFO[0000] Generating api version hello.k8spatterns.io/v1alpha1 for kind Hello.
INFO[0002] Created pkg/apis/hello/v1alpha1/hello_types.go
INFO[0002] Created pkg/apis/addtoscheme_hello_v1alpha1.go
INFO[0002] Created pkg/apis/hello/v1alpha1/register.go
INFO[0002] Created pkg/apis/hello/v1alpha1/doc.go
INFO[0002] Created deploy/crds/hello_v1alpha1_hello_cr.yaml
W0611 10:29:21.440169   56433 parse.go:239] Ignoring child directory github.com/k8spatterns/hello-operator/pkg/apis/hello: unable to import "github.com/k8spatterns/hello-operator/pkg/apis/hello": go/build: importGo github.com/k8spatterns/hello-operator/pkg/apis/hello: exit status 1
can't load package: package github.com/k8spatterns/hello-operator/pkg/apis/hello: unknown import path "github.com/k8spatterns/hello-operator/pkg/apis/hello": cannot find module providing package github.com/k8spatterns/hello-operator/pkg/apis/hello

INFO[0013] Created deploy/crds/hello_v1alpha1_hello_crd.yaml
INFO[0018] Running deepcopy code-generation for Custom Resource group versions: [hello:[v1alpha1], ]
INFO[0023] Code-generation complete.
INFO[0025] Running OpenAPI code-generation for Custom Resource group versions: [hello:[v1alpha1], ]
2019/06/11 10:29:38 Code for OpenAPI definitions generated
INFO[0030] Created deploy/crds/hello_v1alpha1_hello_crd.yaml
INFO[0030] Code-generation complete.
INFO[0030] API generation complete.
```

It looks like it succeeded and the directory `pkg/apis/hello` has been created eventually:

```
ls pkg/apis/hello
v1alpha1
```

However, the warning is a bit disturbing. Also I was wondering why I was ask for my GitHub credentials during the process (looks like a read-write checkout of some GitHub repo)

grafik

Here the full output with `--verbose`:

<details>
<summary>operator-sdk add api --api-version=hello.k8spatterns.io/v1alpha1 --kind=Hello --verbose</summary>

```
DEBU[0000] Debug logging is set
INFO[0000] Generating api version hello.k8spatterns.io/v1alpha1 for kind Hello.
INFO[0002] Created pkg/apis/hello/v1alpha1/hello_types.go
INFO[0002] Created pkg/apis/addtoscheme_hello_v1alpha1.go
INFO[0002] Created pkg/apis/hello/v1alpha1/register.go
INFO[0002] Created pkg/apis/hello/v1alpha1/doc.go
INFO[0002] Created deploy/crds/hello_v1alpha1_hello_cr.yaml
W0611 10:36:35.669666   61132 parse.go:239] Ignoring child directory github.com/k8spatterns/hello-operator/pkg/apis/hello: unable to import "github.com/k8spatterns/hello-operator/pkg/apis/hello": go/build: importGo github.com/k8spatterns/hello-operator/pkg/apis/hello: exit status 1
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
can't load package: package github.com/k8spatterns/hello-operator/pkg/apis/hello: unknown import path "github.com/k8spatterns/hello-operator/pkg/apis/hello": cannot find module providing package github.com/k8spatterns/hello-operator/pkg/apis/hello

INFO[0053] Created deploy/crds/hello_v1alpha1_hello_crd.yaml
DEBU[0053] Running []string{"go", "build", "-o", "/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/client-gen", "./cmd/client-gen"}
DEBU[0054] Running []string{"go", "build", "-o", "/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/lister-gen", "./cmd/lister-gen"}
DEBU[0055] Running []string{"go", "build", "-o", "/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/informer-gen", "./cmd/informer-gen"}
DEBU[0056] Running []string{"go", "build", "-o", "/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/deepcopy-gen", "./cmd/deepcopy-gen"}
INFO[0057] Running deepcopy code-generation for Custom Resource group versions: [hello:[v1alpha1], ]
DEBU[0057] Running []string{"/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/deepcopy-gen", "--input-dirs", "github.com/k8spatterns/hello-operator/pkg/apis/hello/v1alpha1", "--output-file-base", "zz_generated.deepcopy", "--bounding-dirs", "github.com/k8spatterns/hello-operator/pkg/apis", "--go-header-file", "/var/folders/bh/fw5xsjw531n6crvdz9tgv_380000gn/T/984914475"}
INFO[0063] Code-generation complete.
DEBU[0063] Running []string{"go", "build", "-o", "/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/openapi-gen", "./cmd/openapi-gen"}
INFO[0064] Running OpenAPI code-generation for Custom Resource group versions: [hello:[v1alpha1], ]
DEBU[0064] Running []string{"/Users/roland/Development/go/workspace/src/github.com/k8spatterns/hello-operator/build/_output/bin/openapi-gen", "--input-dirs", "github.com/k8spatterns/hello-operator/pkg/apis/hello/v1alpha1", "--output-package", "github.com/k8spatterns/hello-operator/pkg/apis/hello/v1alpha1", "--output-file-base", "zz_generated.openapi", "--go-header-file", "/var/folders/bh/fw5xsjw531n6crvdz9tgv_380000gn/T/367750542"}
2019/06/11 10:36:51 Code for OpenAPI definitions generated
INFO[0069] Created deploy/crds/hello_v1alpha1_hello_crd.yaml
INFO[0069] Code-generation complete.
INFO[0069] API generation complete.
```

</details>

**Environment**
* operator-sdk version:

operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342

* go version:

go version go1.12.5 darwin/amd64

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** scaffold a `pkg/apis/<group>/group.go` file.

**Motivation for the change:** The following error is generated by the [gengo parser]():

```console
$ operator-sdk generate openapi
W0507 16:56:26.785419   21221 parse.go:239] Ignoring child directory github.com/test-org/operator/pkg/apis/<group>: No files for pkg "github.com/test-org/operator/pkg/apis/<group>"
```

which doesn't look great. While we could skip reporting the error if it has that form, we might accidentally skip a valid error. Adding a package file to the group package corrects the error without any other changes.

Closes #1502, closes #1546

### CODE REVIEW

**Comment by estroz** [comment]
@LiliC @joelanford the SDK will scaffold `pkg/apis/<group>/stub.go` if one does not exist. I've also added a check for existence of _any_ go files in `pkg/apis/<group>`; if one exists, `stub.go` is not scaffolded since it is unnecessary. PTAL.

**Comment by estroz** [comment]
@hasbro17 this is actually an ["issue"](https://github.com/golang/go/issues/28459) with `go/build`, and it looks like the [intended behaviour](https://github.com/golang/go/issues/28459#issuecomment-439425274) is to error.

From one of the issue [comments](https://github.com/golang/go/issues/28459#issuecomment-468930560):
>This issue appears to extend further - build.Import with build.FindOnly should return the directory path resolved for an import, even if there are no Go files in the directory, but this does not seem to be the case with Go modules.

This is exactly what [`k8s.io/gengo`](https://github.com/kubernetes/gengo/blob/master/parser/parse.go#L132) is doing, which is used by `controller-tools`, and by dependency us, to generate CRD's. If the intended behaviour is indeed to error if there are no go files in a package path, by implication the correct way to structure packages is to always have at least one go file in them, right? So perhaps this is the best solution.

**Comment by LiliC** [comment]
Coming back to this, while I was at the workshop a lot of users were super confused by the warning and came to me asking if this is a problem or not. So would be good to bypass this in a way, or suppress it just to avoid confusion IMHO.

File: cmd/operator-sdk/add/api.go [hunk 1]
```diff
@@ -102,8 +106,15 @@ func apiRun(cmd *cobra.Command, args []string) error {
 		Repo:           projutil.CheckAndGetProjectGoPkg(),
 		AbsProjectPath: absProjectPath,
 	}
-
 	s := &scaffold.Scaffold{}
+
+	// Check if any package files for this API group dir exist, and if not
+	// scaffold a stub.go to prevent erroneous gengo parse errors.
```
Comment (hasbro17) [inline cmd/operator-sdk/add/api.go]:
```suggestion
	// scaffold a group.go to prevent erroneous gengo parse errors.
```

Also below `stub`->`group`.

File: internal/pkg/scaffold/group.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+func (s *Group) GetInput() (input.Input, error) {
+	if s.Path == "" {
+		s.Path = filepath.Join(ApisDir, s.Resource.GoImportGroup, GroupFile)
+	}
+	s.TemplateBody = stubTmpl
+	return s.Input, nil
+}
+
+const stubTmpl = `// Package {{.Resource.GoImportGroup}} contains {{.Resource.GoImportGroup}} API versions
```
Comment (joelanford) [inline internal/pkg/scaffold/group.go]: Maybe also put an explanation in this comment for why this file is necessary?
