### PR TITLE
ansible: use correct download URL for tini on aarch64

### LINKED ISSUE #3233: arm64 base image doesn't actually work on arm64
## Bug Report

**What did you do?**

Installed aarch64 release of `operator-sdk`, created a skeleton ansible operator, and ran `operator-sdk build` to generate an image.

**What did you expect to see?**

The image should run.

**What did you see instead? Under which circumstances?**

`exec format error`

**Environment**
* operator-sdk version:

v0.18.1

**Additional context**

It looks like the `quay.io/operator-framework/ansible-operator:v0.18.1` base image for ARM64 doesn't have a working `tini` binary. The file at `/tini` just contains the text `Not found`. When I try to run the base image directly on my Raspberry Pi 4 under Ubuntu 20.04, I get `exec format error`. If I override the entrypoint to run `/usr/local/bin/entrypoint` directly, it actually runs.

### PR DESCRIPTION
**Pull request by agaffney**
**Description of the change:**

This fixes the build of the ansible-operator base image to use the correct download URL for `tini` on ARM64. This fixes issue #3233 

**Motivation for the change:**

The current ansible-operator base image for ARM64 doesn't work

### CODE REVIEW

File: internal/scaffold/ansible/dockerfilehybrid.go [hunk 1]
```diff
@@ -88,7 +88,7 @@ RUN mkdir -p ${HOME}/.ansible/tmp \
  && chown -R ${USER_UID}:0 ${HOME} \
  && chmod -R ug+rwx ${HOME}
```
Comment (camilamacedo86) [inline internal/scaffold/ansible/dockerfilehybrid.go:89]: missing add the fragment for the fix.

Comment (agaffney) [reply internal/scaffold/ansible/dockerfilehybrid.go:89]: Are you asking me to change something here?

Comment (jmrodri) [reply internal/scaffold/ansible/dockerfilehybrid.go:89]: @agaffney I think @camilamacedo86 is asking for the changelog fragment.

Here's the template: https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml

Comment (agaffney) [reply internal/scaffold/ansible/dockerfilehybrid.go:89]: Ah, I saw nothing about that in `CONTRIBUTING.md`, and I didn't see anything like this when I looked at some of the recently merged PRs after the above comment. This hardly seems worthy of a changelog entry, but I'll go ahead and create the fragment.

Comment (agaffney) [reply internal/scaffold/ansible/dockerfilehybrid.go:89]: Done

File: changelog/fragments/3234-arm64-tini-url.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+entries:
+  - description: >
+      Fix the download URL for the `tini` binary on ARM64 for the ansible
```
Comment (camilamacedo86) [inline changelog/fragments/3234-arm64-tini-url.yaml:3]:
```suggestion
      Fix the download URL for the `tini` binary on ARM64 for the Ansible based-Operators
```

File: changelog/fragments/3234-arm64-tini-url.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+      operator base image
```
Comment (estroz) [inline changelog/fragments/3234-arm64-tini-url.yaml:4]:
```suggestion
		Consider the `aarch64`/`arm64` architecture when downloading `tini` in the hybrid
		Ansible Dockerfile so ansible-operator images run on nodes of that architecture.
```

Comment (estroz) [reply changelog/fragments/3234-arm64-tini-url.yaml:4]: Actually this isn't necessary.
