### PR TITLE
pkg/k8sclient: add cache reset on 1 minute interval

### LINKED ISSUE #272: Dynamic Client doesn't discover newly created resources after operator has run
Currently The SDK's query, action, and Watch APIs are not able to discover a new resource
type after the operator has initiated.

For example:

We have a setup such that the operator gets the `AppService` resource every 5 seconds:
 
```go
a := &v1alpha1.AppService{
	TypeMeta: metav1.TypeMeta{
		Kind:       "AppService",
		APIVersion: "example.com/v1alpha1",
	},
	ObjectMeta: metav1.ObjectMeta{
		Name:      "bla",
		Namespace: "default",
	},
}
for {
	err := query.Get(a)
	if err != nil {
		logrus.Error(err)
	}
	time.Sleep(5 * time.Second)
}
```

Initially, the CRD of `AppService` is not registered. 

```sh
$ kubectl get CRD
No resources found.
```

The above code prints the error:

```sh
ERRO[0000] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
```

Let's create the CRD:

```sh
$ kubectl get crd
NAME                      AGE
appservices.example.com   7s
```

We expect the getter from main loop to eventually discover the `AppService` resource so that 
the getter gets the correct resource. However, that does not happen, and we get the same error as before:

```sh
ERRO[0035] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
```

### PR DESCRIPTION
**Pull request by shawn-hurley**
This sets up a go routine to reset the restMapper at a 1 minute
interval so that new resources can be found in the cluster.

fixes #272

### CODE REVIEW

File: pkg/k8sclient/client.go [hunk 1]
```diff
@@ -124,3 +128,30 @@ func outOfClusterConfig() (*rest.Config, error) {
 	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
 	return config, err
 }
+
+// stopCacheReset - Stops the rest mapper cache from reseting.
+func stopCacheReset() {
```
Comment (hasbro17) [inline pkg/k8sclient/client.go]: Do we ever need to call `stopCacheReset()`? I don't see it being used anywhere.
Also it's not something exposed to the user in the handler since it's not expected that an operator would ever want to turn this off and on again as part of normal operations.

So I would suggest to remove `stopCacheReset()` for now until we have a use case for it.
With that we can also get rid of `quit` and `started` and simplify the cache reset to:
```Go
func init() {
...
  go periodicResetRestMapper(1 * time.Minute)
}

func periodicResetRestMapper(duration time.Duration) {
  ticker := time.NewTicker(duration)
  for {
    select {
    case <-ticker.C:
      restMapper.Reset()
    }
  }
}
```

Ideally we'd pass a context to the go routine but we can't do that while all of this is being done in the init() function. That will have to wait until we refactor all of the global state into objects.

**Comment by fanminshi** [comment]
@shawn-hurley have you try this pr to see if it fixes the issue in #272.

**Comment by hasbro17** [comment]
@shawn-hurley You can do a manual test with the example in #272 to see if the RestMapper is able to pick a newly registered resource.

**Comment by shawn-hurley** [comment]
For testing I am using the [starter-pack-operator](https://github.com/shawn-hurley/starter-pack-operator). 

I am overriding the GoPkg.toml to use my branch of the operator-sdk and then running the `kubectl create -f deploy/crd.yaml` then running `operator-sdk up local --operator-flags="--namespace test"` then you will have to create the cr using `kubectl create -f deploy/cr.yaml`

While the operator is running you should see that we can't find the cluster service broker resource. To test the PR you can install the [svc-catalog](https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/) through helm and it should go away.

**Comment by shawn-hurley** [comment]
```console
INFO[0000] Go Version: go1.10.1
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
ERRO[0000] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0005] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0010] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0015] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0020] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0025] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0030] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0035] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0040] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0045] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0050] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0055] failed to get resource client for (apiVersion:example.com/v1alpha1, kind:AppService, ns:default): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(example.com/v1alpha1, Kind=AppService): no matches for example.com/, Kind=AppService
ERRO[0060] appservices.example.com "bla" not found
ERRO[0065] appservices.example.com "bla" not found
ERRO[0070] appservices.example.com "bla" not found
ERRO[0075] appservices.example.com "bla" not found
ERRO[0080] appservices.example.com "bla" not found
ERRO[0085] appservices.example.com "bla" not found
ERRO[0090] appservices.example.com "bla" not found
```

Output from running the operator with the my change.

**Comment by fanminshi** [comment]
lgtm

**Comment by fanminshi** [comment]
@shawn-hurley One more thing. Could you also update [changelog](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md) with this fix. Thanks!
