### PR TITLE
fix bundle run install mode MultiNamespace

### LINKED ISSUE #4512: operator-sdk run bundle fails on MultiNamespace install mode
#### What did you do?

```
operator-sdk --verbose run bundle quay.io/maistra/istio-workspace-operator-bundle:v0.0.5-next -n istio-workspace-operator --install-mode MultiNamespace=bundle-single,bundle-test
INFO[0011] Successfully created registry pod: quay-io-maistra-istio-workspace-operator-bundle-v0-0-5-next 
INFO[0012] Created CatalogSource: istio-workspace-operator-catalog 
FATA[0012] Failed to run bundle: no supported install modes 
```

#### What did you expect to see?

```
operator-sdk --verbose run bundle quay.io/maistra/istio-workspace-operator-bundle:v0.0.5-next -n istio-workspace-operator --install-mode MultiNamespace=bundle-single,bundle-test
INFO[0011] Successfully created registry pod: quay-io-maistra-istio-workspace-operator-bundle-v0-0-5-next 
INFO[0011] Created CatalogSource: istio-workspace-operator-catalog 
INFO[0011] OperatorGroup "operator-sdk-og" created      
INFO[0011] Created Subscription: istio-workspace-operator-v0-0-5-next-sub 
INFO[0021] Approved InstallPlan install-dhk4f for the Subscription: istio-workspace-operator-v0-0-5-next-sub 
INFO[0021] Waiting for ClusterServiceVersion "istio-workspace-operator/istio-workspace-operator.v0.0.5-next" to reach 'Succeeded' phase 
INFO[0021]   Waiting for ClusterServiceVersion "istio-workspace-operator/istio-workspace-operator.v0.0.5-next" to appear 
INFO[0038]   Found ClusterServiceVersion "istio-workspace-operator/istio-workspace-operator.v0.0.5-next" phase: Pending 
INFO[0040]   Found ClusterServiceVersion "istio-workspace-operator/istio-workspace-operator.v0.0.5-next" phase: Installing 
INFO[0065]   Found ClusterServiceVersion "istio-workspace-operator/istio-workspace-operator.v0.0.5-next" phase: Succeeded 
INFO[0065] OLM has successfully installed "istio-workspace-operator.v0.0.5-next" 
```

#### What did you see instead? Under which circumstances?

Attempting to use operator-sdk run bundle for testing purposes of the install modes.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

#### Possible Solution

```diff
diff --git a/internal/olm/operator/registry/operator_installer.go b/internal/olm/operator/registry/operator_installer.go
index 882a5a19..faadbcb7 100644
--- a/internal/olm/operator/registry/operator_installer.go
+++ b/internal/olm/operator/registry/operator_installer.go
@@ -375,6 +375,8 @@ func (o *OperatorInstaller) getTargetNamespaces(supported sets.String) ([]string
                return []string{o.cfg.Namespace}, nil
        case supported.Has(string(v1alpha1.InstallModeTypeSingleNamespace)):
                return o.InstallMode.TargetNamespaces, nil
+       case supported.Has(string(v1alpha1.InstallModeTypeMultiNamespace)):
+               return o.InstallMode.TargetNamespaces, nil
        default:
                return nil, fmt.Errorf("no supported install modes")
        }
```

#### Additional context

A PullRequest with tests in the works, unless I'm missing some reason why this is not supported to begin with. With the patch above the operator seems to install just fine.

### PR DESCRIPTION
**Pull request by aslakknutsen**
Fixes `no supported install modes` error when installing Operators
in install mode MultiNamespace via
`operator-sdk run bundle --install-mode MultiNamespace=x,y`

Closes #4512

### CODE REVIEW

File: internal/olm/operator/registry/operator_installer.go [hunk 1]
```diff
@@ -375,6 +375,8 @@ func (o *OperatorInstaller) getTargetNamespaces(supported sets.String) ([]string
 		return []string{o.cfg.Namespace}, nil
 	case supported.Has(string(v1alpha1.InstallModeTypeSingleNamespace)):
 		return o.InstallMode.TargetNamespaces, nil
+	case supported.Has(string(v1alpha1.InstallModeTypeMultiNamespace)):
+		return o.InstallMode.TargetNamespaces, nil
```
Comment (rashmigottipati) [inline internal/olm/operator/registry/operator_installer.go:379]: Suggestion: Can you please log a warning message here that MultiNamespace is being used, before returning the InstallMode.

**Review by rashmigottipati — COMMENTED** [review]
@aslakknutsen thank you for your contribution to Operator SDK. :+1:

By design, we have intentionally not supported MultiNamespace because it is error-prone and it will be deprecated or removed altogether in the future. Supporting this would be fine for now, so this PR can be approved after adding the warning log message.

**Comment by aslakknutsen** [comment]
@rashmigottipati Ah right. I was reading something about that in an issue opened by someone, but it seemed at least at that time that the developers were stating otherwise. But ok. It's there now so :)

File: internal/olm/operator/registry/operator_installer.go [hunk 2]
```diff
@@ -375,6 +375,9 @@ func (o *OperatorInstaller) getTargetNamespaces(supported sets.String) ([]string
 		return []string{o.cfg.Namespace}, nil
 	case supported.Has(string(v1alpha1.InstallModeTypeSingleNamespace)):
 		return o.InstallMode.TargetNamespaces, nil
+	case supported.Has(string(v1alpha1.InstallModeTypeMultiNamespace)):
+		log.Warn("MultiNamespace is being used for the InstallMode")
```
Comment (estroz) [inline internal/olm/operator/registry/operator_installer.go:379]:
```suggestion
		log.Warn("The selected install mode MultiNamespace may cause tenancy issues and is not recommended")
```

**Comment by estroz** [comment]
@aslakknutsen can you add the [developer certificate of origin](https://probot.github.io/apps/dco/) to both your PR description too? Thanks!

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
For posterity: I'm fine with not adding a changelog for this mode because we don't recommend using it.
