### PR TITLE
deps: bump to k8s v1.17

### LINKED ISSUE #2030: Drop dependency on k8s.io/kubernetes
Kubernetes intentionally ships a broken go.mod file to discourage people from depending on k8s.io/kubernetes (see kubernetes/kubernetes#79384). As a result, in order to depend on operator-sdk, we must go through major hacks to get go modules working.

Is it feasible to drop this dependency?

kubernetes/kubernetes#79384 (comment) indicates it may be possible to move the controller library out of k8s.io/kubernetes, and I think the only other usage is kubectl which can already use k8s.io/api and k8s.io/kubectl

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
* bump all deps to their k8s v1.17 equivalents; various code/doc updates from broken API's.
* bundle create: fix issue where manifests/ is expected by the operator-registry image builder but not generated by the SDK. In case deploy/olm-catalog/<operator-name>/manifests doesn't exist, create one and delete it after the image is done building. If --generate-only is set, do not remove manifests/. Also add tests

**Motivation for the change:** support new(er) version of k8s

Supercedes #2715, #2702 
Fixes #2030

/area dependency

### CODE REVIEW

File: cmd/operator-sdk/bundle/create.go [hunk 1]
```diff
@@ -15,116 +15,320 @@
...
+// a manifest/, metadata/ or bundle.DockerFile do not exist, they are removed.
+func (c bundleCreateCmd) runBuild() error {
+	rootDir := filepath.Dir(c.directory)
+	metadataDir := filepath.Join(rootDir, bundle.MetadataDir)
+	manifestsDir := filepath.Join(rootDir, bundle.ManifestsDir)
+
+	// Clean up transient files once the image is built, as they are no longer
+	// needed.
+	if !isExist(manifestsDir) {
+		defer makeRmFunc(manifestsDir)()
```
Comment (joelanford) [inline cmd/operator-sdk/bundle/create.go]: Is there a reason we need to return a function and call it, rather than just defering a function directly? e.g.

`defer remove(manifestsDir)`

File: go.mod [hunk 2]
```diff
@@ -3,88 +3,63 @@ module github.com/operator-framework/operator-sdk
...
-	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20191016114939-2b2b218dc1df
-	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
-	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
-	k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
-	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
-	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
-	k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
-	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
+	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
+	k8s.io/client-go => k8s.io/client-go v0.0.0-20191016111102-bec269661e48 // Required by prometheus-operator
```
Comment (joelanford) [inline go.mod]: Can client-go be pinned to `v0.17.4`? Or would that cause the prometheus-operator dependency not to compile correctly?

File: internal/scaffold/ansible/go_mod.go [hunk 3]
```diff
@@ -43,36 +43,14 @@ go 1.13
...
-	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.0.0-20191016112429-9587704a8ad4
-	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20191016114939-2b2b218dc1df
-	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
-	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
-	k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
-	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
-	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
-	k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
-	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
+	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d // Required by Helm
```
Comment (joelanford) [inline internal/scaffold/ansible/go_mod.go]: This is required here, but no in the main `go.mod` for the SDK repo?

File: internal/scorecard/plugins/plugin_runner.go [hunk 4]
```diff
@@ -298,16 +293,8 @@ func getCSV(csvManifest string, csv *olmapiv1alpha1.ClusterServiceVersion) error
...
-	if err != nil {
-		return "", err
-	}
-	stratDep, ok := strategy.(*olminstall.StrategyDetailsDeployment)
-	if !ok {
-		return "", fmt.Errorf("expected StrategyDetailsDeployment, got strategy of type %T", strategy)
-	}
-	return stratDep.DeploymentSpecs[0].Name, nil
+func getDeploymentName(strategy olmapiv1alpha1.NamedInstallStrategy) string {
+	return strategy.StrategySpec.DeploymentSpecs[0].Name
```
Comment (joelanford) [inline internal/scorecard/plugins/plugin_runner.go]: Seems possible for this to panic if there are no `DeploymentSpecs`.

File: internal/scaffold/olm-catalog/csv_test.go [hunk 5]
```diff
@@ -145,16 +144,8 @@ func TestUpdateVersion(t *testing.T) {
...
-	if err != nil {
-		t.Fatal(err)
-	}
-	strategy, ok := strategyInterface.(*olminstall.StrategyDetailsDeployment)
-	if !ok {
-		t.Fatalf("Strategy of type %T was not StrategyDetailsDeployment", strategyInterface)
-	}
-	csvPodImage := strategy.DeploymentSpecs[0].Spec.Template.Spec.Containers[0].Image
+	csvDepSpecs := csv.Spec.InstallStrategy.StrategySpec.DeploymentSpecs
+	csvPodImage := csvDepSpecs[0].Spec.Template.Spec.Containers[0].Image
```
Comment (joelanford) [inline internal/scaffold/olm-catalog/csv_test.go]: Can this panic? While unlikely, it is theoretically possible for there to be no `Containers`, right?

File: cmd/operator-sdk/bundle/create.go (hunk 1 above)
Comment (estroz) [reply cmd/operator-sdk/bundle/create.go]: Nope, just a forgotten remnant of refactoring.

File: go.mod (hunk 2 above)
Comment (estroz) [reply go.mod]: This can be pinned, must have lost this change in a rebase.

File: internal/scaffold/ansible/go_mod.go (hunk 3 above)
Comment (estroz) [reply internal/scaffold/ansible/go_mod.go]: Apparently not anywhere, just checked.

File: test/test-framework/go.mod [hunk 6]
```diff
@@ -5,39 +5,15 @@ go 1.13
...
-	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
-	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
-	k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
-	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
-	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
-	k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
-	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
+	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
+	k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
 )
```
Comment (camilamacedo86) [inline test/test-framework/go.mod]: 👍 it will work here 
We need to do after a follow-up PR to do the same in the go mods.

File: website/content/en/docs/migration/version-upgrade-guide.md [hunk 7]
```diff
@@ -1058,6 +1058,26 @@ RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
...
+```
+require (
+	github.com/operator-framework/operator-sdk master
+	sigs.k8s.io/controller-runtime v0.5.2
+)
+
+replace (
+  k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
+	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
+)
```
Comment (camilamacedo86) [inline website/content/en/docs/migration/version-upgrade-guide.md]: space indentation.

File: internal/scaffold/ansible/go_mod.go [hunk 8]
```diff
@@ -43,36 +43,13 @@ go 1.13
...
-	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20191016114939-2b2b218dc1df
-	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
-	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
-	k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
-	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
-	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
-	k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
-	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
+	k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
+	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
```
Comment (camilamacedo86) [inline internal/scaffold/ansible/go_mod.go]: I am not sure if we can remove the replaces in the PR. 
See that if we run make install and then create a new project:

I```
NFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: github.com/operator-framework/operator-sdk@v0.16.1-0.20200331094118-c97e53b9e138 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
FATA[0034] failed to exec []string{"go", "build", "./..."}: exit status 1 
```

I understand it is because locally it will looking for the master. 
However, if pass in the CI shows fine. So, is the CI looking for the changes here made in the source code as well?

File: internal/scaffold/go_mod.go [hunk 9]
```diff
@@ -42,36 +42,13 @@ go 1.13
...
-	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
-	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
-	k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
-	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
-	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
-	k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
-	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
+	k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
+	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
 )
```
Comment (camilamacedo86) [inline internal/scaffold/go_mod.go]: Hi @joelanford and @estroz, 
 
I am not sure if we can remove the replaces in this PR. 
See that if we run `make install` and then, create a new project:

```
NFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: github.com/operator-framework/operator-sdk@v0.16.1-0.20200331094118-c97e53b9e138 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
FATA[0034] failed to exec []string{"go", "build", "./..."}: exit status 1 
```

I understand it is because locally it will looking for the SDK master. 
However, if pass in the CI shows fine. Is the CI looking for the SDK image built from the source code? Are we testing its scaffold on it?

File: go.mod [hunk 10]
```diff
@@ -3,88 +3,63 @@ module github.com/operator-framework/operator-sdk
...
 	github.com/rubenv/sql-migrate v0.0.0-20191025130928-9355dd04f4b3 // indirect
 	github.com/sergi/go-diff v1.0.0
-	github.com/sirupsen/logrus v1.4.2
+	github.com/sirupsen/logrus v1.5.0
 	github.com/spf13/afero v1.2.2
 	github.com/spf13/cobra v0.0.5
 	github.com/spf13/pflag v1.0.5
 	github.com/spf13/viper v1.4.0
 	github.com/stretchr/testify v1.4.0
 	github.com/ziutek/mymysql v1.5.4 // indirect
```
Comment (camilamacedo86) [inline go.mod]:
```suggestion
	github.com/yvasiyarov/go-metrics v0.0.0-20150112132944-c25f46c4b940 // indirect
```
The above indirect module needs to be in the go.mod, otherwise it will get stuck when we run `go mo tidy`

Screenshot 2020-03-31 at 11 57 27

c/c @joelanford @estroz

Comment (estroz) [reply go.mod]: I haven't seen this issue locally or in CI. Have you tried clearing your modcache?

File: internal/scaffold/go_mod.go (hunk 9 above)
Comment (joelanford) [reply internal/scaffold/go_mod.go]: Yeah, the e2e tests add a `replace` to the scaffolded go.mod (e.g. [for the go operator](https://github.com/operator-framework/operator-sdk/blob/c97e53b9e138540690324c0341d43933a3d7e711/hack/tests/scaffolding/scaffold-memcached.go#L76-L80)) to make sure that the branch code is being tested instead of `master`.

File: go.mod (hunk 10 above)
Comment (camilamacedo86) [reply go.mod]: You are right the clean cache fixed that 👍 
Solved.

File: website/content/en/docs/migration/version-upgrade-guide.md [hunk 11]
```diff
@@ -1058,6 +1058,26 @@ RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
...
+- Ensure that the following `require` modules and `replace` directives with the specific versions are present in your `go.mod` file:
+
+```
+require (
+	github.com/operator-framework/operator-sdk master
+	sigs.k8s.io/controller-runtime v0.5.2
+)
+
+replace (
+  k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
```
Comment (camilamacedo86) [inline website/content/en/docs/migration/version-upgrade-guide.md]:
```suggestion
	k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
```

Comment (camilamacedo86) [reply website/content/en/docs/migration/version-upgrade-guide.md]: Solved

File: hack/tests/subcommand-bundle.sh [hunk 12]
```diff
@@ -0,0 +1,149 @@
...
+      error_text "${1}: file ${2} should not exist"
+      exit 1
+    fi
+  else
+    if [[ ! -f "$2" ]]; then
+      error_text "${1}: file ${2} should exist"
+      exit 1
+    fi
+  fi
+}
```
Comment (joelanford) [inline hack/tests/subcommand-bundle.sh]: Nit: move these to `test_lib.sh`?

Comment (estroz) [reply hack/tests/subcommand-bundle.sh]: Will do that in #2737 when I add validate tests.
