### PR TITLE
Properly handle resources with '-' in the group name

### LINKED ISSUE #2486: Resources that use `-` in the API group name can't be directly accessed by ansible
## Bug Report

**What did you do?**
Resource with, e.g.,:
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
```
Accessing the resource or resource spec as a variable fails.

**What did you expect to see?**
Accessing the variable should work, i.e.:
```
foo: "{{ _cert-manager_io_certificaterequest }}"
```

**What did you see instead? Under which circumstances?**
The variable name is truncated at the `-`, and ansible throws an undefined variable exception:
```
The task includes an option with an undefined variable. The error was: '_cert' is undefined
```

**Environment**
* operator-sdk version:

operator-sdk version: "v0.15.0", commit: "21a93ca379b887ab2303b0d148a399bf205c3231", go version: "go1.13.6 darwin/amd64"

* go version:

go version go1.13.6 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Single node.  Docker Desktop w/ Kubernetes

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**

The resource can be accessed through the array accessor, e.g.:
```
foo: vars["_cert-manager_io_certificaterequest"]
```
**Additional context**
While `-` is not valid in a JSON variable, it is valid in a JSON key name.  However, it will get parsed as a subtraction operation.

### PR DESCRIPTION
**Pull request by fabianvf**
Resources with '-' in the APIGroup now are properly formatted when
passed to Ansible. For example

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
```

will now result in a variabled called
`_cert_manager_io_certificaterequest`
instead of
`_cert-manager_io_certificaterequest`

Fixes #2486

**Description of the change:**

**Motivation for the change:**

### CODE REVIEW

File: pkg/ansible/runner/runner.go [hunk 1]
```diff
@@ -310,7 +310,7 @@ func (r *runner) makeParameters(u *unstructured.Unstructured) map[string]interfa
 	parameters := paramconv.MapToSnake(spec)
 	parameters["meta"] = map[string]string{"namespace": u.GetNamespace(), "name": u.GetName()}
 
-	objKey := fmt.Sprintf("_%v_%v", strings.Replace(r.GVK.Group, ".", "_", -1),
+	objKey := fmt.Sprintf("_%v_%v", strings.ReplaceAll(strings.ReplaceAll(r.GVK.Group, ".", "_"), "-", "_"),
```
Comment (jmrodri) [inline pkg/ansible/runner/runner.go]: could you put a comment above this line? maybe even including an example. And what david said about the test would be nice.

Comment (estroz) [reply pkg/ansible/runner/runner.go]: Are `.` and `-` the only characters than need replacing? Regardless this might be easier to read as a regexp and `re.ReplaceAllString`.

Comment (fabianvf) [reply pkg/ansible/runner/runner.go]: broke it out into a function which should be more clear. It should be easy to add more characters if needed, as well as reusing it on additional parameters in the future if that ever becomes a concern (might be worth looking into whether we need to do that, but wanted to keep scope here relatively limited)
