### PR TITLE
[fix]: include filename in the error returned by generate-csv command

### LINKED ISSUE #2583: csv generation ends in an unclear error
## Bug Report

**What did you do?**
operator-sdk generate csv --csv-channel alpha --default-channel --csv-version 0.0.1 --update-crds

**What did you expect to see?**
Complete CSV generation without errors 

**What did you see instead? Under which circumstances?**
INFO[0000] Generating CSV manifest version 0.0.1
INFO[0000] No TypeMeta in deploy/crds/cms.solute.us_syncs_crd.yaml, skipping file
INFO[0000] Skipping manifest cms.solute.us/v1beta1, Kind=Sync
INFO[0000] Created deploy/olm-catalog/sync-operator/0.0.1/sync-operator.v0.0.1.clusterserviceversion.yaml
FATA[0000] error getting TypeMeta from bytes: error converting YAML to JSON: yaml: line 23: mapping values are not allowed in this context

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

**Possible Solution**
If this is related to the CSV that is generated, line 23 is `strategy: {}` under spec.install.spec.deployments.spec. which I believe is a default value. 

If this is related to the CRD, line 23 is spec.validation.openAPIv3schema.description's apiVersion. It has description and type: string under it. 

**Additional context**
I have the openAPI validation stuff in the CRD so am wondering if that is related, but if I remove the entire validation section, it still shows this error.

### PR DESCRIPTION
**Pull request by varshaprasad96**
**Description of the change:**
Modify error message by including the file path.

**Motivation for the change:**
 Currently, if there is error during unmarshalling of crds in the
deploy/crds folder, the error returned by generate-csv command
is unclear as it does not include any filename. This PR modifies
the error message to include the filepath.

### CODE REVIEW

File: cmd/operator-sdk/generate/csv.go [hunk 1]
```diff
@@ -199,7 +199,7 @@ func writeCRDsToDir(crdPaths []string, toDir string) error {
 		}
 		typeMeta, err := k8sutil.GetTypeMetaFromBytes(b)
 		if err != nil {
-			return err
+			return fmt.Errorf("Error in %s : %v", p, err)
```
Comment (camilamacedo86) [inline cmd/operator-sdk/generate/csv.go]:
```suggestion
			return fmt.Errorf("error in %s : %v", p, err)
```

**Comment by camilamacedo86** [comment]
I found the issue :-) 
If you add in the first comment:

Closes: #<numberissue>

In this case:

Closes: #2583

Then, when the PR is merged the issue will be closed automatically.

File: cmd/operator-sdk/generate/csv.go (hunk 1 above)
Comment (varshaprasad96) [reply cmd/operator-sdk/generate/csv.go]: Thanks @camilamacedo86. I'll follow the same process in future to link the bugs.
