### PR TITLE
fix: (ansible) - Errors in the event have not been re-trigging the reconcile. 

### LINKED ISSUE #2372: Ansible operator does not trigger reconcile loops after ansible failure
## Bug Report

**What did you do?**
I created a hello-world style ansible operator, which does nothing but failing the play with ansible's `fail` task.
I deployed the Operator, CRD and Custom Resource.

**What did you expect to see?**
I expect to see the operator firing consecutive reconcile loops with exponential back-off.

**What did you see instead? Under which circumstances?**
The operator failed once and did no further reconciles.

**Environment**
* operator-sdk version: 

v0.13.0

* go version:

Uses docker image from v0.13.0 operator SDK, did not test on the host

* Kubernetes version information:

Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+70132b0f13", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Minikube

* Are you writing your operator in ansible, helm, or go?

Ansible

**Additional context**
This was also discussed in #2198 
cc @fabianvf  @camilamacedo86 

here is the repository containing the PoC i used: https://github.com/glothriel/testoperator

I did:
```
kubectl apply -f deploy/crds/glothriel.com_testcrs_crd.yaml 
kubectl apply -f deploy/
...waited till operator is running...
kubectl apply -f deploy/crds/glothriel.com_v1alpha1_testcr_cr.yaml
kubectl logs testoperator-79cb78ddfd-jpkc6 ansible -f 
```

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Fix issue: https://github.com/operator-framework/operator-sdk/issues/2372
Errors in the event have not been re-trigging the reconcile. 

**Motivation for the change:**
Closes #2372

**Notes**
Local tests to verify it can be done with the image: `quay.io/camilamacedo86/ansible-operator:dev`
The user POC in the #2372 was used to check.

### CODE REVIEW

File: pkg/ansible/controller/reconcile.go [hunk 1]
```diff
@@ -183,7 +182,8 @@ func (r *AnsibleOperatorReconciler) Reconcile(request reconcile.Request) (reconc
 			}
 		}
 		if event.Event == eventapi.EventRunnerOnFailed && !event.IgnoreError() {
-			failureMessages = append(failureMessages, event.GetFailedPlaybookMessage())
+			eventErr := errors.New("event runner on failed")
+			return reconcile.Result{}, eventErr
```
Comment (fabianvf) [inline pkg/ansible/controller/reconcile.go]: I think we still want the markDone function to be called in this case (if status management is enabled), that's what puts the failure message in the status reflects that a run did not succeed. We should do this even if we requeue after

Comment (fabianvf) [reply pkg/ansible/controller/reconcile.go]: https://github.com/operator-framework/operator-sdk/pull/2375/files#diff-9649888b3df1961dad649345545de4c0R304

Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: Thank you for your review @fabianvf. 
Done. Wdyt now?

File: pkg/ansible/controller/reconcile.go [hunk 2]
```diff
@@ -183,7 +182,20 @@ func (r *AnsibleOperatorReconciler) Reconcile(request reconcile.Request) (reconc
 			}
 		}
 		if event.Event == eventapi.EventRunnerOnFailed && !event.IgnoreError() {
+			eventErr := errors.New("event runner on failed")
+			failureMessages := eventapi.FailureMessages{}
```
Comment (shawn-hurley) [inline pkg/ansible/controller/reconcile.go]: I am pretty sure this will eat ignored failures

**Comment by shawn-hurley** [comment]
I think that this will break the existing functionality that users are relying on. 

A task can choose to ignore the error and continue on, in that case, we need to show all the errors that could have occurred, requeue, mark the appropriate condition.

File: pkg/ansible/controller/reconcile.go (hunk 2 above)
Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: Hi @shamsher31 and @fabianvf, 
 
Should we mark all errors and just retrigger the reconcile if `!event.IgnoreError()` ? Is that the expected behaviour?

Comment (fabianvf) [reply pkg/ansible/controller/reconcile.go]: I think we shouldn't break the loop here actually, we should wait until all events are processed before we determine whether the run is successful or failed. We can probably just add a check after we determine if the run is successful, and add `Requeue: True` to reconcileResult if it was not. We would just need to add this line back and add a check right after, since all the returns after that return `reconcileResult` I think that should do it https://github.com/operator-framework/operator-sdk/pull/2375/files#diff-9649888b3df1961dad649345545de4c0L215

Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: Make sense. Now I got why it was using the msg var before. I will change it now.

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley it was changed could you please give a look and see if it is ok for you now?

File: pkg/ansible/controller/reconcile.go [hunk 3]
```diff
@@ -183,7 +183,12 @@ func (r *AnsibleOperatorReconciler) Reconcile(request reconcile.Request) (reconc
 			}
 		}
 		if event.Event == eventapi.EventRunnerOnFailed && !event.IgnoreError() {
-			failureMessages = append(failureMessages, event.GetFailedPlaybookMessage())
+			if len(event.GetFailedPlaybookMessage()) < 1 {
```
Comment (fabianvf) [inline pkg/ansible/controller/reconcile.go]: I'm not sure I follow what this block is doing, are we actually hitting this branch and if so does it matter if `event.GetFailedPlaybookMessage()` is `""`?

File: pkg/ansible/controller/reconcile.go [hunk 4]
```diff
@@ -235,6 +241,11 @@ func (r *AnsibleOperatorReconciler) Reconcile(request reconcile.Request) (reconc
 		}
 		return reconcileResult, errmark
 	}
+
+	// re-trigger reconcile because of failures
+	if !runSuccessful {
```
Comment (fabianvf) [inline pkg/ansible/controller/reconcile.go]: I don't think this will requeue if we are managing status, I think if we just set the `reconcileResult.Requeue` to true up at https://github.com/operator-framework/operator-sdk/pull/2375/files#diff-9649888b3df1961dad649345545de4c0R221 then it should requeue in all cases, unless it's specifically important that we return an error, in which case we'll just need to make sure we do that in the managed status case as well

https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Result

File: pkg/ansible/controller/reconcile.go (hunk 3 above)
Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: Yes, it matters.
If the event.GetFailedPlaybookMessage() is "" then, `runSuccessful := len(failureMessages) == 0` besides has an error.

Comment (fabianvf) [reply pkg/ansible/controller/reconcile.go]: that's strange, wouldn't failure messages then be `[]string{""}`, which should still have a length of 1 (https://play.golang.org/p/ZcvpUbPIMct)?

File: pkg/ansible/controller/reconcile.go (hunk 4 above)
Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: Solved 👍 Good spot tks.

File: pkg/ansible/controller/reconcile.go (hunk 3 above)
Comment (camilamacedo86) [reply pkg/ansible/controller/reconcile.go]: You are right `runSuccessful := len(failureMessages) == 0` will work well since it will be 1 in the scenario of "". However, it will have no msg. Because of this, I added it.
