### PR TITLE
manifest generation: remove `metadata.namespace` from manifests

### LINKED ISSUE #3809: Operator SDK 1.0.0 - explicit service account for operator causes bundle build to fail
Setup:
```
$ operator-sdk version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"

$ cd $(mktemp -d)
```
From the quick start:
```
$ operator-sdk init\
 --domain abcde.net\
 --project-name foo-project\
 --repo github.com/example-inc/memcached-operator

$ operator-sdk create api --group=qqqqq --version=v1alpha1 --kind=Zzzzz --resource=true --controller=true --namespaced=false

$ make install
```
I don't want my operator to run under the `default` service account so add a service account:
```
$ cat <<EOF > config/manager/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
EOF
$ sed -i '/^- manager.yaml/a - service_account.yaml' config/manager/kustomization.yaml
```
Note - there are other  patches required but not relevant to this issue.

Next:
```
$ make bundle
/home/eace/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
operator-sdk generate kustomize manifests -q
cd config/manager && /home/eace/go/bin/kustomize edit set image controller=controller:latest
/home/eace/go/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
INFO[0000] Building annotations.yaml                    
INFO[0000] Writing annotations.yaml in /tmp/tmp.4rzP8jfjfk/bundle/metadata 
INFO[0000] Building Dockerfile                          
INFO[0000] Writing bundle.Dockerfile in /tmp/tmp.4rzP8jfjfk 
operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] Error: Value foo-project-manager: error validating object: metadata.namespace: Forbidden: not allowed on this type. &{map[apiVersion:v1 kind:ServiceAccount metadata:map[creationTimestamp:<nil> name:foo-project-manager namespace:foo-project-system]]} 
Makefile:112: recipe for target 'bundle' failed
make: *** [bundle] Error 1
```

With the new 1.0.0 scaffolding - what is the intended approach to have an operator run under its own service account?

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
When generating bundles and packagemanifests, remove `metadata.namespace` from namespaced resources when writing them into the `manifests` directory to avoid validation errors.

OLM installs namespaced manifests in the namespace that the operator is installed, so it is invalid to hardcode a specific namespace in these manifests.

**Motivation for the change:**
Closes #3809

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] ~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~

### CODE REVIEW

**Comment by estroz** [comment]
@joelanford do you know which validator is returning this error? Also I’m not sure why this is a requirement at all. Much like for a CSV, OLM should be able to substitute whatever namespace it wants into a bundled manifest regardless of whether one is set or not. Is this so operator authors won’t get the idea that their object will be installed into the namespace specified in the manifest?

@dinhxuanvu @gallettilance thoughts on this?

Relates to #3748.

**Comment by joelanford** [comment]
/hold

For discussion about whether this validator is appropriate (and if it is, I want to add some unit tests to prevent regressions)

**Comment by estroz** [comment]
From @dinhxuanvu:

>If non-CSV manifests (such as CRD) have namespace information, they will fail validation. It is "kubectlable" validation. OLM will overwrite namespace info so you shouldn't include namespace info by default given it won't be honored

File: internal/generate/collector/manifests.go [hunk 1]
```diff
@@ -212,6 +212,7 @@ func (c *Manifests) addRoles(rawManifests ...[]byte) error {
 		if err := yaml.Unmarshal(rawManifest, &role); err != nil {
 			return err
 		}
+		role.SetNamespace("")
```
Comment (estroz) [inline internal/generate/collector/manifests.go:215]: It would be easier to just remove an object's namespace before [writing it](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/operator-sdk/generate/internal/genutil.go#L90).

Comment (joelanford) [reply internal/generate/collector/manifests.go:215]: Hmm, the package and naming of `WriteObjectsToFiles` makes me hesitate a little putting this logic there since it seems like a very general-purpose and obvious function. I interpret it as "please serialize these objects directly to files".

WDYT of removing the namespace of all objects just before they're passed into this function and only when we're using it in the context of writing a manifests directory?

Comment (joelanford) [reply internal/generate/collector/manifests.go:215]: Actually, how about [here](https://github.com/operator-framework/operator-sdk/blob/497b7f8ce68cd4d8f1fdd4a70f9cd78f80149654/internal/cmd/operator-sdk/generate/internal/manifests.go#L23-L45)?

Comment (estroz) [reply internal/generate/collector/manifests.go:215]: :+1: to your last comment.
