### PR TITLE
cmd/operator-sdk/run: use Windows binary suffix with '--local'

### LINKED ISSUE #2480: On Windows, operator-sdk run --local doesn't work.
## Bug Report

**What did you do?**
I'm trying to use operator-sdk on Windows. After fixing a bug in Go itself that stops this from working correctly, I tried to do a "make local".

**What did you expect to see?**
The "make local" built everything, then failed because the name of the file it had built was "my-operator" rather than "my-operator.exe".

**What did you see instead? Under which circumstances?**
It should work just the same as it does on Linux/macOS.

**Environment**
* operator-sdk version: 87787d1

* go version: `go version go1.13.7 windows/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: various

* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**
Fix `cmd/operator-sdk/run/local.go` so that it appends `.exe` to `outputBinName` on Windows.

**Additional context**
You need a fix for [gengo issue #166](https://github.com/kubernetes/gengo/issues/166) before any of this will work; otherwise the `operator-sdk generate k8s` step will generate files in the wrong place.

### PR DESCRIPTION
**Pull request by al45tair**
On Windows, we need to add the .exe suffix to the executable that is
generated by the operator-sdk run --local command, otherwise it will
fail because the file doesn't have an executable extension.

Closes #2480

### CODE REVIEW

File: cmd/operator-sdk/run/local.go [hunk 1]
```diff
@@ -75,7 +76,11 @@ func (c runLocalArgs) runGo() error {
 	projutil.MustInProjectRoot()
 	absProjectPath := projutil.MustGetwd()
 	projectName := filepath.Base(absProjectPath)
-	outputBinName := filepath.Join(scaffold.BuildBinDir, projectName+"-local")
+	var exeSuffix string
+	if runtime.GOOS == "windows" {
+		exeSuffix = ".exe"
+	}
+	outputBinName := filepath.Join(scaffold.BuildBinDir, projectName+"-local"+exeSuffix)
```
Comment (joelanford) [inline cmd/operator-sdk/run/local.go]: This change will fix the specific problem with `run --local`, but under the hood, we use the `projutil.GoBuild()` helper.

I think a better change would be to update the underlying build helper so that it always appends `.exe` when on Windows (and the bin name doesn't already have that suffix). That way we don't accidentally miss this in other places that use use `projutil.GoBuild()`

WDYT of the following instead?
```diff
diff --git a/internal/util/projutil/exec.go b/internal/util/projutil/exec.go
index 7853da76..03ba73ca 100644
--- a/internal/util/projutil/exec.go
+++ b/internal/util/projutil/exec.go
@@ -19,6 +19,7 @@ import (
        "os"
        "os/exec"
        "path/filepath"
+       "runtime"
        "strings"
 
        log "github.com/sirupsen/logrus"
@@ -111,6 +112,9 @@ func (opts GoCmdOptions) getGeneralArgsWithCmd(cmd string) ([]string, error) {
        }
 
        if opts.BinName != "" {
+               if runtime.GOOS == "windows" && !strings.HasSuffix(opts.BinName, ".exe") {
+                       opts.BinName += ".exe"
+               }
                bargs = append(bargs, "-o", opts.BinName)
        }
        bargs = append(bargs, opts.Args...)
```

Comment (joelanford) [reply cmd/operator-sdk/run/local.go]: Actually, maybe we _don't_ want to do what I just suggested :stuck_out_tongue_closed_eyes:

In the `operator-sdk build` case, we build a Go binary and then copy it into a Linux container. So perhaps the `run --local` case is the only one where we want to add `.exe`

/cc @estroz @hasbro17 Bouncing this off you to check my thinking.

File: cmd/operator-sdk/run/local.go [hunk 2]
```diff
@@ -75,7 +76,11 @@ func (c runLocalArgs) runGo() error {
...
 	if err := c.buildLocal(outputBinName); err != nil {
 		return fmt.Errorf("failed to build operator to run locally: %v", err)
```
Comment (camilamacedo86) [inline cmd/operator-sdk/run/local.go]: WDYT about we take this opportunity to add a few tests in the Travis for win platform as well?
@al45tair it is not a blocker to merge this PR, but in POV would be great if you see that it could be added without too much effort. 
@joelanford @estroz

Comment (joelanford) [reply cmd/operator-sdk/run/local.go]: @camilamacedo86 I don't think we have _any_ tests around `run --local` or _any_ tests for Windows (correct me if I'm wrong). If not, I think it would be okay for this to merge without tests and for us to take an action to look into those things on the macro level.

Comment (camilamacedo86) [reply cmd/operator-sdk/run/local.go]: Yes, we have not. I agree with you.

File: cmd/operator-sdk/run/local.go (hunk 1 above)
Comment (al45tair) [reply cmd/operator-sdk/run/local.go]: Yes, this is specific to `run --local` for the reason you give; operators *normally* run in a Linux environment, not on Windows, so I think making the change you suggest would break other things.

Comment (joelanford) [inline cmd/operator-sdk/run/local.go]: Just a nit to remove the need for the `exeSuffix` variable:

```
outputBinName := filepath.Join(scaffold.BuildBinDir, projectName+"-local")
if runtime.GOOS == "windows" {
	outputBinName += ".exe"
}

Comment (camilamacedo86) [reply cmd/operator-sdk/run/local.go]: Hi @al45tair, 

Could you please check the above nit? I think it is missing just this detail.

Comment (al45tair) [reply cmd/operator-sdk/run/local.go]: I'll update the pull request tomorrow. Amusingly I originally wrote it the way @joelanford suggests, but changed my mind because it seemed cleaner to build the complete path element and then `filepath.Join()` *that*. But you're right, the cost is that we need a variable.

**Comment by al45tair** [comment]
Hmmm. That test failure doesn't seem to be my doing.

File: cmd/operator-sdk/run/local.go (hunk 1 above)
Comment (al45tair) [reply cmd/operator-sdk/run/local.go]: I've updated the pull request, but there's a test failure that I don't think is anything to do with this change.

Comment (camilamacedo86) [reply cmd/operator-sdk/run/local.go]: I just restarted. We need to try to upgrade the marker to see if this problem is solved. It has been failing somethings and the current workaround is just to re-start it.

File: CHANGELOG.md [hunk 3]
```diff
@@ -12,6 +12,7 @@
 
 - Fixed issue with Go dependencies caused by removed tag in `openshift/api` repository ([#2466](https://github.com/operator-framework/operator-sdk/issues/2466))
 - Fixed a regression in the `operator-sdk run` command that caused `--local` flags to be ignored ([#2478](https://github.com/operator-framework/operator-sdk/issues/2478))
+- Fix command `operator-sdk run --local` which was not working on Windows. #2481
```
Comment (camilamacedo86) [inline CHANGELOG.md]: We need to add the link as it is in the others,
```suggestion
- Fix command `operator-sdk run --local` which was not working on Windows. ([#2481](https://github.com/operator-framework/operator-sdk/pull/2481))
```
