### PR TITLE
Closes #4446: Logging to Stdout based on verbosity

### LINKED ISSUE #4446: Ansible-based operator logging verbosity flags don't affect events written to stdout
## Bug Report

I'm attempting to lower the log level of my ansible-based operator for every day use. Logs are collected from stdout of the operator pod. 
I would also like to be able to increase log levels for investigation when there's an issue.

#### What did you do?

I followed the guidelines for adjusting log levels [here](https://v0-19-x.sdk.operatorframework.io/docs/ansible/reference/advanced_options/#ansible-verbosity)

Before any change I ran `ps -ef` inside the container and see the anible-runner start with command:
` /usr/bin/python3.6 /usr/local/bin/ansible-runner -vv --rotate-artifacts 20 -p /opt/ansible/playbook.yml -i ....`

With the annotation in the watched CR
```
annotations:
    "ansible.operator-sdk/verbosity": "0"
```
I see ( -vv gone from command )
` /usr/bin/python3.6 /usr/local/bin/ansible-runner --rotate-artifacts 20 -p /opt/ansible/playbook.yml -i  .....`

#### What did you expect to see?

I expect to see the log verbosity at stdout is the same as what is written to internal log files
`/tmp/ansible-operator/runner/<group>/<version>/<kind>/<namespace>/<resource>/artifacts/latest/stdout`

#### What did you see instead? Under which circumstances?

Log levels written to stdout remain at info level regardless of the annotation.
The annotation in the CR affected the verbosity of logs written to file, but not what is written to stdout.

#### Environment

**Operator type:**

 /language ansible 

**Kubernetes cluster type:**

Openshift 4.5.17

`$ operator-sdk version`

ansible-operator:v0.19.0

`$ go version` (if language is Go)

`$ kubectl version`

v1.18.3+45b9524

### PR DESCRIPTION
**Pull request by VenkatRamaraju**
**Description of the change:**
Printed log events to stdout, based on verbosity set in CR.

**Motivation for the change:**
To no longer ignore the verbosity at stdout while running Ansible-based operators, as mentioned in #4446.

### CODE REVIEW

File: internal/ansible/events/log_events.go [hunk 1]
```diff
@@ -62,22 +64,52 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
+	verbosityAnnotation := 0
+	if annot, exists := u.UnstructuredContent()["metadata"].(map[string]interface{})["annotations"]; exists {
+		if verbosityField, present := annot.(map[string]interface{})["ansible.sdk.operatorframework.io/verbosity"]; present {
+			verbosityValue, err := strconv.Atoi(verbosityField.(string))
+			if err != nil {
+				logger.Error(err, "Unable to parse verbosity value from CR.")
+			} else {
+				verbosityAnnotation = verbosityValue
+			}
+		}
```
Comment (jmrodri) [inline internal/ansible/events/log_events.go:77]:
```suggestion
	verbosityAnnotation := 0
	if annot, exists := u.UnstructuredContent()["metadata"].(map[string]interface{})["annotations"]; exists {
		if verbosityField, present := annot.(map[string]interface{})["ansible.sdk.operatorframework.io/verbosity"]; present {
			verbosityAnnotation, err := strconv.Atoi(verbosityField.(string))
			if err != nil {
				logger.Error(err, "Unable to parse verbosity value from CR.")
			}
		}
```

File: internal/ansible/events/log_events.go [hunk 2]
```diff
@@ -62,22 +64,52 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
 		setFactAction := e.EventData["task_action"] == eventapi.TaskActionSetFact
 		debugAction := e.EventData["task_action"] == eventapi.TaskActionDebug
+		verbose := verbosityAnnotation > 0 || verbosityEnvVar > 0
 
+		if verbose {
+			l.mux.Lock()
+			fmt.Println(e.StdOut)
+			l.mux.Unlock()
+			return
+		}
```
Comment (jmrodri) [inline internal/ansible/events/log_events.go:103]:
```suggestion
		if verbosityAnnotation > 0 || verbosityEnvVar > 0 {
			l.mux.Lock()
			fmt.Println(e.StdOut)
			l.mux.Unlock()
			return
		}
```

File: internal/ansible/events/log_events.go [hunk 3]
```diff
@@ -62,22 +64,52 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
 		"job", ident,
 	)
 
+	// Parse verbosity from CR
+	verbosityAnnotation := 0
+	if annot, exists := u.UnstructuredContent()["metadata"].(map[string]interface{})["annotations"]; exists {
+		if verbosityField, present := annot.(map[string]interface{})["ansible.sdk.operatorframework.io/verbosity"]; present {
```
Comment (jmrodri) [inline internal/ansible/events/log_events.go:70]: I can't remember if we need to do all the casting but it's probably the only way.

**Review by jmrodri — CHANGES_REQUESTED** [review]
A few refinements. Looks good otherwise.

File: internal/ansible/events/log_events.go (hunk 1 above)
Comment (VenkatRamaraju) [reply internal/ansible/events/log_events.go:77]: Hi @jmrodri, making those changes results in the following errors during the building of the binary:
``internal/ansible/events/log_events.go:71:4: verbosityAnnotation declared but not used``
``internal/ansible/events/log_events.go:82:3: verbosityEnvVar declared but not used``
``make: *** [install] Error 2``

I believe it's because of the redeclaration of `verbosityAnnotation` in a different scope (Line 68 and Line 71).
Perhaps I could change line 71 to an assignment instead of a declaration. The same would follow for `verbosityEnvVar`.

**Review by jmrodri — APPROVED** [review]
/lgtm

File: internal/ansible/events/log_events.go [hunk 4]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
 		"job", ident,
 	)
 
+	// Parse verbosity from CR
+	verbosityAnnotation := 0
+	if annot, exists := u.UnstructuredContent()["metadata"].(map[string]interface{})["annotations"]; exists {
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:69]: I think these are unsafe casts, we'd need something more like:

```
if metadata, ok := u.UnstructuredContent()["metadata"].(map[string]interface{}); ok {
  if annot, exists := metadata["annotations"]; exists {
...
```

otherwise we could get panics here

File: internal/ansible/events/log_events.go (hunk 3 above)
Comment (fabianvf) [reply internal/ansible/events/log_events.go:70]: same comment on unsafe casts here

File: internal/ansible/events/log_events.go [hunk 5]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
 		"job", ident,
 	)
 
+	// Parse verbosity from CR
+	verbosityAnnotation := 0
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:68]: I think it might be better to move all of these verbosity parsing blocks to a separate method, so we can just call `verbosity := getVerbosity(u)`, might make it a little more clear

File: internal/ansible/events/log_events.go [hunk 6]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
+		}
+	}
+
 	// logger only the following for the 'Tasks' LogLevel
 	t, ok := e.EventData["task"]
 	if ok {
 		setFactAction := e.EventData["task_action"] == eventapi.TaskActionSetFact
 		debugAction := e.EventData["task_action"] == eventapi.TaskActionDebug
 
+		if verbosityAnnotation > 0 || verbosityEnvVar > 0 {
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:96]: we actually want to compare the value of the verbosity (precendence, annotation > envvar) to the value that is set in the event itself

File: internal/ansible/events/log_events.go [hunk 7]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
+			l.mux.Lock()
+			fmt.Println(e.StdOut)
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:98]: I think this should probably be preceded with a little log that makes it clear this is logging ansible stdout like here https://github.com/operator-framework/operator-sdk/pull/4961/files#diff-13da9e4e392cc2d59df5cd216407c953b17acf07bc614ed04d1b9d9385c6622aR104

File: internal/ansible/events/log_events.go [hunk 8]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
 			l.mux.Lock()
 			logger.Info("[playbook task]", "EventData.Name", e.EventData["name"])
 			l.logAnsibleStdOut(e)
 			l.mux.Unlock()
 			return
 		}
-		if e.Event == eventapi.EventRunnerOnOk && debugAction {
+		if e.Event == eventapi.EventRunnerOnOk {
 			l.mux.Lock()
-			logger.Info("[playbook debug]", "EventData.TaskArgs", e.EventData["task_args"])
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:80]: maybe instead of getting rid of this we can call it `playbook task finished` or something

File: internal/ansible/events/log_events.go [hunk 9]
```diff
@@ -62,22 +64,50 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
 
+		if verbosityAnnotation > 0 || verbosityEnvVar > 0 {
+			l.mux.Lock()
+			fmt.Println(e.StdOut)
+			l.mux.Unlock()
+			return
+		}
 		if e.Event == eventapi.EventPlaybookOnTaskStart && !setFactAction && !debugAction {
 			l.mux.Lock()
 			logger.Info("[playbook task]", "EventData.Name", e.EventData["name"])
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:104]: and we could rename this one to `playbook task start`

**Review by fabianvf — CHANGES_REQUESTED** [review]

File: internal/ansible/events/log_events.go (hunk 4 above)
Comment (VenkatRamaraju) [reply internal/ansible/events/log_events.go:69]: The metadata field will exist in UnstructuredContent(), so this checks whether or not the annotations field exists.
Also, without the ``.(map[string]interface{})`` assertion, it'll error with ``invalid operation: u.UnstructuredContent()["metadata"]["annotations"] (type interface {} does not support indexing)``, so it is necessary.

File: internal/ansible/events/log_events.go [hunk 10]
```diff
@@ -62,22 +64,31 @@ func (l loggingEventHandler) Handle(ident string, u *unstructured.Unstructured,
...
 		if e.Event == eventapi.EventPlaybookOnTaskStart && !setFactAction && !debugAction {
 			l.mux.Lock()
-			logger.Info("[playbook task]", "EventData.Name", e.EventData["name"])
+			logger.Info("[playbook task start]", "EventData.Name", e.EventData["name"])
 			l.logAnsibleStdOut(e)
 			l.mux.Unlock()
 			return
 		}
-		if e.Event == eventapi.EventRunnerOnOk && debugAction {
+		if e.Event == eventapi.EventRunnerOnOk {
```
Comment (fabianvf) [inline internal/ansible/events/log_events.go:89]: let's actually leave `debugAction` in the conditional, that way if they don't set the annotation or envvar absolutely nothing changes.
