### PR TITLE
ansible molecule e2e: pin pyasn1{-modules} version, better ready check, fix e2e user setup

### LINKED ISSUE #1748: Ansible Operator scaffold tests fail with Kubernetes 1.15
## Bug Report

**What did you do?**
Updated the `image: bsycorp/kind:latest-1.15` in the `molecule.yml` file for the local test scenario.

**What did you expect to see?**
Tests should still run successfully when using Kubernetes versions newer than 1.12 (the current default version in the tests).

**What did you see instead? Under which circumstances?**
After the kind Docker image is run, the "Wait for the Kubernetes API to become available" times out and I see the message:

```
TASK [Wait for the Kubernetes API to become available (this could take a minute)] ***
FAILED - RETRYING: Wait for the Kubernetes API to become available (this could take a minute) (60 retries left).
FAILED - RETRYING: Wait for the Kubernetes API to become available (this could take a minute) (59 retries left).
...
fatal: [kind-test-local]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "attempts": 60, "changed": false, "connection": "close", "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"forbidden: User \\\"system:anonymous\\\" cannot get path \\\"/apis\\\"\",\"reason\":\"Forbidden\",\"details\":{},\"code\":403}\n", "content_length": "189", "content_type": "application/json", "date": "Mon, 29 Jul 2019 19:49:30 GMT", "elapsed": 0, "json": {"apiVersion": "v1", "code": 403, "details": {}, "kind": "Status", "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"", "metadata": {}, "reason": "Forbidden", "status": "Failure"}, "msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "redirected": false, "status": 403, "url": "https://localhost:8443/apis", "x_content_type_options": "nosniff"}
```

**Environment**
* operator-sdk version:

```
master
```

* go version:

```
go version go1.12.7 darwin/amd64
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

KIND (`bsycorp/kind:latest-1.15`)

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**

Instead of using Ansible's `uri` module and blindly trying to load the `/api` endpoint, we should just use the `kubectl cluster-info` command, which allows us to use K8s' built-in authorization and should be a more stable test for cluster functionality. For example:

```yaml
    - name: Wait for the Kubernetes API to become available (this could take a minute)
      command: kubectl cluster-info
      register: result
      until: result.stdout is regex("Kubernetes master.* is running")
      retries: 60
      delay: 5
```

PR incoming.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** 

**Motivation for the change:**

Closes #1748

### CODE REVIEW

File: hack/tests/e2e-ansible-molecule.sh [hunk 1]
```diff
@@ -8,8 +8,15 @@ ROOTDIR="$(pwd)"
 GOTMP="$(mktemp -d)"
 trap_add 'rm -rf $GOTMP' EXIT
 # Needs to be from source until 2.20 comes out
-pip install --user git+https://github.com/ansible/molecule.git
-pip install --user docker openshift jmespath
+pip install --user \
+    pyasn1==0.4.5 \
+    pyasn1-modules==1.0.22
+pip install --user --ignore-installed \
+    git+https://github.com/ansible/molecule.git
```
Comment (fabianvf) [inline hack/tests/e2e-ansible-molecule.sh]: This we can pin to 2.20, this is likely the cause of our issues. It was initially installed from source because we relied on a few patches that hadn't yet made it to a release

File: hack/tests/e2e-ansible-molecule.sh [hunk 2]
```diff
@@ -8,8 +8,15 @@ ROOTDIR="$(pwd)"
 GOTMP="$(mktemp -d)"
 trap_add 'rm -rf $GOTMP' EXIT
 # Needs to be from source until 2.20 comes out
-pip install --user git+https://github.com/ansible/molecule.git
-pip install --user docker openshift jmespath
+pip install --user \
```
Comment (fabianvf) [inline hack/tests/e2e-ansible-molecule.sh]: With molecule pinned you can hopefully avoid needing to pin these specifically
