### PR TITLE
cmd/operator-sdk/internal: explicitly set GOROOT

### LINKED ISSUE #2744: Upgrading from v0.15.2 to v0.16.0 breaks types generation
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Support on upgrading to v0.16.0 from v0.15.2.

## Question

**What did you do?**

In our project we are working on migrating from Operator SDK v0.15.2 to v0.16.0, following the [migration guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v016x). After upgrading my `operator-sdk` binary to v0.16.0, the `operator-sdk generate k8s` step fails in our build process.

**What did you expect to see?**

Following the migration guide, we should expect to see a successful upgrade to v0.16.0 without any breaking changes to our CRD types.

**What did you see instead? Under which circumstances?**

The error reported is as follows (project name/repo redacted):

```
$ operator-sdk --verbose generate k8s
DEBU[0000] Debug logging is set
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [redacted_group:[v1alpha1], ]
F0330 09:15:56.449021   21969 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from redacted_repo_path/pkg/apis/redacted_group/v1alpha1.redacted_type
```

This particular error:

>Hit an unsupported type invalid type for invalid type

has been seen before, and I've found a handful of previous issues in this repo with this error. However, none of those solutions seem to apply here.

**Environment**
* operator-sdk version:

```
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

* Kubernetes version information:

N/A

* Kubernetes cluster kind: 

N/A

**Additional context**

For reference, `GOROOT` is set appropriately as reported by `go env`:

```
$ go env | grep GOROOT
GOROOT="/usr/local/go"

$ which go
/usr/local/go/bin/go

$ go version
go version go1.13.8 linux/amd64
```

It's worth also noting that for some reason this build is **passing** in our Travis CI, with v0.16.0 `operator-sdk` binary. So I'm certainly not claiming this is not a local env issue; however, I'm not sure what is breaking on the version upgrade.

Our project builds fine on v0.15.2 in my local env.

As for package dependencies, since I know that's also been a sort of cause for this kind of error, we are pulling in another internal package (not a public go pkg) from our GitHub Enterprise repos. In order for this to work, we set a `git config` rule to use `url.[new].insteadof=[old]` to handle pulling in the repo(s) via SSH instead of HTTPS. We also use this same config in Travis CI, which works fine.

### PR DESCRIPTION
**Pull request by aharbis**
**Description of the change:**

If the user's `GOROOT` does not match the `GOROOT` used to build the binary, they would be required to explicitly set the `GOROOT` env variable:

```bash
export GOROOT=$(go env GOROOT)
```

To avoid this step for end-users we can explicitly pull the `GOROOT` from `go env` and explicitly set the `GOROOT` env variable prior to generation code executing.

**Motivation for the change:**

Closes #2744

### CODE REVIEW

File: cmd/operator-sdk/internal/genutil/k8s.go [hunk 1]
```diff
@@ -34,6 +35,16 @@ import (
 func K8sCodegen() error {
 	projutil.MustInProjectRoot()
 
+	out, err := exec.Command("go", "env", "GOROOT").CombinedOutput()
```
Comment (camilamacedo86) [inline cmd/operator-sdk/internal/genutil/k8s.go:38]:
```suggestion
	goEnv, err := exec.Command("go", "env", "GOROOT").CombinedOutput()
```

File: cmd/operator-sdk/internal/genutil/k8s.go [hunk 2]
```diff
@@ -34,6 +35,16 @@ import (
...
+	if err != nil {
+		return fmt.Errorf("failed to GOROOT from go env")
```
Comment (joelanford) [inline cmd/operator-sdk/internal/genutil/k8s.go:40]:
```suggestion
		return fmt.Errorf("failed to get GOROOT from go env: %w", err)
```

File: cmd/operator-sdk/internal/genutil/k8s.go [hunk 3]
```diff
@@ -34,6 +35,16 @@ import (
...
+	}
+	goRoot := strings.TrimSuffix(string(out), "\n")
+	log.Debugf("Setting GOROOT=%s", goRoot)
+	if err := os.Setenv("GOROOT", goRoot); err != nil {
+		return fmt.Errorf("failed to set env GOROOT=" + goRoot)
```
Comment (joelanford) [inline cmd/operator-sdk/internal/genutil/k8s.go:45]:
```suggestion
		return fmt.Errorf("failed to set env GOROOT=%s: %w", goRoot, err)
```

File: cmd/operator-sdk/internal/genutil/k8s.go (hunk 1 above)
Comment (camilamacedo86) [inline cmd/operator-sdk/internal/genutil/k8s.go:38]: nit:  (to make more clear what it is)
```suggestion
	goEnv, err := exec.Command("go", "env", "GOROOT").CombinedOutput()
```

File: cmd/operator-sdk/internal/genutil/k8s.go [hunk 4]
```diff
@@ -34,6 +35,16 @@ import (
 func K8sCodegen() error {
```
Comment (camilamacedo86) [inline cmd/operator-sdk/internal/genutil/k8s.go:35]: Also, just one question, is the issue just faced with the operator-sdk generate k8s command?

Comment (aharbis) [reply cmd/operator-sdk/internal/genutil/k8s.go:35]: Good question. I tested in a failing environment (where I have release `v0.16.0` and unset `GOROOT`), and both the `crds` and `csv` generate commands work without throwing any errors.

This seems to be isolated to the `k8s` generation.

File: cmd/operator-sdk/internal/genutil/k8s.go (hunk 2 above)
Comment (aharbis) [reply cmd/operator-sdk/internal/genutil/k8s.go]: Done, sorry for the typo there! Good suggestion on including the `err`.

File: cmd/operator-sdk/internal/genutil/k8s.go (hunk 3 above)
Comment (aharbis) [reply cmd/operator-sdk/internal/genutil/k8s.go]: Done.

File: cmd/operator-sdk/internal/genutil/k8s.go (hunk 1 above)
Comment (aharbis) [reply cmd/operator-sdk/internal/genutil/k8s.go]: Done, good suggestion!

**Comment by aharbis** [comment]
Thanks for the quick turnaround on feedback on the PR! Pushed a patch commit, I was not sure if y'all prefer me to squash and update my branch, or if you handle the squash on the merge. Let me know if anything is out of place, and I'll keep note for future contributions.

**Comment by joelanford** [comment]
We squash on merge, so no worries. As soon as CI passes, I'll merge it in. Thanks again!
