### PR TITLE
Resources without generation will not skip events

### LINKED ISSUE #2108: Secret Watches fail to detect changes
## Bug Report

**What did you do?**
Added a watch on Secrets in the `watches.yaml` file:

```
---
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale

- version: v1
  kind: Secret
  role: /opt/ansible/roles/csi-scale-secret
  manageStatus: false # Note this was required, otherwise the container crashed.
```

**What did you expect to see?**
I expected that changes to Secrets would be captured and call the `/opt/ansible/roles/csi-scale-secret` role.

**What did you see instead? Under which circumstances?**
Secrets would trigger the `/opt/ansible/roles/csi-scale-secret` role once at startup and never again. Changes to secrets would not yield additional responses.

**Environment**
* operator-sdk version: `v0.10.0`

* go version: `go version go1.13.1 linux/amd64`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  `remote`

* Are you writing your operator in ansible, helm, or go? `ansible`

**Possible Solution**

**Additional context**
I've moved temporarily to a go based solution which invokes my ansible role, so my environment is currently not the same (would prefer to return to pure ansible).

### PR DESCRIPTION
**Pull request by fabianvf**
Fixes #2108

If the `metadata.generation` is `0`, the event will now still trigger a
reconciliation.

**Description of the change:**

**Motivation for the change:**

### CODE REVIEW

File: pkg/predicate/predicate.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func (GenerationChangedPredicate) Update(e event.UpdateEvent) bool {
 		log.Error(nil, "Update event has no new metadata", "event", e)
 		return false
 	}
-	if e.MetaNew.GetGeneration() == e.MetaOld.GetGeneration() {
+	if e.MetaNew.GetGeneration() == e.MetaOld.GetGeneration() && e.MetaNew.GetGeneration() != 0 {
```
Comment (fabianvf) [inline pkg/predicate/predicate.go:49]: I'm pretty sure that this will only happen if the metadata.generation is not set and therefore goes to the default integer value of 0 when queried.
