### PR TITLE
pkg/test/context.go: create an id that is a valid namespace name

### LINKED ISSUE #2101: Operator-sdk's test-framework fails to initialize cluster resource: Namespace
## Bug Report

**What did you do?**
Tried to run e2e tests on memcached sample operator.

- For curiosity, I changed the test name and made sure it will exceed the openshift's `project/namespace` character limit which is `63 characters`
- Then ran this command `operator-sdk test local ./test/e2e --image quay.io/pratikjagrut/memcached-operator:v0.0.2 --verbose`

**What did you expect to see?**
SDK to handle exceeded namespace character limit and tests to pass.

**What did you see instead? Under which circumstances?**
Fails with the following error.
```
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/tmp/namespaced-manifest.yaml605350766", "-globalMan", "/tmp/global-manifest.yaml069236213", "-root", "/home/pjagrut/go/src/github.com/operator-framework/operator-sdk-samples/memcached-operator"} 
=== RUN   TestMemcached
=== RUN   TestMemcached/memcached-group
=== RUN   TestMemcached/memcached-group/Cluster-memcached-memcached-group-cluster
=== PAUSE TestMemcached/memcached-group/Cluster-memcached-memcached-group-cluster
=== CONT  TestMemcached/memcached-group/Cluster-memcached-memcached-group-cluster
--- FAIL: TestMemcached (27.18s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster-memcached-memcached-group-cluster (0.31s)
            memcached_test.go:98: failed to initialize cluster resources: Namespace "memcached-memcached-group-cluster-memcached-memcached-group-cluster-1571914599" is invalid: metadata.name: Invalid value: "memcached-memcached-group-cluster-memcached-memcached-group-cluster-1571914599": must be no more than 63 characters
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/memcached-operator/test/e2e	54.554s
Error: failed to build test binary: (failed to exec []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/tmp/namespaced-manifest.yaml605350766", "-globalMan", "/tmp/global-manifest.yaml069236213", "-root", "/home/pjagrut/go/src/github.com/operator-framework/operator-sdk-samples/memcached-operator"}: exit status 1)
Usage:
  operator-sdk test local <path to tests directory> [flags]

Flags:
      --debug                         Enable debug-level logging
      --global-manifest string        Path to manifest for Global resources (e.g. CRD manifests)
      --go-test-flags string          Additional flags to pass to go test
  -h, --help                          help for local
      --image string                  Use a different operator image from the one specified in the namespaced manifest
      --kubeconfig string             Kubeconfig path
      --local-operator-flags string   The flags that the operator needs (while using --up-local). Example: "--flag1 value1 --flag2=value2"
      --molecule-test-flags string    Additional flags to pass to molecule test
      --namespace string              If non-empty, single namespace to run tests in
      --namespaced-manifest string    Path to manifest for per-test, namespaced resources (e.g. RBAC and Operator manifest)
      --no-setup                      Disable test resource creation
      --up-local                      Enable running operator locally with go run instead of as an image in the cluster

Global Flags:
      --verbose   Enable verbose logging

```

**Environment**
* operator-sdk version: `v0.10.0-117-gc7f429f0", commit: "c7f429f05808406068b1a67f49b0de9e6481f545`

* go version: `go1.12.9 linux/amd64`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T15:15:06Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-beta.2+03b33d2", GitCommit:"03b33d2", GitTreeState:"clean", BuildDate:"2019-10-21T19:38:32Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Are you writing your operator in ansible, helm, or go?
GO

**Possible Solution**
Seems like SDK appends `operator name, test-group name and test name` to create the namespace without taking care of the length of the final string.
We should check the char length of the final string before creating the namespace.
If it exceeds then should cut it down to less than 63 chars or else it is good to go.

### PR DESCRIPTION
**Pull request by dustinspecker**
Before this change it was possible for `TestCtx.GetNamespace()` to create a
namespace with too long of a name, thus getting an error from Kubernetes
saying the namespace name exceeded 63 characters.

Now set the id to "osdk-e2e-UUID", so that `TestCtx.GetNamespace()` is
guaranteed to have a namespace name be 63 characters or less, which is a
valid namespace name.

Fixes #2101

### CODE REVIEW

File: pkg/test/resource_creator.go [hunk 1]
```diff
@@ -34,7 +35,7 @@ func (ctx *TestCtx) GetNamespace() (string, error) {
 		return ctx.namespace, nil
 	}
 	// create namespace
-	ctx.namespace = ctx.GetID()
+	ctx.namespace = fmt.Sprintf("osdk-e2e-%s", uuid.New())
```
Comment (dustinspecker) [inline pkg/test/resource_creator.go]: I'd like to investigate adding unit tests around GetNamespace this weekend. Need to figure how to handle testing code using UUID. Attach a UUID on TestCtx? Maybe change GetID() to return this UUID on TestCtx instead of creating the UUID here.

Comment (dustinspecker) [reply pkg/test/resource_creator.go]: Taking a second look at this: I think assigning ctx.id in newTestCtx to the above string would make this all easier. So instead of changing resource_creator modify pkg/test/context.go's newTestCtx.

File: pkg/test/context.go [hunk 2]
```diff
@@ -48,23 +47,8 @@ type CleanupOptions struct {
...
-			),
-			"test",
-		)
-	} else {
-		prefix = "main"
-	}
-
-	id := prefix + "-" + strconv.FormatInt(time.Now().Unix(), 10)
+	// TestCtx is used among others for namespace names where '/' is forbidden and must be 63 characters or less
+	id := "osdk-e2e-" + uuid.New()
```
Comment (dustinspecker) [inline pkg/test/context.go]: I like this approach much better than my previous code change. This weekend I'd still like to add unit tests around NewTestCtx, but please let me know thoughts on this approach.

File: pkg/test/context.go [hunk 3]
```diff
@@ -48,23 +47,8 @@ type CleanupOptions struct {
...
-				-1,
-			),
-			"test",
-		)
-	} else {
-		prefix = "main"
-	}
-
-	id := prefix + "-" + strconv.FormatInt(time.Now().Unix(), 10)
+	// TestCtx is used among others for namespace names where '/' is forbidden and must be 63 characters or less
```
Comment (camilamacedo86) [inline pkg/test/context.go]: @joelanford wdyt? Are you ok with? 
For me, it shows fine.

File: CHANGELOG.md [hunk 4]
```diff
@@ -25,6 +25,7 @@
 
 ### Bug Fixes
 - Fix `operator-sdk build`'s `--image-build-args` to support spaces within quotes like `--label some.name="First Last"`. ([#2312](https://github.com/operator-framework/operator-sdk/pull/2312))
+- Fix `pkg/test/NewTestCtx()` to always create an id that is a valid namespace name. This prevents `TestCtx.GetNamespace()` from attempting to sometimes erroneously creating a namespace with a name exceeding 63 characters. ([#2335](https://github.com/operator-framework/operator-sdk/pull/2335))
```
Comment (camilamacedo86) [inline CHANGELOG.md]: WDYT?

```suggestion
- Fix issue to use from test-framework which is faced when the created namespace is exceeding 63 characters. The `TestCtx.GetNamespace()` was changed to always create a unique ID instead of using the operator name in order to avoid this scenario. ([#2335](https://github.com/operator-framework/operator-sdk/pull/2335))
```

Comment (dustinspecker) [reply CHANGELOG.md]: Thank you for the suggestion! I made a couple additional modifications to the proposed change. Please let me know what you think.

File: pkg/test/context.go (hunk 2 above)
Comment (camilamacedo86) [reply pkg/test/context.go]: It is ok for me. @joelanford have you any objection?

File: test/test-framework/test/e2e/memcached_test.go [hunk 5]
```diff
@@ -45,8 +45,8 @@ func TestMemcached(t *testing.T) {
 	}
 	// run subtests
 	t.Run("memcached-group", func(t *testing.T) {
-		t.Run("Cluster", MemcachedCluster)
-		t.Run("Cluster2", MemcachedCluster)
+		t.Run("AVeryLongClusterNameThatIsSoLong", MemcachedCluster)
```
Comment (estroz) [inline test/test-framework/test/e2e/memcached_test.go]: Why are these names changed?

Comment (camilamacedo86) [reply test/test-framework/test/e2e/memcached_test.go]: I think he tried to demonstrate that the issue was solved. 
However, I agree with @estroz. I would stick with the previous names either.

Comment (dustinspecker) [reply test/test-framework/test/e2e/memcached_test.go]: Yep, that's why I did it. Before this change that test would fail. I'll change it back.
