### PR TITLE
Fixed invalid object names generated for long package names 

### LINKED ISSUE #4470: k8sutil.TrimDNS1123Label creates invalid values
#### What did you do?
```
operator-sdk run bundle --install-mode AllNamespaces -n proactive-node-scaling-operator quay.io/$repo/proactive-node-scaling-operator-bundle:latest
I0202 10:50:13.277327   46403 request.go:645] Throttling request took 1.051324502s, request: GET:https://api.control-cluster-raffa.demo.red-chesterfield.com:6443/apis/authentication.k8s.io/v1beta1?timeout=32s
FATA[0010] Failed to run bundle: create catalog: error creating registry pod: error creating registry pod: create registry pod: Pod "-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest" is invalid: metadata.name: Invalid value: "-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 
```
I never got this error before. The catalog source pod name is clearly wrong: `-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest`, I probably made some mistake somewhere. How is that name generated?

#### What did you expect to see?

Working bundle

#### What did you see instead? Under which circumstances?
```
Invalid value: "-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 
```
#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Unknown

`$ operator-sdk version`
```
operator-sdk version
operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64
```

`$ go version` (if language is Go)
1.15.5

`$ kubectl version`

N/A

### PR DESCRIPTION
**Pull request by jmrodri**
* TrimDNS1123Label would trim strings but end up creating invalid DNS1123
strings.
* FormatOperatorNameDNS1123 would return strings that were invalid if
  they begin or end with non-alphanumeric or hyphens.

Fixes #4470

Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

File: internal/util/k8sutil/k8sutil.go [hunk 1]
```diff
@@ -102,7 +110,11 @@ func FormatOperatorNameDNS1123(name string) string {
 // by removing characters from the beginning of label such that len(label) <= 63.
 func TrimDNS1123Label(label string) string {
```
Comment (estroz) [inline internal/util/k8sutil/k8sutil.go:111]: This function assumes `label` is already a DNS1123 label

Comment (jmrodri) [reply internal/util/k8sutil/k8sutil.go:111]: @estroz the string was valid but too long. So when we trimmed it we put a leading hyphen which is INVALID.  For example, this `quay-io-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest` turned into `-raffaelespazzoli-proactive-node-scaling-operator-bundle-latest`which is invalid.

Comment (estroz) [reply internal/util/k8sutil/k8sutil.go:107]: Right, there's a bug here that could be solved by adding `FormatOperatorNameDNS1123()` but is inefficient since `label` is already a DNS 1123 label. See below.

File: internal/util/k8sutil/k8sutil.go [hunk 2]
```diff
@@ -102,7 +106,11 @@ func FormatOperatorNameDNS1123(name string) string {
...
 	if len(label) > validation.DNS1123LabelMaxLength {
-		return label[len(label)-validation.DNS1123LabelMaxLength:]
+		lbl := label[len(label)-validation.DNS1123LabelMaxLength:]
+		if len(validation.IsDNS1123Label(lbl)) != 0 {
+			return FormatOperatorNameDNS1123(lbl)
+		}
+		return lbl
```
Comment (estroz) [inline internal/util/k8sutil/k8sutil.go:113]:
```suggestion
		return strings.TrimSpace(label[len(label)-validation.DNS1123LabelMaxLength:], "-")
```

**Review by estroz — CHANGES_REQUESTED** [review]

File: internal/util/k8sutil/k8sutil.go [hunk 3]
```diff
@@ -93,7 +93,11 @@ var dns1123LabelRegexp = regexp.MustCompile("[^a-zA-Z0-9]+")
 // replacing all non-compliant UTF-8 characters with "-".
 func FormatOperatorNameDNS1123(name string) string {
 	if len(validation.IsDNS1123Label(name)) != 0 {
-		return dns1123LabelRegexp.ReplaceAllString(name, "-")
+		// Use - for any of the non-matching characters
+		n := dns1123LabelRegexp.ReplaceAllString(name, "-")
```
Comment (jberkhahn) [inline internal/util/k8sutil/k8sutil.go:97]: I know you didn't write the regex for this, but aren't capital letters not allowed in dns names?

Comment (estroz) [reply internal/util/k8sutil/k8sutil.go:97]: They are not, but if that regexp didn't contain `A-Z` then all capital letters would be replaced with `-`.

File: internal/util/k8sutil/k8sutil.go [hunk 4]
```diff
@@ -93,7 +93,11 @@ var dns1123LabelRegexp = regexp.MustCompile("[^a-zA-Z0-9]+")
...
+
+		// Now let's remove any leading or trailing -
+		return strings.Trim(n, "-")
```
Comment (estroz) [inline internal/util/k8sutil/k8sutil.go:100]:
```suggestion
		return strings.ToLower(strings.Trim(n, "-"))
```

File: internal/util/k8sutil/k8sutil.go (hunk 2 above)
Comment (jmrodri) [reply internal/util/k8sutil/k8sutil.go:113]: `TrimSpace` only takes one argument. This seems to work `return strings.Trim(label[len(label)-validation.DNS1123LabelMaxLength:], "-")`

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by jberkhahn** [comment]
ok
/lgtm

File: changelog/fragments/fix-trim-format-dns1123-functions.yaml [hunk 5]
```diff
@@ -0,0 +1,11 @@
+entries:
+  - description: >
+      TrimDNS1123Label changed to return VALID DNS1123 strings. It
+      previously blindly trimmed them potentially creating invalid labels.
+
+      FormatOperatorNameDNS1123 would return strings that were invalid if
+      they begin or end with non-alphanumeric or hyphens.
```
Comment (estroz) [inline changelog/fragments/fix-trim-format-dns1123-functions.yaml:7]: These are internal functions. This should read something like
```suggestion
      Fixed invalid object names generated for long package names passed to `run packagemanifests`.
```

**Comment by jmrodri** [comment]
@estroz updated it and rebased things around.

**Review by estroz — APPROVED** [review]
/lgtm
