### PR TITLE
internal/pkg/scaffold: use `Resource.GoImportGroup` in CRD/CR file names

### LINKED ISSUE #1368: unable to generate CRD
## Bug Report

I am unable to generate the CRD for the type below. I get the following output:
```
GOFLAGS="-v" operator-sdk generate openapi 
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [redhatcop:[v1alpha1], ] 
2019/05/02 08:17:53 Code for OpenAPI definitions generated
INFO[0000] Code-generation complete. 
```
so basically nothing gets generated.

**Environment**
```
operator-sdk version
operator-sdk version: v0.7.0+git
```
```
go version
go version go1.11.7 linux/amd64
```

**Possible Solution**
I don't have a workaround. I am currently stuck

**Additional context**
```
ls pkg/apis/redhatcop/v1alpha1/
doc.go  namespaceconfig_types.go  register.go  zz_generated.deepcopy.go  zz_generated.openapi.go
```

here is the entire file `namespaceconfig_types.go`:

```
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// NamespaceConfigSpec defines the desired state of NamespaceConfig
// +k8s:openapi-gen=true
type NamespaceConfigSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html
	Selector  metav1.LabelSelector   `json:"selector,omitempty"`
	Resources []runtime.RawExtension `json:"resources,omitempty"`
}

// NamespaceConfigStatus defines the observed state of NamespaceConfig
// +k8s:openapi-gen=true
type NamespaceConfigStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// NamespaceConfig is the Schema for the namespaceconfigs API
// +k8s:openapi-gen=true
type NamespaceConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NamespaceConfigSpec   `json:"spec,omitempty"`
	Status NamespaceConfigStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// NamespaceConfigList contains a list of NamespaceConfig
type NamespaceConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NamespaceConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NamespaceConfig{}, &NamespaceConfigList{})
}
```

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** use `Resource.GoImportGroup` in CRD and CR file names.

**Motivation for the change:** the `controller-tools` CRD generator uses API import path in CRD file names, causing a "cache miss" in the SDK's CRD generator wrapper. See #1368 for more details.

Closes #1368

### CODE REVIEW

File: internal/pkg/scaffold/cr.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ type CR struct {
 func (s *CR) GetInput() (input.Input, error) {
 	if s.Path == "" {
 		fileName := fmt.Sprintf("%s_%s_%s_cr.yaml",
-			strings.ToLower(s.Resource.Group),
+			strings.ToLower(s.Resource.GoImportGroup),
```
Comment (joelanford) [inline internal/pkg/scaffold/cr.go]: Nit: Doesn't really matter, but we don't have to use `strings.ToLower()` here, since we've already done that for `GoImportGroup`:

https://github.com/operator-framework/operator-sdk/blob/4db8cd7e21a9a9a672cc0996f96bd9dfe1d29d66/internal/pkg/scaffold/resource.go#L133-L134

**Comment by hasbro17** [comment]
On second thought since this wasn't an issue in the previous release then probably no need to mention in the CHANGELOG.
