### PR TITLE
pkg/schaffold: Add missing errors handeling in main.go

### LINKED ISSUE #893: pkg/schaffold: Missing error handling in generated code "main.go"
## Bug Report

**What did you do?**
when running `errcheck` tool on the generated code, it detects 2 errors in `cmd/manager/main.go`:

- cmd/manager/main.go:70:15:warning: error return value not checked (leader.Become(context.TODO(), "memcached-operator-lock")) (errcheck)
- cmd/manager/main.go:78:9:warning: error return value not checked (r.Unset()) (errcheck)

**What did you expect to see?**
`errcheck` report should be clear of errors on the generated code.

**Environment**
* operator-sdk version: 

dd62eaa4a4f3b703f7489003dd1a862b92c247a6

* Kubernetes version information:

not relevant

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go? GO

**Possible Solution**
I will propose a PR that add the missing error handling.

### PR DESCRIPTION
**Pull request by clamoriniere1A**
**Description of the change:**

This PR is adding missings errors handling in the operator generated code from `pkg/scaffold`.

**Motivation for the change:**

"errcheck" tool detects 2 errors on the operator generated code:
- cmd/manager/main.go:70:15:warning: error return value not checked
(leader.Become(context.TODO(), "memcached-operator-lock")) (errcheck)
- cmd/manager/main.go:78:9:warning: error return value not checked (r.Unset())
(errcheck)

Closes #893

### CODE REVIEW

File: pkg/scaffold/cmd.go [hunk 1]
```diff
@@ -90,15 +90,24 @@ func main() {
...
 
 	r := ready.NewFileReady()
 	err = r.Set()
 	if err != nil {
 		log.Error(err, "")
 		os.Exit(1)
 	}
-	defer r.Unset()
+	defer func() {
+		if err = r.Unset(); err != nil {
```
Comment (shawn-hurley) [inline pkg/scaffold/cmd.go]: We should consider instead to remove the error check from `Unset` and instead allow it to panic if it errors IMO. 
/cc @mhrivnak

Comment (mhrivnak) [reply pkg/scaffold/cmd.go]: I'm not a fan of panics in general, and I subscribe to the philosophy articulated [here](https://github.com/golang/go/wiki/PanicAndRecover#usage-in-a-package). Printing a stack trace of each goroutine is usually not that helpful to an end user.

Logging the error and exiting with a non-zero code seems like the best thing to do in this circumstance.

**Comment by clamoriniere1A** [comment]
@shawn-hurley, @mhrivnak and @AlexNPavel thank you for the review. 
I updated the PR in order to re-run the failing CI job, that is all green now.
