### PR TITLE
SDK log injection and uniform logging in operator-sdk binary

### LINKED ISSUE #503: Default logger for the SDK
Setting log level and adding verbose flag would be useful as it'd be nice to give some visibility to the user about what is happening.

### LINKED ISSUE #732: Improve error message when no resources have been added to operator
If you create a new operator, and then run `operator-sdk generate k8s` without first creating any custom resources, as the getting started guide was instructing people to do until https://github.com/operator-framework/getting-started/issues/30 fixed it, you get this less than helpful error message:

```sh
$ operator-sdk generate k8s
Running code-generation for custom resource group versions: []
2018/11/12 14:32:03 failed to perform code-generation: (exit status 255)
```

This could be improved to something more informative so that if people do do this (for example, if they accidentally miss the step that I added to the getting started guide), they have some hope of working out what they did wrong.

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
1. Switch the `operator-sdk` binary's logger from a mix of std `log` and [`logrus`](https://github.com/sirupsen/logrus) to only `logrus`.
1. Use [`controller-runtime/pkg/runtime/log.SetLogger()`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/runtime/log#SetLogger) to inject [`logr.Logger`](https://github.com/go-logr/logr) that users can define into their operator.
    - The SDK injects [`zap`](https://godoc.org/go.uber.org/zap) by default in this PR.
    - `pkg/sdk/*metrics*` and `pkg/ansible` are used by generated operators, which is why these packages don't use `logrus`.

**Motivation for the change:** Operators generated by the SDK did not have a uniform logging interface pre-`v0.1.0`. Now that `controller-runtime` is the main source of logs in a generated operator, the decision was made to expose a log injection mechanism so users can choose what logger to use and operators emit uniform, structured logs. See #503 for our detailed discussion. The `operator-sdk` binary similarly did not have uniform logging. `logrus` is a reasonable choice for the binary's logger because warnings are used frequently.

Closes #503, closes #732

### CODE REVIEW

File: commands/operator-sdk/cmd/add/crd.go [hunk 1]
```diff
@@ -60,26 +60,26 @@ func crdFunc(cmd *cobra.Command, args []string) {
 	verifyCrdFlags()
 	verifyCrdDeployPath()
 
-	fmt.Fprintln(os.Stdout, "Generating custom resource definition (CRD) file")
+	fmt.Println("Generating custom resource definition (CRD) file")
```
Comment (estroz) [inline commands/operator-sdk/cmd/add/crd.go]: Anyone have thoughts on whether we should keep `fmt.[F]?[Pp]rint*(...)` statements for binary step logging or switch to `log.Info*(...)`?

File: commands/operator-sdk/cmd/up/local.go [hunk 2]
```diff
@@ -142,23 +142,22 @@ func upLocalAnsible() {
...
 	// wait for either to finish
 	err = <-done
-	if err == nil {
-		logrus.Info("Exiting")
-	} else {
-		logrus.Fatal(err.Error())
+	if err != nil {
+		log.Fatal(err)
 	}
+	log.Info("Ansible operator started succesfully. Exiting.")
```
Comment (estroz) [inline commands/operator-sdk/cmd/up/local.go]: @shawn-hurley @mhrivnak is this message correct? I want to add more context to this log message.

File: commands/operator-sdk/cmd/add/crd.go (hunk 1 above)
Comment (LiliC) [reply commands/operator-sdk/cmd/add/crd.go]: Yes agree, think that would unify the logging, by switching to `log.Info()`. Although I am okay if that is done that in a separate PR.

File: commands/operator-sdk/cmd/up/local.go (hunk 2 above)
Comment (mhrivnak) [reply commands/operator-sdk/cmd/up/local.go]: No. Line 152 will block for as long as the operator is running. When the operator exits, either due to an error or a signal handler, in the usual case it will be long after startup. I suggest sticking with just "Exiting". We could try to add a reason for why it's exiting, but if `err` is `nil`, there isn't much to go on.

File: pkg/ansible/controller/controller.go [hunk 3]
```diff
@@ -16,14 +16,13 @@ package controller
...
 	"fmt"
-	"log"
 	"strings"
 	"time"
 
 	"github.com/operator-framework/operator-sdk/pkg/ansible/events"
 	"github.com/operator-framework/operator-sdk/pkg/ansible/runner"
 
-	"github.com/sirupsen/logrus"
+	log "github.com/sirupsen/logrus"
```
Comment (joelanford) [inline pkg/ansible/controller/controller.go]: I'm wondering if we should use the `logr` interface in the ansible (and eventually helm) operator packages and main functions.

If those operators had been developed using the scaffolding in this PR, they would likely be using logr-based SDK log package.

Also, in the case where a user migrates from ansible/helm to a go-based hybrid, would their operator logging be a mix of logr (from any added controllers) and logrus (from `pkg/ansible`)?

Comment (estroz) [reply pkg/ansible/controller/controller.go]: @mhrivnak @shawn-hurley what do you think should be done with `pkg/ansible/events`? There's probably a similar approach with `logr` to get the same functionality.

**Comment by estroz** [comment]
Note: I'm removing package-level logging in favor of a more configurable setup.

File: pkg/ansible/controller/controller.go (hunk 3 above)
Comment (estroz) [reply pkg/ansible/controller/controller.go]: Re-implementing with `logr`.

Comment (shawn-hurley) [reply pkg/ansible/controller/controller.go]: @estroz thank you for implementing this for the pkg/ansible!

File: example/memcached-operator/memcached_controller.go.tmpl [hunk 4]
```diff
@@ -95,11 +97,11 @@ func (r *ReconcileMemcached) Reconcile(request reconcile.Request) (reconcile.Res
 			// Request object not found, could have been deleted after reconcile request.
 			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
 			// Return and don't requeue
-			log.Printf("Memcached %s/%s not found. Ignoring since object must be deleted\n", request.Namespace, request.Name)
+			log.Error(err, "Memcached resource not found. Ignoring since object must be deleted", "Request.Namespace", request.Namespace, "Requst.Name", request.Name)
```
Comment (AlexNPavel) [inline example/memcached-operator/memcached_controller.go.tmpl]: Should this be an Error or a different log level? Error implies that something went wrong, but the `IsNotFound` situation is normal when a CR is deleted.

File: commands/operator-sdk/cmd/build.go [hunk 5]
```diff
@@ -183,13 +186,15 @@ func buildFunc(cmd *cobra.Command, args []string) {
...
 		if err != nil {
-			log.Fatalf("failed to build test binary: %v", err)
+			log.Fatalf("failed to build test binary: (%v)", err)
 		}
 		// if a user is using an older sdk repo as their library, make sure they have required build files
 		testDockerfile := filepath.Join(scaffold.BuildTestDir, scaffold.DockerfileFile)
 		_, err = os.Stat(testDockerfile)
 		if err != nil && os.IsNotExist(err) {
 
+			log.Info("Generating operator test files.")
```
Comment (hasbro17) [inline commands/operator-sdk/cmd/build.go]: This could be a little more descriptive. It's not really test files. It's the build manifests needed for the test-framework.
```Go
log.Info("Generating build manifests for test-framework")
```

Same with the log.Fatal error if this fails.

File: commands/operator-sdk/cmd/new.go [hunk 6]
```diff
@@ -119,6 +122,8 @@ func mustBeNewProject() {
 }
 
 func doScaffold() {
+	log.Infof("Generating %s project scaffold.", strings.Title(operatorType))
```
Comment (hasbro17) [inline commands/operator-sdk/cmd/new.go]: Do we need this and Line 153? The log on line 84 pretty much says this already including the type.

File: commands/operator-sdk/cmd/test/local.go [hunk 7]
```diff
@@ -135,12 +137,12 @@ func testLocalFunc(cmd *cobra.Command, args []string) {
...
 		err = ioutil.WriteFile(tlConfig.globalManPath, combined, os.FileMode(fileutil.DefaultFileMode))
 		if err != nil {
-			log.Fatalf("could not create temporary global manifest file: %v", err)
+			log.Fatalf("could not create temporary global manifest file: (%v)", err)
 		}
 		defer func() {
 			err := os.Remove(tlConfig.globalManPath)
 			if err != nil {
-				log.Fatalf("could not delete global namespace manifest file")
+				log.Fatal("could not delete global namespace manifest file")
```
Comment (hasbro17) [inline commands/operator-sdk/cmd/test/local.go]:
```suggestion
				log.Fatal("could not delete global manifest file")
```

File: commands/operator-sdk/cmd/up/local.go [hunk 8]
```diff
@@ -71,6 +71,9 @@ const (
 
 func upLocalFunc(cmd *cobra.Command, args []string) {
 	mustKubeConfig()
+
+	log.Info("Bringing operator up locally.")
```
Comment (hasbro17) [inline commands/operator-sdk/cmd/up/local.go]:
```suggestion
	log.Info("Running the operator locally.")
```

**Comment by hasbro17** [comment]
@estroz Can you please share a sample output of what the logs look like now? e.g for the memcached-operator.

File: pkg/ansible/controller/controller.go [hunk 9]
```diff
@@ -33,6 +33,8 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/source"
 )
 
+var log = logutil.SDKLog.WithName("controller")
```
Comment (hasbro17) [inline pkg/ansible/controller/controller.go]:
```suggestion
var log = logutil.SDKLog.WithName("ansible-controller")
```

File: pkg/logutil/log_util.go [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+const (
+	// VDebug == -1. log.V(VDebug).Info(...) == log.Debug(...)
+	VDebug LogVerbosity = iota - 1
+	_
+	// VWarn == 1. log.V(VWarn).Info(...) == log.Warn(...)
+	VWarn
+)
+
+// SDKLog is the parent logger for logs generated by operator code.
+var SDKLog = logf.Log.WithName("operator-sdk")
```
Comment (hasbro17) [inline pkg/logutil/log_util.go]: Do we need to name the parent logger? We're naming it everywhere else. Wondering if there's a reason to prepend the name operator-sdk to all log statements?

Perhaps for the SDK pkg logs yes. But for the logger being used in the templates?

File: example/memcached-operator/memcached_controller.go.tmpl [hunk 11]
```diff
@@ -85,7 +87,7 @@ type ReconcileMemcached struct {
 // The Controller will requeue the Request to be processed again if the returned error is non-nil or
 // Result.Requeue is true, otherwise upon completion it will remove the work from the queue.
 func (r *ReconcileMemcached) Reconcile(request reconcile.Request) (reconcile.Result, error) {
-	log.Printf("Reconciling Memcached %s/%s\n", request.Namespace, request.Name)
+	log.Info("Reconciling Memcached", "Request.Namespace", request.Namespace, "Requst.Name", request.Name)
```
Comment (hasbro17) [inline example/memcached-operator/memcached_controller.go.tmpl]: Seeing a log message formatted like this is quite weird after using Printf, Logf etc for so long.
@estroz Can we format the string with `fmt.Sprintf()`? That may be a bit verbose though.
```Go
log.Info(fmt.Sprintf("Reconciling Memcached %s/%s\n", request.Namespace, request.Name))
```
Seems like [logr.Info](https://github.com/go-logr/logr/blob/master/logr.go#L107-L111) just accepts keys/values.

@shawn-hurley This format of constructing log messages seems a bit cumbersome to me at least. Not sure how users would feel if this is the default.

File: pkg/logutil/log_util.go (hunk 10 above)
Comment (estroz) [reply pkg/logutil/log_util.go]: `controller-runtime` sets their [package logger](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/runtime/log/log.go#L101) with a name, so I followed that convention. Using the `"operator-sdk"` log name we can differentiate `controller-runtime` logs from operator logs. I can remove the name if we don't want to have differentiated logs.

**Comment by estroz** [comment]
@hasbro17 logs look like this:
```
2018-11-08T00:00:25.700Z	WARN	operator-sdk.logging_event_handler	events/log_events.go:73	[playbook debug]	{"name": "example-memcached", "namespace": "default", "gvk": "ansible.example.com/v1alpha1, Kind=Memcached", "event_type": "runner_on_ok", "job": "5164212467572124800", "EventData.TaskArgs": "msg=this is a finalizer"}
```
As per your comment on formatting the log message, I don't think its necessary because there's enough structured information here to get the meaning of a log message.

File: example/memcached-operator/memcached_controller.go.tmpl (hunk 11 above)
Comment (joelanford) [reply example/memcached-operator/memcached_controller.go.tmpl]: I agree that this interface pushes users away from unstructured string formatting (and toward structured logging). 

It lends itself to building a scoped logger with `WithName` and/or `WithValues` so that users don't have to repeat the same string formatting for variables every time they need to log a message.
```go
requestLogger := log.WithFields("Request.Namespace", request.Namespace, "Request.Name", request.Name)
requestLogger.Info("Reconciling Memcached")
...
requestLogger.Info("Memcached resource not found. Ignoring since object must be deleted")
```

My two cents is that the nudge toward structured logging is probably a good thing since the interface makes it cleaner to log simple messages that share common metadata, and it makes logs more machine-consumable by default, which is probably a good habit to reinforce.

Comment (shawn-hurley) [reply example/memcached-operator/memcached_controller.go.tmpl]: I +1 basically everything @joelanford said above.  As stated earlier in this conversation as well, if users of the SDK hate it they can choose a different logger. I think to have this as a default but maybe (later) adding a doc showing how to go back to logrus will show users they have a choice. I think in that doc it would be smart though to explain what Joe said above. 

Thoughts?

Comment (hasbro17) [reply example/memcached-operator/memcached_controller.go.tmpl]: Yeah I agree. It's actually good if we're pushing users towards structured logging as the default.
I guess my initial reaction was prompted by being used to unstructured logging myself.

And yeah a doc to illustrate the choice of using a different logger should be good enough if users want to opt out of the default.

File: pkg/logutil/log_util.go (hunk 10 above)
Comment (hasbro17) [reply pkg/logutil/log_util.go]: @estroz The controller-runtime logs should already be different from all other logs with its own name.

What we might want to differentiate between is the SDK pkg logs and the user's logs within their reconcilers and pkgs.
Right now both logs will be prefixed with `operator-sdk`. Which doesn't differentiate between our pkg logs and the user's custom logs. 
So I would prefer to keep this unnamed, and instead keep the naming in whatever pkg the logs are being used in.

File: example/memcached-operator/memcached_controller.go.tmpl (hunk 11 above)
Comment (estroz) [reply example/memcached-operator/memcached_controller.go.tmpl]: @hasbro17 @shawn-hurley @joelanford added a doc on logging.

File: doc/dev/logging.md [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+        reqLogger.Error(err, "failed to create new Deployment", "Deployment.Namespace", dep.Namespace, "Deployment.Name", dep.Name)
+        return reconcile.Result{}, err
+      }
+    }
+    return reconcile.Result{}, err
+  }
+
+  ...
+}
+```
```
Comment (hasbro17) [inline doc/dev/logging.md]: @estroz 👍 The doc looks great.
Can we also add a sample output of the logs at the end of this snippet to show what the info and error logs look like with the keyValues set. We can mention that it's for the default zap implementation.

File: pkg/logutil/log_util.go (hunk 10 above)
Comment (estroz) [reply pkg/logutil/log_util.go]: In that case we can do away with `SDKLog` and call `logf.Log` to create loggers instead. Sound good?

File: pkg/logutil/log_util.go [hunk 13]
```diff
@@ -0,0 +1,32 @@
...
+// is 0: log.V(0).Info(...) == log.Info(...)
+//
+// HACK: zapr doesn't calculate log levels correctly, so we must set log
+// level integers incorrectly (according to logr) for now so they map to zapr's.
+const (
+	// VDebug == -1. log.V(VDebug).Info(...) == log.Debug(...)
+	VDebug LogVerbosity = iota - 1
+	_
+	// VWarn == 1. log.V(VWarn).Info(...) == log.Warn(...)
+	VWarn
```
Comment (hasbro17) [inline pkg/logutil/log_util.go]: Going on a bit of exposition here:

So logr levels have no concept of Warn, Fatal or anything else. It only has Info and Error.
Logr's Info logs [decrease in importance](https://github.com/kubernetes-sigs/controller-runtime/blob/53fc44b56078cd095b11bd44cfa0288ee4cf718f/vendor/github.com/go-logr/logr/logr.go#L70-L73) as the levels(0,1,2,...) go up e.g 0 is considered standard Info, 1 could be considered Debug(less important), 2 is like more Debug(even less important). 
No levels map to Warn or Fatal which are generally more important than Info and Debug.

Zap levels are the inverse. -2(More Debug) -1(Debug), 0 (Info), 1(Warning) ...
https://godoc.org/go.uber.org/zap/zapcore#Level

But since zapr just flips the logr level it will only end up using the following zap levels: 0(Info), -1(Debug), -2(More Debug) ...
https://github.com/go-logr/zapr/blob/master/zapr.go#L133-L134
https://github.com/go-logr/zapr/blob/master/zapr.go#L34-L37

So zapr's mapping is correct.

In practice because the runtime's helper uses either [Development](https://godoc.org/go.uber.org/zap#NewDevelopment) or [Production](https://godoc.org/go.uber.org/zap#NewProduction) configs for zapr, we can only see 2 (zap)levels of logs.
- Production => zap.Info(0) and higher
  - so only logr.V(0) => zap.V(0). Remember logr.V(-1) is illegal.
- Development => zap.Debug(-1) and higher
  - so that gives us logr.V(1) => zap.V(-1) and  logr.V(0) => zap.V(0) and 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/runtime/log/log.go#L39-L48

Since logr.V(2) or zap.V(-2) is a custom Debug level those logs will not show up. So logr.V(2) is pointless if we're using the runtime's [`ZapLogger(development bool)`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/runtime/log/log.go#L36) method.

That's why the runtime only has 2 levels of logs statements right now. 
[Info or logr.V(0)](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L121) and [Debug logr.V(1)](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L232)

Comment (LiliC) [reply pkg/logutil/log_util.go]: > And if we must have consts then they should only be VInfo=0 and VDebug=1.
Warnings or VWarn is going against the logr since there is no level for warnings and V(1) is not a warning.

We agreed on warning to be 0 in the meeting as summed up
https://github.com/operator-framework/operator-sdk/issues/503#issuecomment-432764973

But yes, reading the logr docs again and:

> I restrict the API to just 2 types of logs: info and error.

So should we then just go with info and error only, as it also has no concept of debug either and not assign "names" to numbers as suggested by logr docs?

Comment (shawn-hurley) [reply pkg/logutil/log_util.go]: > I would prefer not to use these consts and just use logr.V(0)( which is justlogr.Info()) and logr.V(1).

👍 

I think it is just easier to deal with IMO.

File: doc/dev/logging.md [hunk 14]
```diff
@@ -0,0 +1,105 @@
+# Logging in operators
```
Comment (hasbro17) [inline doc/dev/logging.md]: @estroz Forgot one last nit. This should be in `doc/user/logging.md`
`doc/dev` is for developers of the SDK.
