### PR TITLE
run --olm: create one ConfigMap per package

### LINKED ISSUE #2923: unable to deploy with operator-sdk run --olm
## Bug Report

I'm deploying my operator with this command
```
operator-sdk run --olm --olm-namespace openshift-operator-lifecycle-manager --operator-namespace namespace-configuration-operator --install-mode=OwnNamespace=namespace-configuration-operator --operator-version $new_version
```

the operator deployment hangs in pending state:
image

see in attachment the csv, install plan.
[install-plan.txt](https://github.com/operator-framework/operator-sdk/files/4545746/install-plan.txt)
[csv.txt](https://github.com/operator-framework/operator-sdk/files/4545748/csv.txt)

A hint that something is wrong here is the fact that this operator defines 3 crds: userconfig, groupconfig, namespaceconfig. In the install plan though we can see 4 crds: 2 versions for namespaceconfig and 2 versions for groupconfigs:

image

The operator seems to be stuck when it tries to install the second set of versions.

**What did you do?**
see above

**What did you expect to see?**
operator correctly installed

**What did you see instead? Under which circumstances?**
see above

**Environment**
* operator-sdk version:

```
operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* go version:

```
go version
go version go1.13.9 linux/amd64
```

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OCP

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
I don't have a workaround.

**Additional context**
First time I'm using the new `run --olm` command and I could be getting something wrong.

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
* internal/olm/operator: create one ConfigMap per package in a package manifests format, and deploy the registry with all ConfigMaps mounted

**Motivation for the change:** the package manifests format must be replicated in a pod's file system for consistent registry initialization.

Closes #2923 

/kind bug

### CODE REVIEW

File: internal/util/k8sutil/k8sutil.go [hunk 1]
```diff
@@ -120,11 +120,11 @@ func GetTypeMetaFromBytes(b []byte) (t metav1.TypeMeta, err error) {
...
-func FormatOperatorNameDNS1123(name string) string {
-	if len(validation.IsDNS1123Label(name)) != 0 {
-		return dns1123LabelRegexp.ReplaceAllString(name, "-")
+func FormatStringDNS1123(s string) string {
+	if len(validation.IsDNS1123Label(s)) != 0 {
+		return dns1123LabelRegexp.ReplaceAllString(s, "-")
 	}
-	return name
+	return s
 }
```
Comment (camilamacedo86) [inline internal/util/k8sutil/k8sutil.go:130]: I agree 100% with the change. But, should we not mark it as breaking change?

File: internal/olm/operator/internal/configmap.go [hunk 2]
```diff
@@ -26,87 +26,111 @@ import (
...
-	nn := types.NamespacedName{
-		Name:      getRegistryConfigMapName(pkgName),
-		Namespace: namespace,
+// getRegistryConfigMaps performs a List operation to get all ConfigMaps
+// labelled as belonging to an operator's registry created by operator-sdk.
+func (rr *RegistryResources) getRegistryConfigMaps(ctx context.Context, namespace string) ([]corev1.ConfigMap, error) {
+	list := corev1.ConfigMapList{}
+	opts := []client.ListOption{
+		client.MatchingLabels(makeRegistryLabels(rr.Pkg.PackageName)),
+		client.InNamespace(namespace),
```
Comment (camilamacedo86) [inline internal/olm/operator/internal/configmap.go:39]: These changes shows are 0% covered by tests. Could we add a few of then?

File: internal/util/k8sutil/k8sutil.go (hunk 1 above)
Comment (estroz) [reply internal/util/k8sutil/k8sutil.go:130]: This is an internal utility.

Comment (camilamacedo86) [reply internal/util/k8sutil/k8sutil.go:130]: It is true. It is in the internal. 👍

File: internal/olm/operator/internal/configmap.go (hunk 2 above)
Comment (estroz) [reply internal/olm/operator/internal/configmap.go:39]: Added an integration test case.

File: internal/util/k8sutil/k8sutil.go (hunk 1 above)
Comment (estroz) [reply internal/util/k8sutil/k8sutil.go:130]: Reverted, will do in a followup.

File: hack/tests/integration.sh [hunk 3]
```diff
@@ -4,7 +4,7 @@ set -eu
 
 source hack/lib/image_lib.sh
 
-export OSDK_INTEGRATION_IMAGE="quay.io/example/memcached-operator:v0.0.2"
+export OSDK_INTEGRATION_IMAGE="quay.io/example/memcached-operator:latest"
```
Comment (camilamacedo86) [inline hack/tests/integration.sh:7]: why we changed to latest?

Comment (estroz) [reply hack/tests/integration.sh:7]: The tag doesn't matter since the image is used however the test wants to use it. I just made it more general.

File: test/integration/operator_olm_test.go [hunk 4]
```diff
@@ -247,3 +248,99 @@ func OperatorPackageManifestBasic(t *testing.T) {
 	// "Remove operator after removal"
 	assert.NoError(t, opcmd.Cleanup())
 }
+
+func OperatorPackageManifestsMultiplePackages(t *testing.T) {
```
Comment (camilamacedo86) [inline test/integration/operator_olm_test.go:252]:
```suggestion
func TestOperatorPackageManifestsMultiplePackages(t *testing.T) {
```

File: test/integration/operator_olm_test.go [hunk 5]
```diff
@@ -178,12 +179,12 @@ func OperatorAnnotationsAllNamespaces(t *testing.T) {
 	assert.NoError(t, opcmd.Run())
 }
 
-func OperatorPackageManifestBasic(t *testing.T) {
+func OperatorPackageManifestsBasic(t *testing.T) {
```
Comment (camilamacedo86) [inline test/integration/operator_olm_test.go:182]:
```suggestion
func TestOperatorPackageManifestsBasic(t *testing.T) {
```

File: test/integration/operator_olm_test.go [hunk 6]
```diff
@@ -119,12 +120,12 @@ func OperatorAnnotationsBasic(t *testing.T) {
 	assert.NoError(t, opcmd.Cleanup())
 }
 
-func OperatorAnnotationsAllNamespaces(t *testing.T) {
+func OperatorBundleAllNamespaces(t *testing.T) {
```
Comment (camilamacedo86) [inline test/integration/operator_olm_test.go:123]:
```suggestion
func TestOperatorBundleAllNamespaces(t *testing.T) {
```

File: test/integration/operator_olm_test.go [hunk 7]
```diff
@@ -44,19 +44,20 @@ var (
...
-	t.Run("AnnotationsAllNamespaces", OperatorAnnotationsAllNamespaces)
-	t.Run("PackageManifestBasic", OperatorPackageManifestBasic)
+	t.Run("BundleBasic", OperatorBundleBasic)
+	t.Run("BundleAllNamespaces", OperatorBundleAllNamespaces)
+	t.Run("PackageManifestsBasic", OperatorPackageManifestsBasic)
+	t.Run("PackageManifestsMultiple", OperatorPackageManifestsMultiplePackages)
 }
 
-func OperatorAnnotationsBasic(t *testing.T) {
+func OperatorBundleBasic(t *testing.T) {
```
Comment (camilamacedo86) [inline test/integration/operator_olm_test.go:55]:
```suggestion
func TestOperatorBundleBasic(t *testing.T) {
```

File: test/integration/operator_olm_test.go (hunk 4 above)
Comment (estroz) [reply test/integration/operator_olm_test.go:252]: This is a sub-test of `TestOLMIntegration` and should never be run by itself, so I omitted the `Test` prefix. Ditto below.

File: test/integration/operator_olm_test.go [hunk 8]
```diff
@@ -44,19 +44,20 @@ var (
...
+		testImageTag = image
 	}
-	t.Run("AnnotationsBasic", OperatorAnnotationsBasic)
-	t.Run("AnnotationsAllNamespaces", OperatorAnnotationsAllNamespaces)
-	t.Run("PackageManifestBasic", OperatorPackageManifestBasic)
+	t.Run("BundleBasic", OperatorBundleBasic)
+	t.Run("BundleAllNamespaces", OperatorBundleAllNamespaces)
+	t.Run("PackageManifestsBasic", OperatorPackageManifestsBasic)
+	t.Run("PackageManifestsMultiple", OperatorPackageManifestsMultiplePackages)
 }
```
Comment (camilamacedo86) [inline test/integration/operator_olm_test.go:54]: Shows that we have many tests to call the same functions, would be better to have one test with many scenarios. However, it is fine.

Comment (estroz) [reply test/integration/operator_olm_test.go:54]: Agreed, this should be refactored. I think we need to incorporate refactoring unit tests into our test planning.

**Comment by estroz** [comment]
@camilamacedo86 the integration test case I added covers this fix, since OLM will not be able to find the CRD in the `stable` channel unless each package gets its own `ConfigMap`.
